### ISSUE TITLE
No protection against accidentally starting multiple client or server instances

### ISSUE THREAD

**Issue by alexforencich** [symless/synergy#5818] opened 2017-01-25 23:18 UTC
It is possible for the GUI to get disassociated from the corresponding client/server process so that 1. the GUI does not accurately report that the client/server is running, 2. the running client/server can't be stopped without the task manager (or equivalent), and 3. an additional client/server instance can be started or is automatically started when the GUI is re-opened, which conflicts with the already running instance.  Shouldn't be a major change to have the GUI process check to see if synergyc/synergys is already running when the GUI starts up and take action accordingly (either report that it is running or kill it and restart it).

**Comment by nlyan** [comment] 2017-01-26 00:18
We do this on Windows. The GUI connects to the Windows service, which actually starts and stops Synergy itself. We are planning on expanding this model in 1.9.x

**Comment by EqUaTe** [comment] 2017-02-16 08:40
It's worth considering the scenario where you actually *want* multiple clients running..

For example, I have a system that I usually control from one on one side, but I also have a laptop sat the other side that I occasionally want to use to control it. As long as this is still supported, then I have no issue, but I don't want to see this functionality removed entirely!

**Comment by XinyuHou** [comment] 2017-03-01 10:46
Duplicate of #5408

**Closed by XinyuHou** 2017-03-01 10:46 UTC

**Comment by CanadianJeff** [comment] 2019-05-04 05:19
I just noticed this in 1.10.x
