### ISSUE TITLE
[Feature Request] make synergy Icon black & white for OSX+Ubuntu

### ISSUE THREAD

**Issue by AbhimanyuAryan** [symless/synergy#5470] opened 2016-07-15 08:50 UTC
If possible can you guys make a clean icon for synergy that runs on top bar? 

OSX has two theme dark & light. Can we make this circle black & tick white(not particular whatever look better...shades of black/white)? Also this icon doesn't look good on mbp retina & desktops with higher resolution

<img width="700" alt="screen shot 2016-07-15 at 2 11 38 pm" src="https://cloud.githubusercontent.com/assets/8083613/16868757/0d84048c-4a97-11e6-860b-f643e19b70cb.png">

For Ubuntu 

![synergy](https://cloud.githubusercontent.com/assets/8083613/16868840/72e1014a-4a97-11e6-86f3-ecd4e7e7be6b.png)

**Comment by XinyuHou** [comment] 2016-07-18 16:13
Duplicate of #3791

**Closed by XinyuHou** 2016-07-18 16:13 UTC
