### ISSUE TITLE
Auto elevate doesn't work on server lock on screen

### ISSUE THREAD

**Issue by roufamatic-avalara** [symless/synergy#5175] opened 2016-01-06 16:47 UTC
Running 1.7.5 on Windows 8.1 as server and OSX 10.10 as client. The server is configured to go to sleep in less time than the client. 
- Configure PC to go to sleep and to show the lock screen on wakeup.
- Connect client (mac) to server (pc)
- With Mac client still awake, put server to sleep. (Repro'd this both with the sleep timer as well as manually putting it to sleep)
- Wake server by pressing some keys on the keyboard (control key is what I normally use).
- Move the mouse over to the client.

The mouse and keyboard for both server and client stop functioning. They remain locked until I use the mouse/keyboard physically attached to the client machine to manually stop the Synergy client (⌘T).

**Comment by roufamatic-avalara** [comment] 2016-01-07 21:07
It seems to only lock things up when you move the mouse from server to client before unlocking the server. As long as you keep the mouse on the server's screen you can log in and everything functions correctly.

**Comment by XinyuHou** [comment] 2016-01-11 19:38
@roufamatic-avalara 

Do you mean Synergy stops working when server is on lock screen?

**Comment by roufamatic-avalara** [comment] 2016-01-11 19:43
The keyboard and mouse stop functioning on the server as well as the client. I'm not able to e.g. type in my password on the server to unlock it once I drag the mouse to the client machine, or move the mouse cursor on the server, until I stop synergy on the client.

**Comment by XinyuHou** [comment] 2016-11-25 16:44
Duplicate of #5075

**Closed by XinyuHou** 2016-11-25 16:44 UTC
Labels: bug
