### ISSUE TITLE
Clipboard Not working

### ISSUE THREAD

**Issue by AlexisPotvin** [symless/synergy#5700] opened 2016-10-24 18:35 UTC
### Operating Systems

Server: Windows 10
Client: ubuntu 14.04
### Synergy Version

1.8.4
### Steps to reproduce bug

Clipboard sharing isn't working both from server to client or from client tot server. The options are enabled for both Drag and drop and clipboard sharing!  (it gray out)

![cant copy and paste](https://cloud.githubusercontent.com/assets/13211420/19658742/12afbfbe-99f7-11e6-805b-f300ccbd5391.png)
### Other info

This is my first use of the software it might be a problem with configuration. I checked the server has both the drag and drop and clipboard sharing enabled.

**Comment by XinyuHou** [comment] 2016-11-25 16:34
@AlexisPotvin 
Are you still experiencing this issue?

**Comment by QuAzI** [comment] 2016-12-11 12:07
Looks like #5715

**Comment by XinyuHou** [comment] 2016-12-30 13:25
Duplicate of #5729

**Closed by XinyuHou** 2016-12-30 13:25 UTC
