### ISSUE TITLE
Is it possible to emulate mouse gesture cross-platform

### ISSUE THREAD

**Issue by starkshaw** [symless/synergy#6137] opened 2017-08-30 15:50 UTC
### Operating Systems ###

Server: Ubuntu 16.04 LTS
Client: macOS Sierra 10.12.6

### Synergy Version ###

1.7.6 (Ubuntu)
1.8.8 (macOS)

### Steps to reproduce bug ###

Currently using Logitech Master 2S as the mouse. Has been configured on macOS by Logitech Options. Seems like those gestures I set don't work with Synergy when I hover the mouse to the macOS side. Is there anyway that I can simulate Logitech gestures?

### Other info ###
 
Thanks.

**Comment by XinyuHou** [comment] 2017-09-05 14:44
Duplicate of #2905

**Closed by XinyuHou** 2017-09-05 14:44 UTC
