### ISSUE TITLE
Cursor loses position when displays are scaled differently

### ISSUE THREAD

**Issue by birdman7260** [symless/synergy#5547] opened 2016-08-18 03:57 UTC
In my situation I have a client that has multiple displays: one at 1440 and one is 4k. At first I wasn't used to how small the text is on my 4k monitor so I upped the scaling (Change the size of text, apps, and other items) to be higher than 100% while I kept both the 1440 and the server's monitor at 100%. This caused an issue when moving my mouse from the 1440 to the 4k and vice versa: it would move from the 1440 onto the 4k and after reaching a certain point it would re-appear on the 1440 somewhat close to the edge that the 4k is on. If I keep moving towards the 4k it would be fine. If I move from the 4k to the 1440, the same issue occurs.

I tried it again with the resolution matching and it still occurred so it definitely has to do with two monitors having differing scaling.

1. Have a client with two monitors.
2. Set one monitor to have scaling above 100% and set the other to have 100%
3. When moving the mouse from one monitor to the other, the pointer snaps back to the first after a short distance.

**Comment by XinyuHou** [comment] 2016-08-22 12:44
Duplicate of #5146

**Closed by XinyuHou** 2016-08-22 12:44 UTC
