### ISSUE TITLE
Synergy 1.4.16 on Debian Jessie ARM

### ISSUE THREAD

**Issue by Ulincsys** [symless/synergy#5504] opened 2016-07-25 17:23 UTC
Synergy starts with error:
>"Synergy terminated unexpectedly with an exit code of 1."

System info:
>
Linux - Debian
Kernel - 4.4.11-ntc (armv7l)
Processor - Allwinner R8
Computer system - [C.H.I.P.](https://getchip.com/)

A notice to readers, this issue is NOT a duplicate of #4814 or #5068 (denoted by ARCH=ARM)

Log info:
>
NOTE: starting client
NOTE: config file: /tmp/qt_temp.MTJ599
NOTE: log level: INFO
NOTE: log file: /var/log/synergy.log
ERROR: ld.so: object 'usr/$LIB/libstdc++.so.6' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
2016-07-25T07:08:46 INFO: Synergy 1.4.16 Client on Linux 4.4.11-ntc #1 SMP Sat May 28 00:27:07 UTC 2016 armv7l
	/build/synergy-M6oALT/synergy-1.4.16/src/lib/synergy/CClientApp.cpp,157
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  53 (X_CreatePixmap)
  Value in failed request:  0x0
  Serial number of failed request:  16
  Current serial number in output stream:  17
NOTE: stopping synergy desktop process

**Comment by XinyuHou** [comment] 2016-08-02 16:05
Duplicate of #5087
It's fixed in 1.8.3 which is not release yet. Please sit tight.

**Closed by XinyuHou** 2016-08-02 16:05 UTC
