### ISSUE TITLE
ESC key on shiny new mac touchbar not sent to linux client

### ISSUE THREAD

**Issue by ebullient** [symless/synergy#6123] opened 2017-08-09 13:09 UTC
### Operating Systems ###

Server: macOS Sierra
Client: Ubuntu Xenial (16.04.3)

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

Try using VI in Ubuntu Client.
Get stuck. =)

The ESC key on the new shiny macbooks is tucked up in the ridiculous touch bar. Mac itself has dealt with it (vim and all things regard the non-physical button as a normal keypress). Synergy seems not to know the psuedo-button was pressed. Running `xev` in the linux client shows no response whatever to touching the button in the touch bar.

### Other info ###

* When did the problem start to occur? When I...

tried to use vi for the first time on my linux client from my new shiny macbook pro with this touchbar contraption.

* Is there a way to work around it? No/Yes, you can...

Not from synergy. I have to resort to the on-screen keyboard in ubuntu to push ESC instead.

* Does this bug prevent you from using Synergy entirely? Yes/No

I can use Synergy, but having to use the on-screen keyboard is awkward at best.

**Comment by XinyuHou** [comment] 2017-08-11 10:06
Duplicate of #5780

**Closed by XinyuHou** 2017-08-11 10:06 UTC
