### ISSUE TITLE
Cursor stuck on Client side but Ctrl+Alt+Del is passed to Server side

### ISSUE THREAD

**Issue by vrtareg** [symless/synergy#5459] opened 2016-07-12 09:10 UTC
Hi Team

I have something similar to  #5397 but in my case I can constantly reproduce problem and it is happening on both 1.7 and latest 1.8 beta:

* Server side Win 7 x64
* Client side CentOS release 6.7 (Final) "Linux 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
* Synergy 1.8.1 both sides

Scenario is the following
* Logged in to Windows:
I can move mouse between the Server and client without any problem and lock and unlock CentOs screen without problems.
* Locking windows screen
Interesting stuff starting from this stage.
If mouse in windows area I can press Ctrl+Alt+Del and unlock windows without the problem.
While Windows locked I will try to move mice to the Linux area it goes crazy and stucks in Linux top right screen.
I can type in Linux side to unlock the screen but I can't use mouse - only keyboard.
I can press Ctrl+Alt+Del but it does not affect Linux side at all - it onl affect Windows side as it bring login prompt which is unusable as mice and keyboard are on Client side.

Please see some debug logs from server and client ...
Please let me know if you need more.

Regards,
Areg

[synergy-debug001.log.4392.txt](https://github.com/symless/synergy/files/358932/synergy-debug001.log.4392.txt)
[synergy-debug001.log.4393.txt](https://github.com/symless/synergy/files/358935/synergy-debug001.log.4393.txt)
[synergy-debug001.log.4394.txt](https://github.com/symless/synergy/files/358934/synergy-debug001.log.4394.txt)
[synergy-debug002.log.11962.txt](https://github.com/symless/synergy/files/358933/synergy-debug002.log.11962.txt)
[synergy-debug002.log.11963.txt](https://github.com/symless/synergy/files/358931/synergy-debug002.log.11963.txt)
[synergy-debug002.log.11964.txt](https://github.com/symless/synergy/files/358930/synergy-debug002.log.11964.txt)
[synergy-server.txt](https://github.com/symless/synergy/files/358938/synergy-server.txt)

**Comment by vrtareg** [comment] 2016-07-12 09:27
Forgot to mention that I got dual screen on server side if it could affect configuration ....

**Comment by harpss1ngh** [comment] 2016-07-15 14:46
Same issue here - 

Server - Windows 10 with dual screens 
Client - Single Screen Windows 7

CTRL+ALT+DEL to the Client doesn't work and I observed this info in the Log:

[2016-07-15T15:44:44] INFO: switch from "CS00006189" to "tux164" at 3830,1079
[2016-07-15T15:44:45] INFO: entering screen
[2016-07-15T15:44:45] INFO: switch from "tux164" to "CS00006189" at 0,1061
[2016-07-15T15:44:45] INFO: leaving screen
[2016-07-15T15:44:50] NOTE: client "CS00006189" has disconnected
[2016-07-15T15:44:50] INFO: jump from "CS00006189" to "tux164" at 960,540
[2016-07-15T15:44:50] INFO: entering screen
[2016-07-15T15:44:56] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-07-15T15:44:56] NOTE: accepted client connection
[2016-07-15T15:44:56] INFO: accepted secure socket
[2016-07-15T15:44:56] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-07-15T15:44:56] NOTE: client "CS00006189" has connected
[2016-07-15T15:45:05] INFO: switch from "tux164" to "CS00006189" at 0,662
[2016-07-15T15:45:05] INFO: leaving screen
[2016-07-15T15:45:08] NOTE: disconnecting client "CS00006189"
[2016-07-15T15:45:08] INFO: jump from "CS00006189" to "tux164" at 960,540
[2016-07-15T15:45:08] INFO: entering screen
[2016-07-15T15:45:08] NOTE: client "CS00006189" has disconnected
[2016-07-15T15:45:09] NOTE: stopped server
[2016-07-15T15:45:09] WARNING: detected application not running, pid=12924
[2016-07-15T15:45:10] INFO: backing off, wait=2s, failures=1
[2016-07-15T15:45:12] INFO: starting new process
[2016-07-15T15:45:12] INFO: activeDesktop:Default
[2016-07-15T15:45:12] INFO: starting new process
[2016-07-15T15:45:13] INFO: drag and drop enabled
[2016-07-15T15:45:13] ERROR: failed to get desktop path, no drop target available, error=2
[2016-07-15T15:45:13] NOTE: started server, waiting for clients
[2016-07-15T15:45:13] INFO: watchdog status: ok
[2016-07-15T15:45:19] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-07-15T15:45:19] NOTE: accepted client connection
[2016-07-15T15:45:19] INFO: accepted secure socket
[2016-07-15T15:45:19] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-07-15T15:45:19] NOTE: client "CS00006189" has connected

**Comment by XinyuHou** [comment] 2016-07-18 16:20
Duplicate of #5294

**Closed by XinyuHou** 2016-07-18 16:20 UTC
