### ISSUE TITLE
Chrome OS support for chrome devices with Android apps

### ISSUE THREAD

**Issue by ejmichel** [symless/synergy#5933] opened 2017-03-27 17:15 UTC
I am wondering about possible support for the new versions of Chromebooks that support Android apps.

Will you be able to add these devices to your supported OS? 

here is the list of support devices for Android apps 
https://sites.google.com/a/chromium.org/dev/chromium-os/chrome-os-systems-supporting-android-apps?visit_id=1-636262316042700219-1477039966&rd=1

I use ChromeOS (chromebox) mainly with only one Windows PC for legacy programs that are not going to port to chrome or Android. 

Currently am using chrome remote desktop which is ok but not ideal...loved your product when i had several windows pcs

thanks

**Comment by XinyuHou** [comment] 2017-03-30 12:14
Duplicate of #3363

**Closed by XinyuHou** 2017-03-30 12:14 UTC
