### ISSUE TITLE
Media key support for Mac clients

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3305] opened 2014-10-13 06:54 UTC
https://github.com/symless/synergy-enterprise/issues/55

**Imported issue:**

* Author: Douglas Mayle
* Date: 2012-09-19 02:29:36
* Legacy ID: 3375

**Steps to reproduce:**

Synergy Mac Clients do not currently support Media keys for a couple of reasons:

1. The Synergy keymap is built up from keyboard layouts, and keyboard layouts don't contains multimedia keys.
2. CGEventCreateKeyboardEvent is unable to create a multimedia event, probably for the same reason as above.

I handle the first problem by manually adding these keys to the s_controlKeys structure.  To handle the second problem, I wrote a separate application to listen in on and serialize these multimedia events.  I then wrote a patch to build a custom event from these serialized events in the case of volume up, down, and mute.  To my knowledge, this is the only way possible to simulate these keypresses (the other solution I've seen is to watch for these keypresses, and directly interact with the sound system, which introduces all sorts of edge cases not worth dealing with)

I can't see how to attach a file, so I'm pasting the contents of the patch into the 'Additional comments' section.

I believe I'm leaking CFDataRef's, though since I'm unsure as to the required lifetime with regards to posting the event, I've left it as an exercise for whomever accepts this patch.  I'm not a Mac application developer, and given the number of times I press Vol Up/Down/Mute before launching, I'm okay with the leaks on my system, as long as the volume keys work.

**Versions and operating systems:**

I have only tested this on OSX Mountain Lion as a client, talking to a Linux (Ubuntu) server. The Linux server is running 1.4.10, and my patch was against trunk.

**Temporary workarounds:**

None

**Additional comments:**

    Index: src/lib/platform/COSXKeyState.cpp
    ===================================================================
    --- src/lib/platform/COSXKeyState.cpp	(revision 1659)
    +++ src/lib/platform/COSXKeyState.cpp	(working copy)
    @@ -36,6 +36,20 @@
     static const UInt32 s_superVK    = kVK_Command;
     static const UInt32 s_capsLockVK = kVK_CapsLock;
     static const UInt32 s_numLockVK  = kVK_ANSI_KeypadClear; // 71
    +
    +const UInt8 VolUp_Press[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x44, 0x34, 0x00, 0x00, 0x44, 0x92, 0x20, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0xB0, 0xAB, 0x9F, 0x70, 0x00, 0x00, 0x17, 0x86, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x00, 0x0B, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +const UInt8 VolUp_Release[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x44, 0x34, 0x00, 0x00, 0x44, 0x92, 0x20, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0xA9, 0xFE, 0x64, 0xF0, 0x00, 0x00, 0x17, 0x86, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x00, 0x0A, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +const UInt8 VolDown_Press[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x43, 0xFE, 0x00, 0x00, 0x44, 0x9E, 0x00, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0x8C, 0x11, 0x65, 0xC0, 0x00, 0x00, 0x18, 0xCE, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x01, 0x0A, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +const UInt8 VolDown_Release[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x43, 0xFE, 0x00, 0x00, 0x44, 0x9E, 0x00, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0x91, 0xCD, 0xB8, 0x60, 0x00, 0x00, 0x18, 0xCE, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x01, 0x0B, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +const UInt8 Mute_Press[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x43, 0x99, 0x80, 0x00, 0x44, 0x5A, 0x40, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0x25, 0x88, 0x1E, 0xD8, 0x00, 0x00, 0x18, 0xFC, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x07, 0x0A, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +const UInt8 Mute_Release[] = { 0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x40, 0x35, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x40, 0x36, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x37, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x02, 0xC0, 0x38, 0x43, 0x99, 0x80, 0x00, 0x44, 0x5A, 0x40, 0x00, 0x00, 0x02, 0xC0, 0x39, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x3A, 0x2B, 0xBA, 0x93, 0xA8, 0x00, 0x00, 0x18, 0xFC, 0x00, 0x01, 0x40, 0x3B, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x40, 0x33, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x40, 0x6B, 0x00, 0x00, 0x07, 0x80, 0x00, 0x01, 0x40, 0x53, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0F, 0x40, 0x54, 0x00, 0x07, 0x0B, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
    +
    +
     #else
     // Hardcoded virtual key table on 10.4 and below.
     static const UInt32 s_shiftVK    = 56;
    @@ -103,6 +117,11 @@
     	{ kKeyKP_Divide,	kVK_ANSI_KeypadDivide },
     	{ kKeyKP_Subtract,	kVK_ANSI_KeypadMinus },
     	{ kKeyKP_Enter,		kVK_ANSI_KeypadEnter },
    +
    +        // Multimedia keys with virtual key codes
    +	{ kKeyAudioUp,		kVK_VolumeUp },
    +	{ kKeyAudioDown,	kVK_VolumeDown },
    +	{ kKeyAudioMute,	kVK_Mute },
     #else
       // Hardcoded virtual key table on 10.4 and below.
     	// cursor keys.
    @@ -490,9 +509,35 @@
     			LOG((CLOG_DEBUG1 "  %%%%%%%%03x (%%%%%%%%08x) %%%%%%%%s", keystroke.m_data.m_button.m_button, keystroke.m_data.m_button.m_client, keystroke.m_data.m_button.m_press ? "down" : "up"));
     
     		// let system figure out character for us
    -		ref = CGEventCreateKeyboardEvent(0, mapKeyButtonToVirtualKey(
    -									keystroke.m_data.m_button.m_button),
    -								keystroke.m_data.m_button.m_press);
    +		if (mapKeyButtonToVirtualKey(keystroke.m_data.m_button.m_button) == kVK_VolumeUp) {
    +			if (keystroke.m_data.m_button.m_press) {
    +				CFDataRef data_press = CFDataCreate(kCFAllocatorDefault, VolUp_Press, sizeof(VolUp_Press));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_press);
    +			} else {
    +				CFDataRef data_release = CFDataCreate(kCFAllocatorDefault, VolUp_Release, sizeof(VolUp_Release));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_release);
    +			}
    +		} else if (mapKeyButtonToVirtualKey(keystroke.m_data.m_button.m_button) == kVK_VolumeDown) {
    +			if (keystroke.m_data.m_button.m_press) {
    +				CFDataRef data_press = CFDataCreate(kCFAllocatorDefault, VolDown_Press, sizeof(VolDown_Press));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_press);
    +			} else {
    +				CFDataRef data_release = CFDataCreate(kCFAllocatorDefault, VolDown_Release, sizeof(VolDown_Release));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_release);
    +			}
    +		} else if (mapKeyButtonToVirtualKey(keystroke.m_data.m_button.m_button) == kVK_Mute) {
    +			if (keystroke.m_data.m_button.m_press) {
    +				CFDataRef data_press = CFDataCreate(kCFAllocatorDefault, Mute_Press, sizeof(Mute_Press));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_press);
    +			} else {
    +				CFDataRef data_release = CFDataCreate(kCFAllocatorDefault, Mute_Release, sizeof(Mute_Release));
    +				ref = CGEventCreateFromData(kCFAllocatorDefault, data_release);
    +			}
    +		} else {
    +			ref = CGEventCreateKeyboardEvent(0, mapKeyButtonToVirtualKey(
    +										keystroke.m_data.m_button.m_button),
    +									keystroke.m_data.m_button.m_press);
    +		}
     		if (ref == NULL) {
     			LOG((CLOG_CRIT "unable to create keyboard event for keystroke"));
     		}

**Comment by ManjotS** [comment] 2015-02-16 02:13
Please fix this

**Comment by 3nki** [comment] 2015-02-18 20:56
+1

**Comment by nbolton** [comment] 2015-03-06 13:17
@XinyuHou @speaker - could one of you turn this into a PR please?

**Comment by andrewbolster** [comment] 2015-06-09 08:49
Sorry to butt in but is it not more sustainable to add a "passthrough" option in the hotkey setup instead of hard-coding a key table? 

In my case (#4365) my "media keys" aren't standard but are just ergonomically convenient for my keyboard. 

This would need a bit more engineering to have the hotkey dialog not actually bind to key combinations until after configuration, but would at least be setup in the config file.

Also this solution breaks the use case where the media is playing on the client not the server, which could surprise some people.

**Comment by jpoet** [comment] 2015-09-15 20:56
I just started using Synergy, and Synergy handling the media keys would make it much more useful to me.

andrewbolster, I see that #4365 was closed, but I can't tell why.  Do you know if this has been fixed some other way?

**Comment by jpoet** [comment] 2015-09-15 21:02
Douglas Mayle, you mention that your fix requires a combination of the patch plus another application.  I see the patch, but I don't see where to get the application.  Is there some place I can get it?

**Comment by kyrsjo** [comment] 2015-09-29 09:52
This enhancement would be great, especially if I could set the media keys (the volume & mute!) to always be sent to a specific machine, i.e. the machine which has the speakers.

The track skip buttons are perfect for changing which computer I'm working on, so please make it possible to specify *which* buttons should be forwarded...

Setup: Linux server/mac client (this works flawlessly, the other way not so well).

**Comment by davecotter** [comment] 2016-03-22 20:04
also add cmd-option-escape :)

**Comment by eezynow** [comment] 2016-04-19 11:05
i am a synergy user who made a github account solely to PLEAD right here for this change.  i iwas using another app called transmission but synergy is a fabulous tool to skate seamlessly between my macbook and mac mini home setup... but why can't i use ALL my keys? if i was trying to go from linux to os x or os x to windows i would expect there might be issues but.....  this is os x to os x...  having the ability to use the volume up, down and mute keys should be bog standard. i forked out $10USD but would happily fork out (a little) more to be able to use my keyboard's volume and mute keys.

**Comment by jfrisvold** [comment] 2016-08-22 16:47
Running the latest 1.8.3-RC1-e36a7ae release on an OS X El Capitan 10.11.6 server with a macOS Public Beta 5 client.  If I understand correctly, this release should let me use the volume up/down keys on the client.  If that's the case, then this isn't working for me.  Pressing the volume keys triggers volume up/down on the server and not the client.

**Comment by dmland** [comment] 2016-08-24 00:26
Possible duplicate of #1320?

**Comment by nlyan** [comment] 2016-09-08 11:05
Confirmed brightness up and down and volume up and down keys are not working. Note that these keys do currently work between Windows servers and Mac clients

**Comment by dacohenii** [comment] 2016-09-14 19:33
Just installed 1.8.3-RC1-e36a7ae, and I can happily report that volume (up/down) and media keys (prev/play/next) are working on my windows server!

My machines:
Client: OSX 10.11.6
Server: Windows 10 x64

Not sure how to test brightness control, etc. from a Windows server (or if that's even possible). 

Thanks a lot for your hard work on this and everything else, Synergy Team!

**Comment by nlyan** [comment] 2016-09-15 09:30
@dacohenii thanks. We know there's a huge backlog of issues to resolve at the moment and we really appreciate positive feedback.

**Closed** 2016-09-19 14:49 UTC
Labels: enhancement

**Comment by jfrisvold** [comment] 2016-09-20 17:07
Brilliant!  1.8.3 RC2 and I can report that media keys work properly on my setup now.  Mac Server and Mac Client.  Works exactly as expected.

**Comment by nlyan** [comment] 2016-09-21 10:02
Note that there are still some issues mapping brightness keys on Windows servers (e.g. with macOS clients) but this is a broader issue than just supporting macOS media keys.

**Comment by dacohenii** [comment] 2016-09-22 14:37
@nlyan Just wondering...what keys will be used for Windows servers with macOS clients? Will the keyboard on the Windows server need to have brightness keys (or perhaps a `fn` key) for this to work?

**Comment by nlyan** [comment] 2016-09-23 10:39
@dacohenii There are no standard key codes for brightness up / down. What we do is map everything internally to the X11 key symbol (used on Linux), which does actually define fixed codes for these keys (and a whole lot of other functions from the "Internet keyboard" era).

The problem atm is our Windows server code isn't capable of passing enough key information to Synergy to perform the mapping (which we have to do more or less manually for each platform).

We'll swing around to it in a future release.

**Comment by darrenswhite** [comment] 2016-10-10 14:44
This doesn't seem to be working on Ubuntu 16.04 64-bit (server) and Windows 7 64-bit (client).

Log is below:

`[2016-10-10T15:42:01] DEBUG: starting process
[2016-10-10T15:42:01] INFO: starting server
[2016-10-10T15:42:01] INFO: command: /usr/bin/synergys -f --no-tray --debug DEBUG --name *** -c /tmp/qt_temp.T32393 --address :24800
[2016-10-10T15:42:01] INFO: config file: /tmp/qt_temp.M32393
[2016-10-10T15:42:01] INFO: log level: DEBUG
[2016-10-10T15:42:01] DEBUG: opening configuration "/tmp/qt_temp.T32393"
[2016-10-10T15:42:01] DEBUG: configuration read successfully
[2016-10-10T15:42:01] DEBUG: plugins dir: /home/***/.synergy/plugins
[2016-10-10T15:42:01] DEBUG: can't open plugins dir: /home/***/.synergy/plugins
[2016-10-10T15:42:01] DEBUG: XOpenDisplay(":0")
[2016-10-10T15:42:01] DEBUG: xscreensaver window: 0x00000000
[2016-10-10T15:42:01] DEBUG: screen shape: 0,0 5120x1600 (xinerama)
[2016-10-10T15:42:01] DEBUG: window is 0x03800004
[2016-10-10T15:42:01] DEBUG: adopting new buffer
[2016-10-10T15:42:01] DEBUG: opened display
[2016-10-10T15:42:01] WARNING: failed to register hotkey AudioPrev (id=e0b1 mask=0000)
[2016-10-10T15:42:01] WARNING: failed to register hotkey AudioPlay (id=e0b3 mask=0000)
[2016-10-10T15:42:01] WARNING: failed to register hotkey AudioStop (id=e0b2 mask=0000)
[2016-10-10T15:42:01] DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=1
[2016-10-10T15:42:01] NOTE: started server, waiting for clients
[2016-10-10T15:42:01] DEBUG: event queue is ready
[2016-10-10T15:42:01] DEBUG: add pending events to buffer
[2016-10-10T15:42:01] DEBUG: screen "***" shape changed
[2016-10-10T15:42:01] WARNING: failed to register hotkey AudioNext (id=e0b0 mask=0000)
[2016-10-10T15:42:01] NOTE: accepted client connection
[2016-10-10T15:42:01] DEBUG: received client "***" info shape=0,0 1600x900 at 0,0
[2016-10-10T15:42:01] NOTE: client "***" has connected`

**Comment by darrenswhite** [comment] 2016-10-17 14:48
Still happening in 1.8.4

**Comment by neumant** [comment] 2018-02-05 15:19
Has this feature been able to be completed yet at this point? Or still something that needs a little more time?

**Comment by nlyan** [comment] 2018-03-18 20:14
This is working between macOS and Windows yes. Linux support was also tested. If there's a problem please open a new issue
