### ISSUE TITLE
Mouse highlights Terminal (Mac server) when using Excel (Windows client)

### ISSUE THREAD

**Issue by davewaxman** [symless/synergy#4430] opened 2015-03-11 13:42 UTC
Server: OS X 10.10.3 and Synergy 10.6.2
Client: Windows 7 Enterprise v6.1.7600 and Synergy 10.6.2

Often when moving my mouse and hilighting text on the Windows client (mostly in Microsoft Excel) text will get hilighted on windows (mostly terminal.app) on my Mac OS X machine. 

I can not always get it to duplicate this behavior, but it happens at least two to three times a day.

How can I assist you further in diagnosis?

**Comment by XinyuHou** [comment] 2017-04-21 15:44
Duplicate of #4300

**Closed by XinyuHou** 2017-04-21 15:44 UTC
Labels: bug
