### ISSUE TITLE
Windows multiple monitors with different scaling causes mouse to loop

### ISSUE THREAD

**Issue by birdman7260** [symless/synergy#6104] opened 2017-07-17 03:07 UTC
### Operating Systems ###

Server: Windows 10 version 1607
Client: Windows 10 version 1703

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

1. Client has 2 monitors
2. One monitor has Scale set to 150%, the other monitor has Scale set to 100%
3. Drag mouse across the two monitors
4. If traveling from Left monitor to Right monitor it will:
Enter Right monitor
When it has moved a small distance right, it will teleport back to Left monitor a small distance inward
If you move into Right monitor from that location it will move across just fine.
Here is a short (20 seconds) video showing the issue: https://youtu.be/TGU0k73fSWo

### Other info ###

* When did the problem start to occur? It has always occurred for me when my monitors are set to different scaling
* Is there a way to work around it? If the monitors have the same scaling it works fine, however that isn't a good workaround.
* Does this bug prevent you from using Synergy entirely? It does not, but it's incredibly frustrating yet I have no other options

Please let me know if any of this doesn't make sense. when you have a laptop with 4k resolution and a monitor with 1440 resolution, setting both to either 100% or 150% scale is just not an option. Getting this fixed would help me tremendously. Thank you.

Logs: https://pastebin.com/jVAdCvYL

Video (20 seconds): https://youtu.be/TGU0k73fSWo

Image showing specifically the "Scale" setting I'm referring to:
![image](https://user-images.githubusercontent.com/1872740/28254497-679daaa4-6a7b-11e7-9373-fb09aea53a70.png)

**Comment by XinyuHou** [comment] 2017-07-21 10:41
Duplicate of #5201

**Closed by XinyuHou** 2017-07-21 10:41 UTC
