### ISSUE TITLE
Server lose input after lock while cursor is on client

### ISSUE THREAD

**Issue by ezb2013** [symless/synergy#5501] opened 2016-07-25 14:46 UTC
If the server computer gets locked while using keyboard and mouse on client computer, then you can't restore mouse and keyboard functionality on server computer until you stop synergy on the client computer.

If the client computer gets locked, then the keyboard and mouse functionality automatically returns to the the server computer (as it should), but then I am unable to move the keyboard and mouse functionality back to the client, until I unlock the client computer using the keyboard directly connected to it.

**Comment by kbasar** [comment] 2016-07-27 01:57
I have exactly same problem with Synergy Basic software. It is very irritative because every time you lock main PC. You need to log-in to all clients and stop the service to enable mouse in server PC. without doing this I can't log-in in server because without mouse enabled in server I can't enter login password.

**Comment by thomaskcr** [comment] 2016-08-02 06:39
If you're talking about Windows machines you may be able to fix this by running synergy as an administrator. Less recommended but you can also disable the "control+alt+delete" feature of the login screen.

**Comment by kbasar** [comment] 2016-08-11 05:15
This problem can be solved easily if cursor disconnect client from server every time when Server PC is locked. Similarly when Server PC is unlocked /logged-in again connect back the cursors of all clients with server. Why cursor is on client when Server is locked? Simply disable the Synergy when Server PC is locked. Hope developer can get the idea what I am trying to say.

**Comment by vanowm** [comment] 2016-08-16 11:36
@thomaskcr running synergy as an administrator creates more side effects and issues that it's worth it...

@kbasar you suggested that unless client is locked you are able move cursor through synergy while server is locked? In my case I'm unable move cursor on client or server if by accident I moved it to client from locked server while on login screen (W10).
When that happens I either have to restart synergy on client using client's hardware mouse/keyboard or put server to sleep and when it wakes up cursor will be restored.

**Comment by kbasar** [comment] 2016-08-29 07:47
Last few weeks I stopped using synergy as it is kind of headache for me. My company policy got stricter and uncompromising- I am not in my desk, even for a minutes  to bring tea at my desk or want to goto wash room or to talking to some one, I must lock all my work station and my laptop. That is quite lot. Problem is when I come back after 2-3 minutes, I want to first log-in into my laptop(server) but I can't because Keyboard/mouse is not working in my laptop, Then I have to stop client in every client machine to get back my server mouse & keyboard. Long story short - it is more headache for me than company workstation safety policy.

**Comment by TxRxFx** [comment] 2016-09-20 13:44
I'm experiencing this same problem using build: 

1.8.2-rc1 12e0120 

on 
windows 7 (server) , Centos 7 (client) and windows 10 pro laptop (client).
(left to right screens in that order)

Even without synchronised screen saver option enabled if all three wind up in a screen saver state the mouse won't return to the locked windows 7 screen (server) if I leave the mouse off the server window before the screen savers kick in.

current workaround for me is to make sure mouse if back on server screen before leaving desk/screen saver starting.

Cheers!

**Comment by vanowm** [comment] 2016-10-29 16:46
Also, note, server looses input when locked and mouse moved on client. The client get keyboard input, but not mouse input (mouse no longer responds), because of that there is no way return input to server, without restarting synergy on client.

Server: Windows 10 x64
Client: WIndows 7 x64

Synergy 1.8.4-stable-a6ff907

**Comment by XinyuHou** [comment] 2016-11-25 16:44
Duplicate of #5075

**Closed by XinyuHou** 2016-11-25 16:44 UTC
Labels: bug

**Comment by ne0hisda0ne** [comment] 2018-11-14 19:56
This works.

https://github.com/symless/synergy-core/issues/5294#issuecomment-318669465
