### ISSUE TITLE
Potential memory leak on server

### ISSUE THREAD

**Issue by djbp** [symless/synergy#5549] opened 2016-08-18 08:26 UTC
Unfortunately, I don't have a great deal of information with regards to reproducing this issue as I have just noticed it.

Synergy is currently using 1.02GB RAM (according to Activity Monitor) on the server system. At the same time on the client, it is using 49MB & 'synergyc' is using ~44% CPU with another using < 1% CPU.

The server is a i7 Macbook Pro running OS X 11.11.
The client is a Mac Mini Core 2-Duo, running OS X 11.11
Synergy on both machines is 1.8.2-stable-36cd521

The uptime of the server will have been < 1 week. The client probably about 1 week, both machines with sleeps in between.

Quitting both apps on client and server and restarting them solves the problems.

It seems as though the client is spawning multiple 'synergyc' processes. There are always two running. When one (e.g. the high CPU usage one) is force-quit, it starts again. One of the two is always using a high CPU. The following is a log entry on the server over a <2-second period):
[2016-08-18T09:18:48] NOTE: accepted client connection
[2016-08-18T09:18:48] INFO: accepted secure socket
[2016-08-18T09:18:48] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:18:48] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:18:48] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:18:48] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:18:50] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:18:50] NOTE: accepted client connection
[2016-08-18T09:18:50] INFO: accepted secure socket
[2016-08-18T09:18:50] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:18:51] WARNING: a client with name "<client-name>" is already conne
cted
[2016-08-18T09:18:51] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:18:51] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:18:53] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:18:53] NOTE: accepted client connection
[2016-08-18T09:18:53] INFO: accepted secure socket
[2016-08-18T09:18:53] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:18:53] WARNING: a client with name "<client-name>" is alrea
dy connected
[2016-08-18T09:18:53] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:18:53] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:18:55] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:18:55] NOTE: accepted client connection
[2016-08-18T09:18:55] INFO: accepted secure socket
[2016-08-18T09:18:55] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:18:56] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:18:56] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:18:56] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:18:58] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:18:58] NOTE: accepted client connection
[2016-08-18T09:18:58] INFO: accepted secure socket
[2016-08-18T09:18:58] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:18:58] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:18:58] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:18:58] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:00] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:00] NOTE: accepted client connection
[2016-08-18T09:19:00] INFO: accepted secure socket
[2016-08-18T09:19:00] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:01] WARNING: a client with name 
"<client-name>" is already connected
[2016-08-18T09:19:01] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:01] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:03] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:03] NOTE: accepted client connection
[2016-08-18T09:19:03] INFO: accepted secure socket
[2016-08-18T09:19:03] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:03] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:19:03] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:03] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:05] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:05] NOTE: accepted client connection
[2016-08-18T09:19:05] INFO: accepted secure socket
[2016-08-18T09:19:05] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:06] WARNING: a client with name "<client-name>" is already 
connected
[2016-08-18T09:19:06] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:06] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:08] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:08] NOTE: accepted client connection
[2016-08-18T09:19:08] INFO: accepted secure socket
[2016-08-18T09:19:08] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:08] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:19:08] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:08] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:10] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:10] NOTE: accepted client connection
[2016-08-18T09:19:10] INFO: accepted secure socket
[2016-08-18T09:19:10] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:11] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:19:11] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:11] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:13] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:13] NOTE: accepted client connection
[2016-08-18T09:19:13] INFO: accepted secure socket
[2016-08-18T09:19:13] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:13] WARNING: a client with name "uk-75-dpay-01.
local" is already connected
[2016-08-18T09:19:13] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:13] NOTE: client "<client-name>" has disconnected
[2016-08-18T09:19:15] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-08-18T09:19:15] NOTE: accepted client connection
[2016-08-18T09:19:15] INFO: accepted secure socket
[2016-08-18T09:19:15] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-08-18T09:19:16] WARNING: a client with name "<client-name>" is already connected
[2016-08-18T09:19:16] NOTE: disconnecting client "<client-name>"
[2016-08-18T09:19:16] NOTE: client "<client-name>" has disconnected

**Comment by XinyuHou** [comment] 2016-08-22 12:43
Duplicate of #5138

**Closed by XinyuHou** 2016-08-22 12:43 UTC
