### ISSUE TITLE
Keyboard not working macOSSierra 10.12/Synergy 1.8/iMac Target Display Mode to Keyboard not shared when using Target Display Mode on Mac server

### ISSUE THREAD

**Issue by Doc70** [symless/synergy#5909] opened 2017-03-15 18:39 UTC
#Operating Systems

Server: macOS Sierra 10.12.3/iMac
Client: macOS Sierra 10.12.3/MacBookPro

Synergy Version

1.8.8

Steps to reproduce bug

Use Synergy on iMac as server, MacBook Pro as client; iMac in Target Display Mode (F2):

Activate server and client
Put iMac in Target Display Mode: Command+F2 on iMac shared keyboard
Move the shared mouse on the MacBookPro screen
At this point the mouse will move from iMac screen (target display mode) to MBP screen, but the keyboard will not get focus.

**Comment by XinyuHou** [comment] 2017-03-22 12:21
Duplicate of #5748

**Closed by XinyuHou** 2017-03-22 12:21 UTC
