### ISSUE TITLE
Auto switch client or server mode

### ISSUE THREAD

**Issue by taluq** [symless/synergy#4450] opened 2015-03-18 17:41 UTC
... depending on available network.

At home my keyboard and mouse are connected to a Linux server; I also have a Windows 8 Client and intermittently one or laptop clients (primary Win7 and secondary Linux).

While on road I want to use my primary Windows 7 laptop as a server, and use the second Win7 laptop as a client. I may also work in a place were I use some other PC as a server, and the two laptops -- again -- as clients.

The following is a concrete example:

1 Home: 172.17.2.xxx network, server is linux 172.17.2.1 
- Win7 laptop#1 (172.17.2.9) should connect to 172.17.2.1
- Linux laptop#2 (172.17.2.xxx) should connect to 172.17.2.1
- Note that at home Win7 laptops may also get addresses in 172.27.1.xxx network (WLAN), in that case they should still act as clients and connect to 172.17.2.1

2 Road warrior (using my own mobile USB HSDPA stick):
- Win7 laptop#1 gets IP 192.168.8.100, should act as server
- Linux laptop#2 gets IP 192.168.8.xxx, should connect to 192.168.8.100

3 Remote place #1
- Win7 laptop#1 gets IP aaa.bbb.ccc.ddd, should act as server
- Linux laptop#2 gets IP aaa.bbb.ccc.eee, should connect to aaa.bbb.ccc.ddd

4 Remote place#2
- Using computer ggg.hhh.iii.137 as server
- Win7 laptop#1 gets ip ggg.hhh.iii.201, should connect to ggg.hhh.iii.137
- Linux laptop#2 gets ip ggg.hhh.iii.yyy, should connect to ggg.hhh.iii.137

At home the laptops may also have 192.168.8.xxx addresses if the mobile stick is on, but connect to 172.17.2.1

Is this already possible?

**Comment by XinyuHou** [comment] 2017-04-21 15:52
Duplicate of #4232

**Closed by XinyuHou** 2017-04-21 15:52 UTC
Labels: enhancement
