### ISSUE TITLE
Alt + Numpad issue

### ISSUE THREAD

**Issue by cbreault** [symless/synergy#6058] opened 2017-06-07 21:03 UTC
### Operating Systems ###

Server: Windows 10.1 x64 Version 1703
Client: Windows 10.1 x64 Version 1604

### Synergy Version ###

1.9

### Steps to reproduce bug ###

Add any hotkey using Alt+KP (numpad) not working.

No information shows in logs either, it's like the key isn't even being pressed.

I would like to use Alt+KP_1 etc to transfer key presses to my client machine.

**Comment by XinyuHou** [comment] 2017-06-30 14:18
Duplicate of #4326

**Closed by XinyuHou** 2017-06-30 14:18 UTC
