### ISSUE TITLE
Mouse click on client does not work

### ISSUE THREAD

**Issue by Not-Steve1** [symless/synergy#6148] opened 2017-09-12 04:09 UTC
### Operating Systems ###

Server: Windows 10 Education (desktop)
Client: Windows 10 Home (Surface 3)

### Synergy Version ###

1.8.8-stable-25a8cb2 on both

### Steps to reproduce bug ###

Did a uninstall and reinstall on server. Did a fresh install on client. Keyboard works fine. Mouse movement works fine. All mouse clicks DOES NOT work.

### Other info ###
This bug started half a year ago and was waiting for a fix for more than a month. I was fed up with no fix for such a major issue so I stopped using this. I gave this another chance today and STILL NO FIX half a year later. Back then I could make 2-3 clicks by restarting the server side but now that does not even work.

* When did the problem start to occur? A LOOONG time ago.
* Is there a way to work around it? No and I'm tired trying to make this work.
* Does this bug prevent you from using Synergy entirely? absolutely Yes

**Comment by XinyuHou** [comment] 2017-09-13 14:20
Duplicate of #5976

**Closed by XinyuHou** 2017-09-13 14:20 UTC
