### ISSUE TITLE
Complete loss of mouse control

### ISSUE THREAD

**Issue by bluenadas** [symless/synergy#5550] opened 2016-08-18 18:05 UTC
Running on 2 machines locally. About twice a day I have the issue where my mouse/keyboard are hung on both machines. Can't move mouse or use keyboard except to ctrl/alt/delete. Can operate within the menu there but once I go back to desktop, it is still hung (attempting to force close synergy). Eventually the system will unhang, but no really idea what is causing it to finally come back.

**Comment by XinyuHou** [comment] 2016-08-22 12:42
Duplicate of #5531

**Closed by XinyuHou** 2016-08-22 12:42 UTC
