### ISSUE TITLE
Cursor is lost when Windows server locks

### ISSUE THREAD

**Issue by legonigel** [symless/synergy#4348] opened 2015-02-04 05:11 UTC
I will try my best to describe the issue, but I cannot consistently replicate the issue. 
I have a server running on windows 8.1 synergy version 1.6.2 and a linux client with synergy version 1.7.0. The issue also existed when the client was running version 1.6.2.
Steps that can sometime replicate the issue.
1. Lock windows 8.1 machine
2. Move cursor from server to client
3. Cursor disappears on both screens
4. Mouse on server goes to sleep

Notes of issues after it happens:
- Keyboard is left bound to client
- Ctrl-Alt-Del is not captured by server (Ctrl-Alt-Del does nothing)
- Restarting the client synergyc will allow the cursor to reappear

I will update if I find anything else that can help find the issue. If there is something in particular that would help get this resolved.  It might also be an issue with my setup, because I compiled it myself and my install on the windows server might not be correct.

**Comment by nbolton** [comment] 2015-03-06 13:00
I think this happens because the process is re-launched when the user changes between sessions/desks -- but the way this is done is not very elegant.

**Comment by legonigel** [comment] 2015-03-06 18:19
I mostly encounter the issue when waking from sleep after locking, but what you said about changing sessions makes sense. The largest issue is that there is currently no way to recover the windows machine, other than doing a hard shutdown.

**Comment by XinyuHou** [comment] 2017-04-21 15:42
Duplicate of #5294

**Closed by XinyuHou** 2017-04-21 15:42 UTC
Labels: bug
