### ISSUE TITLE
Switching screens while Command prompt is in focus toggles my input method

### ISSUE THREAD

**Issue by fayf** [symless/synergy#6043] opened 2017-05-17 05:49 UTC
### Operating Systems ###

Server: Windows 10 (v1703 Creator's Update)
Client: Windows 10 (v1703 Creator's Update)

### Synergy Version ###

1.8.8-stable-25a8cb2 on both server and client.

### Steps to reproduce bug ###

1. Multiple input methods enabled on server
2. Command prompt or Bash is open and in focus
3. Move mouse over to client's screen
4. Input method of server changes to the next in the list (!?)

### Other info ###

* When did the problem start to occur? Since I started using it about 2 weeks ago (this was after the Creator's Update was applied)
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

My IME keyboard settings (thought it might be relevant)
![ime](https://cloud.githubusercontent.com/assets/1522199/26140070/4c9b77ac-3b07-11e7-87de-a9bf52da85d4.png)

Server logging
[server.txt](https://github.com/symless/synergy/files/1006680/server.txt)

**Comment by XinyuHou** [comment] 2017-05-22 11:02
Duplicate of #5530

**Closed by XinyuHou** 2017-05-22 11:02 UTC
