### ISSUE TITLE
Ubuntu client screen locks when Windows server is active

### ISSUE THREAD

**Issue by magic-mouse** [symless/synergy#4272] opened 2014-12-11 07:43 UTC
**Steps to reproduce:**

Don't use your slave machine for the duraiton of the time it takes to either lock or start screen saver. While use the master machine.

**Expected:** Slave machine should be "active" or considered active while server is active.

**Actual:** The screensaver activates, making login happen everytime.

**Temporary workarounds:**

Constant login.

Similar bugs:

Not found any

**Additional comments:**

Host is Windows 8.1, Slave is ubuntu 12.04 LTS

**Comment by XinyuHou** [comment] 2017-04-21 13:15
Duplicate of #5886

**Closed by XinyuHou** 2017-04-21 13:15 UTC
Labels: bug
