### ISSUE TITLE
One of two mice fail to work correctly on Client

### ISSUE THREAD

**Issue by AndrewRise** [symless/synergy#6047] opened 2017-05-19 20:12 UTC
Server: Windows 10  4k screen
Client: Windows 8.1  1080p
Synergy Version 1.8.8

Just installed Synergy and figured out I can use my 10$ Bluetooth mouse, but it is unusable with my 80$ mouse :) Cursor on client moves like jelly or even loses connection.
Tried all DPI settings on mouse, turned off other mice, same result. 
Video of test below:
https://youtu.be/InW2oKmxgBc

**Comment by XinyuHou** [comment] 2017-05-22 11:17
Duplicate of #4911

**Closed by XinyuHou** 2017-05-22 11:17 UTC
