### ISSUE TITLE
Giving hand to client when server not loged in on Windows 10

### ISSUE THREAD

**Issue by LittleLama** [symless/synergy#5702] opened 2016-10-25 09:57 UTC
### Operating Systems

Server: Windows 10 x64
Client: Windows 10 x86
### Synergy Version

1.8.4-stable-a6ff907
### Steps to reproduce bug
1. Turn on client unit and log in
2. Turn on server unit without loging in
3. Moving server mouse gives hand to client
4. Can't log in on server because it doesn't have the hand = BUG
5. The only way to give the hand back to server is to disconnect network wire or wifi from the client = PROBLEM
### How it should work

My opinion : When server is not loged in, don't give hand to client
Like others could think about it : Find a way to give the hand back to server even if it is not loged in

**Comment by XinyuHou** [comment] 2016-11-25 16:45
Duplicate of #5075

**Closed by XinyuHou** 2016-11-25 16:45 UTC
