### ISSUE TITLE
Pressing Command L in OSX locks screen in Windows

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#434] opened 2014-10-13 01:07 UTC
**Imported issue:**
- Author: aznm1k...@gmail.com (Google user)
- Date: 2010-04-18 00:00:00
- Legacy ID: 444

Hi,  

I'm using and OSX 32-bit compiled client with the default 64-bit server on  
Windows 7.  Everything's working fine and dandy except pressing Command+L  
while focused in OSX makes Windows 7 lock the screen.  Is there anyway I can  
solve this without changing the key bindings while on my OSX screen?  

Thanks!

**Comment by dhulihan** [comment] 2015-04-06 19:21
I'm still experiencing this in 1.6.3 (Win7 x86_64 Server, Mac OS 10.10.2 Client). :crying_cat_face:

**Comment by bluevulpine** [comment] 2015-08-09 20:55
Experiencing this using 1.7.3, Windows 10 Pro server, Mac OS 10.10.4 client. Hard to use 'open location' CMD+L in Safari, Firefox, Chrome...

**Comment by hurt-** [comment] 2015-11-16 18:55
Please fix this issue, I am experiencing the same thing since I switched windows and alt in the Synergy configuration. This is default on my hackintosh installation but results in locking the windows machine everytime I try to write '@'.

**Comment by ergelo** [comment] 2016-03-08 21:39
I'm also still experiencing this issue, but it seem to be a low-level system key binding, that can't be easily intercepted. Has anybody found a decent workaround?

**Comment by webavant** [comment] 2017-04-10 03:13
The problem solves for me when I add a third modifier key, e.g. `keystroke(control+super+l)` instead of `keystroke(super+l)`.

**Comment by XinyuHou** [comment] 2017-04-21 12:46
Duplicate of #3084

**Closed by XinyuHou** 2017-04-21 12:46 UTC
Labels: bug

**Comment by gbirchmeier** [comment] 2017-06-27 14:43
This is NOT a dupe of #3084.

3084 wants Command+L to lock EVERYTHING.  That's like the opposite of this issue, which DOESN'T want it to lock.

It should be reopened.
