### ISSUE TITLE
Mouse Lagging on Windows Client

### ISSUE THREAD

**Issue by Montigny34** [symless/synergy#5860] opened 2017-02-23 17:51 UTC
### Operating Systems ###

**Server: Mac OS Sierra 10.12.3
Client: Windows 10. Version 1607 (OS Build 14393.693)**

### Synergy Version ###

1.8.7

**READ ME, DELETE ME**: Go to the 'Help' (on Windows) or 'Synergy' (on macOS) menu and then 'About Synergy' to check your version. Verify that you are using the same version across all of your machines, and that your issue still occurs with the latest release available at https://symless.com/account/login

### Steps to reproduce bug ###

1. When moving the mouse on my windows client the mouse lags and it slow / jumps places all the time. My Mac which is the server and has the mouse plugged into it is fine. This issue didn't occur when I first used Synergy. I didn't change anything besides have Synergy automatically start on boot for both machines. Tried re-installing and this didn't fix anything.

**Comment by XinyuHou** [comment] 2017-03-01 12:07
@Montigny34 

Is you Mac using wireless connection?

**Comment by Montigny34** [comment] 2017-03-01 14:33
Yes both clients are wireless.

**Comment by XinyuHou** [comment] 2017-03-01 17:18
Duplicate of #4132 
Please have a look at this work around
https://github.com/symless/synergy/issues/4132#issuecomment-249556234

**Closed by XinyuHou** 2017-03-01 17:18 UTC
