### ISSUE TITLE
Move from server to client switches keyboard layout

### ISSUE THREAD

**Issue by Katulus** [symless/synergy#4404] opened 2015-03-05 12:35 UTC
I have Windows 8.1 client and server and I have two keyboard layouts on server - US and Czech. When I move mouse from server to client AND I have Windows command window (cmd) focused, keyboard layout is automatically switched. This happens only when server has focus in console window.
Examples:
- server layout US, focus in cmd -> move to client -> server layout switched to CZ, client layout stays
- server layout US, focus NOT in cmd -> move to client -> server layout stays US, client layout stays
- server layout CZ, focus in cmd -> move to client -> server layout switched to US, client layout stays
- server layout CZ, focus NOT in cmd -> move to client -> server layout stays CZ, client layout stays

I uploaded debug log with 2 such switches here: http://pastebin.com/QSa1VWP8

**Comment by XinyuHou** [comment] 2017-04-21 15:32
Duplicate of #5395

**Closed by XinyuHou** 2017-04-21 15:32 UTC
Labels: bug

**Comment by Katulus** [comment] 2017-04-21 18:38
@XinyuHou : This is not a duplicate of #5395. 
#5395 is about not respecting layout switch when focus is on client.
This issue is about incorrectly switching layout when moving from server to client with focused command prompt window. Check the 4 bullet points in original description. Simply moving mouse from server to client switches layout back and forth without any intention,
