### ISSUE TITLE
Angled movement gets artifically constrained

### ISSUE THREAD

**Issue by smurfless1** [symless/synergy#5929] opened 2017-03-27 16:40 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.3
Client: macOS Sierra 10.12.3

### Synergy Version ###

1.8.7-stable-9799e96 (server/client)

### Steps to reproduce bug ###

1. Move mouse slowly or, uh, "average-ly", in a line about 15 degrees from a horizontal line in any of these directions:
left + up (or down), 
right + up (or down)

On the server, this motion moves at the anticipated ~15 degree line. On the client, the same movement moves perfectly horizontal with the occasional up or down pixel in the correct direction. It seems like something eats most of the vertical movement in translation. 

Slower movement or faster movement minimizes the effect, and a really vigorous mouse shake will just look normal, but more typical movements seem to get consolidated into "mostly straight up/down" or "mostly straight left/right" unless forced.

### Other info ###

* There seems to be no trigger except that I noticed it after Sierra was installed. This doesn't mean much. 
* There seems to be no workaround
* This was tried with either system as server, over wired and wifi, to no effect.

**Comment by XinyuHou** [comment] 2017-03-30 11:59
Duplicate of #5648

**Closed by XinyuHou** 2017-03-30 11:59 UTC
