### ISSUE TITLE
Mouse click routinely lost

### ISSUE THREAD

**Issue by NeilujT** [symless/synergy#5979] opened 2017-04-06 13:28 UTC
### Operating Systems ###

Server: Windows 10 version 1607
Client: Windows 10 version 1607

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

I would love to be able to reproduce the bug consitently, but at the moment I have not find the determining trigger element. Therefore it is simply quite hard to reproduce.

Occurences
------------
It has happened on multiple occasions after two type of events mostly:
1 - When browsing a website that contains video (I though for sometimes that it was linked to adobe Flash and while I woulnd't rule out the possibility, I am not entirely convinced that this is the case now due to flash being progressively abandonned, as well as not being able to consistently reproduce the error with Flash video for example.)
2 - Upon waking up and login or simply unlocking the server

Symptomes
------------
When the bug occurs, mouse click (right or left) are not working / being sent to the client.
Mouse movements, and keyboard are fully responsives. Only the click events to not work.

### Other info ###

* A workaround is to restart the synergy service on the client
* The problem started to occurs few version back. but I wouldn't be able to say which one for sure
* While this bug does not prevent to use Synergy, it makes it severly less usefull when it happens up to 20 times per day.

I managed to isolate part of the logs when the error occured (in this case after a locking / unlocking of the server)

Server log:
https://gist.github.com/NeilujT/d3dc949631e23a015378ef893afa4ddc

Client log:
https://gist.github.com/NeilujT/ea8ac3b6e870b64d057eb9a358dda2b5

**Comment by NeilujT** [comment] 2017-04-06 13:36
I'll add #5964 and #5925 to the list as they seem related in behavior. 
Although 1Password cannot be the culprit in the present scenario

Hope this helps.

**Comment by figuerres** [comment] 2017-04-12 12:54
i think this is part of the same bug i created [https://github.com/symless/synergy/issues/5976](url)

**Comment by XinyuHou** [comment] 2017-04-12 16:23
Duplicate of issue  #5976

**Closed by XinyuHou** 2017-04-12 16:23 UTC
