### ISSUE TITLE
Hotkeys: left/right CTRL,ALT,SHIFT | Numblock VS normal numbers | FORWARDING

### ISSUE THREAD

**Issue by homezonebenny** [symless/synergy#6018] opened 2017-04-26 00:44 UTC
**TO FIX LIST**
- Enable Numblock usage. There's a difference between 1 and numblock 1 same for - and numblock - and so on
- There's a difference between the "left" and the "right" CTRL and ALT and SHIFT aswell !!!
- Hotkey forwarding. Means press the hotkey on Server, and forward it to Client
- One hotkey to jump from one PC to the other, back and forth. In my example from Server to Client, Client to Server
- Windows key isn't working to set as a modifier for hotkeys ?!

Detailed informations below.

**Newest Stable Version:**
1.8.8

**See screenshot:**
http://i.imgur.com/BswHlYx.png

**And this:**
https://pastebin.com/raw/KK8YPXbz

# What I figured out
Synergy is **not** working with Numblock at all.
That means when I set a hotkey with:
CTRL + ALT + (numblock) 1
it only works when I press:
CTRL + ALT + 1 (without numblock)

**The next thing I don't understand is this:**
http://i.imgur.com/U6OSOZE.png
For me it sounds like, press this hotkey (above in that window) on both listed PCs.
So when I press
CTRL + ALT + (num) 0
in that example it would (should) be pressed on both PCs.
Cosmo and Cosmo2 ?!?!?!
But somehow it's only pressed on Cosmo2 (Client).
Not on Cosmo (Server).

## What I try
I just simply try to "forward" a hotkey from Server to client WITH numblock.

**That means when I press:**
CTRL + ALT + (num) 0
CTRL + ALT + (num) 1
...
CTRL + ALT + (num) 9
it will be pressed on the Server PC and on the Client PC aswell.
Like just a simply forwarding of the pressed 3 keys (hotkey).
So it's possible to press a hotkey on the Server PC and it will be "pressed" (emulated / simulated) on the Client PC aswell. So I can simply control a program running on the Client PC.
Like Play / Pause / Skip on the Windows Media Player for example.

**At the moment I just want a hotkey forwarding from:**
CTRL + ALT + ANY numblock key
from Server to Client. While it's being pressed on the Server AND on the Client.
Sometimes you use that hotkey for a programm on the Server PC aswell so.
It should be pressed on Server AND on Client at the same time.
Or better said on Server first and -> forwarded to Client if you understand.

And I tried to get ONE hotkey to switch back and forth from server to client, to server, to client.
At the moment I use:
CTRL + ALT + 1 (NO numblock 1...) = Server
CTRL + ALT + 2 (NO numblock 2...) = Client
I just wish to use one single hotkey. To jump from Server to Client, from Client to Server.
Sadly, _Windows Key_ isn't working for hotkeys aswell.

**Comment by XinyuHou** [comment] 2017-04-28 15:42
Duplicate of #5868

**Closed by XinyuHou** 2017-04-28 15:42 UTC
