### ISSUE TITLE
Server process randomly dies when transferring control to client

### ISSUE THREAD

**Issue by mnjul** [symless/synergy#5613] opened 2016-09-23 19:13 UTC
### Operating Systems ###

Client: macOS Sierra 10.12

Server: macOS Sierra 10.12

### Synergy Version ###

1.8.3-rc2-89c9c58, verified to be used on both of the systems

### Steps to reproduce bug ###

(see logs at the end of this issue report)
Note: This can only be intermittently reproduced. Most of the time I get #5612, but sometimes I get this.

1. Try to move the mouse cursor from server to client.
2. The client doesn't receive the control at all, after around a few seconds. (i.e. unlike #5612) 
  * During this time, neither server nor client may be controlled using server's keyboard/mouse.
3. Client says server is dead, and server is not responding during attempts to reconnect
4. Server says process has exited and is restarting.
5. Needs to wait until server process has re-started/re-initialized, and client process has re-connected to the server, when everything is good again.

### Other info ###

* Server is a Mac Mini Late-2012 and Client is a MacBook Air Early-2014. Both are on Ethernet under the same LAN (and within the same router) --- MBA using Thunderbolt-to-Ethernet adapter. No other observable network issues.
* When did the problem start to occur? I upgraded to Sierra just like yesterday when I also installed Synergy 1.8.3-rc2 from the beta tester's mail and it happened, so I'm not actually sure who's at the culprit.
* Is there a way to work around it? No.
* Does this bug prevent you from using Synergy entirely? Yes --- I can bear with one-second lags like #5612, honestly, but all the process restarting/reinitializing/reconnecting takes quite some time and, well, it kills my productivity more than it kills me.

### Logs ###

Note: time is synchronized between server & client.

Server:
```
[2016-09-23T14:56:38] INFO: screen "purinimi.local" grabbed clipboard 0 from "purinimi.local"
[2016-09-23T14:56:38] INFO: screen "purinimi.local" grabbed clipboard 1 from "purinimi.local"
[2016-09-23T14:56:40] INFO: switch from "purinimi.local" to "purin-KeimikanTsri.local" at 0,554
[2016-09-23T14:56:40] INFO: leaving screen
[2016-09-23T14:56:40] WARNING: cursor may not be visible
[2016-09-23T14:56:40] INFO: screen "purinimi.local" updated clipboard 0
[2016-09-23T14:56:40] INFO: screen "purinimi.local" updated clipboard 1
[2016-09-23T14:56:41] INFO: switch from "purin-KeimikanTsri.local" to "purinimi.local" at 2558,735
[2016-09-23T14:56:41] INFO: entering screen
[2016-09-23T14:56:41] INFO: screen "purinimi.local" grabbed clipboard 0 from "purinimi.local"
[2016-09-23T14:56:41] INFO: screen "purinimi.local" grabbed clipboard 1 from "purinimi.local"
[2016-09-23T14:56:41] WARNING: cursor may not be visible
[2016-09-23T14:56:41] INFO: switch from "purinimi.local" to "purin-KeimikanTsri.local" at 0,384
[2016-09-23T14:56:41] INFO: leaving screen # this is '1' is in STR
[2016-09-23T14:57:01] INFO: process exited normally
[2016-09-23T14:57:01] INFO: detected process not running, auto restarting
[2016-09-23T14:57:06] INFO: starting server
[2016-09-23T14:57:06] INFO: config file: /var/folders/74/f56tx_g50ll9hpylxq17884c0000gn/T/Synergy.Nb1060
[2016-09-23T14:57:06] INFO: log level: INFO
[2016-09-23T14:57:06] INFO: drag and drop enabled
[2016-09-23T14:57:06] NOTE: started server, waiting for clients
2016-09-23 14:57:06.934 synergys[10599:826633] starting cocoa loop
[2016-09-23T14:57:07] NOTE: accepted client connection
[2016-09-23T14:57:07] NOTE: client "purin-KeimikanTsri.local" has connected
```

Client:
```
[2016-09-23T14:56:40] INFO: entering screen
[2016-09-23T14:56:40] INFO: clipboard was updated
[2016-09-23T14:56:41] INFO: leaving screen
[2016-09-23T14:56:49] NOTE: server is dead
[2016-09-23T14:56:49] WARNING: failed to connect to server: server is not responding
[2016-09-23T14:56:50] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:01] NOTE: disconnected from server
[2016-09-23T14:57:02] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:02] WARNING: failed to connect to server: Connection refused
[2016-09-23T14:57:03] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:03] WARNING: failed to connect to server: Connection refused
[2016-09-23T14:57:04] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:04] WARNING: failed to connect to server: Connection refused
[2016-09-23T14:57:05] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:05] WARNING: failed to connect to server: Connection refused
[2016-09-23T14:57:06] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:06] WARNING: failed to connect to server: Connection refused
[2016-09-23T14:57:07] NOTE: connecting to '192.168.236.241': 192.168.236.241:24800
[2016-09-23T14:57:07] WARNING: cursor may not be visible
[2016-09-23T14:57:07] NOTE: connected to server
```

**Comment by grigorovich** [comment] 2016-09-24 01:27
Try to switch off "Enable clipboard sharing". If to do that problem will gone for me.
Its a huge bug in clipboard. @mnjul , please mark this as bug.
That problem log:
.........
[2016-09-24T08:14:24] WARNING: cursor may not be visible
< HERE IS LAG - synergy server thinking and then exiting below... >
[2016-09-24T08:14:24] INFO: screen "mbargo" updated clipboard 0
[2016-09-24T08:14:24] INFO: screen "mbargo" updated clipboard 1
[2016-09-24T08:14:24] INFO: switch from "mediaplayer" to "mbargo" at 652,8
[2016-09-24T08:14:24] INFO: entering screen
[2016-09-24T08:14:25] INFO: screen "mbargo" grabbed clipboard 0 from "mbargo"
[2016-09-24T08:14:25] INFO: screen "mbargo" grabbed clipboard 1 from "mbargo"
[2016-09-24T08:14:39] INFO: stopping synergy desktop process
[2016-09-24T08:14:39] INFO: process exited normally
< and then after 10-20 seconds GUI application will automatically restarts synergys, but in nongui (CLI) synergys exited >

Client continue works fine at same time.

PS: 'mbargo' - server, 'mediaplayer' - client, both macOSX 10.12

**Comment by mnjul** [comment] 2016-09-24 02:24
Yep, switching off "Enable clipboard sharing" fixes both this and #5612 for me. I did some experiments and the (amount of) content inside clipboard doesn't matter, apparently --- even I just copied three characters from SublimeText, it would still lag/hang.

However, I do believe this is related to macOS Sierra's Universal Clipboard feature: if I turn off Bluetooth of both Macs (and of my iPhone/iPad lying nearby) I don't get the lagging / server death at all, even if "Enable clipboard sharing" is on. (it appears that Universal Clipboard between Macs can be shared over ethernet, though, since I already have Wi-Fi off on both Macs).

**Comment by mnjul** [comment] 2016-09-24 02:25
> @mnjul , please mark this as bug.
I can't add labels to issues here, so probably need to wait for some other official guys.

**Comment by nlyan** [comment] 2016-09-26 09:49
The "enable clipboard sharing" checkbox was added in 1.8.3 in anticipation of problems with Sierras clipboard sync functionality. ( Many thanks to https://github.com/symless/synergy/issues/123#issuecomment-247070199 ).

We're currently assessing all the problems with Sierra and this is a priority for 1.8.4

**Comment by nlyan** [comment] 2016-10-10 14:30
Duplicate of #5531

**Closed by nlyan** 2016-10-10 14:30 UTC
Labels: bug

**Comment by decriptor** [comment] 2017-02-09 20:48
This has been working fine for me until the latest mac update from a few days ago. I'm guessing that Apple changed something here causing this to break?

macOS Sierra
Version 10.12.3 (Both server and client)

**Comment by brainsnorkel** [comment] 2017-03-16 00:04
I'm getting the same problem with 1.8.8-stable on two MBPs with both running Sierra 10.12.3 even with clipboard sharing disabled.

```
[2017-03-16T11:03:03] INFO: switch from "MacBook-Pro" to "vpn-elided.harvard.edu" at 2545,1138
[2017-03-16T11:03:03] INFO: entering screen
[2017-03-16T11:03:03] NOTE: client "MacBook-Pro" has disconnected
[2017-03-16T11:03:03] INFO: process exited normally
[2017-03-16T11:03:03] INFO: detected process not running, auto restarting
[2017-03-16T11:03:04] INFO: starting server
[2017-03-16T11:03:04] INFO: config file: /var/folders/pb/92nt2cb11x30hd959921vd540000gn/T/Synergy.hue502
[2017-03-16T11:03:04] INFO: log level: INFO
[2017-03-16T11:03:04] INFO: drag and drop enabled
[2017-03-16T11:03:04] NOTE: clipboard sharing is disabled
[2017-03-16T11:03:04] NOTE: started server, waiting for clients
2017-03-16 11:03:04.762 synergys[22360:137175] starting cocoa loop
[2017-03-16T11:03:19] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-03-16T11:03:19] INFO: accepted secure socket
[2017-03-16T11:03:19] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2017-03-16T11:03:19] NOTE: accepted client connection
[2017-03-16T11:03:19] NOTE: client "MacBook-Pro" has connected
```

**Comment by kshenk1** [comment] 2021-07-02 12:47
FWIW, I'm running version 1.14 (build 6/8/2021): OSX 11.4 intel server with win10 pro client. My setup was working fine until this morning, when this became the pattern:
```
[2021-07-02T08:38:15] WARNING: cursor may not be visible
[2021-07-02T08:38:20] NOTE: client "win10pro" is dead
[2021-07-02T08:38:20] INFO: jump from "win10pro" to "osx11" at 960,540
[2021-07-02T08:38:20] INFO: entering screen
[2021-07-02T08:38:21] NOTE: accepted client connection
[2021-07-02T08:38:21] NOTE: client "win10pro" has connected
[2021-07-02T08:38:23] INFO: switch from "osx11" to "win10pro" at 0,404
[2021-07-02T08:38:23] INFO: leaving screen
[2021-07-02T08:38:23] WARNING: cursor may not be visible
[2021-07-02T08:38:32] NOTE: client "win10pro" is dead
```
Perplexed by this after reviewing my configuration and doing some lite troubleshooting on my LAN... I found this tread. AND INDEED - I **un**checked the "enable clipboard" option and the lights immediately came back on.

Thank you @grigorovich !
