### ISSUE TITLE
Synergy Client crashes when running multiple clients on one Windows machine

### ISSUE THREAD

**Issue by synergyuser** [symless/synergy#6027] opened 2017-05-03 18:12 UTC
### Operating Systems ###

Server: CentOS 7 (7.2)
Client: Windows 7 (service pack 1)

### Synergy Version ###

1.8.*

### Steps to reproduce bug ###

Originally discovered in 1.8.2, but this problem also exists with 1.8.8.

Configuration involves having two CentOS 7 machines each with one Synergy server running, which connect to a third machine with Windows 7 which run two instances of Synergy clients running (run through the command line).  Idea is the two people on the CentOS machines can use the Windows 7 machine.

Whenever the Synergy servers are brought down or come back up, the Synergy clients crash (not usually at the same time, but if one crashes the other is a guaranteed crash, crash doesn't occur in any particular order).  Whenever the crash happens, logs on the clients indicate the last thing done was usually clipboard related operations (no pattern as to which operation, last thing logged was any of open, close, empty clipboard).  Even on the highest level of debug logging, nothing of interest was logged to post here.

Installed 1.8.8 in order to leverage the addition of clipboard disabling, but disabling the clipboard sharing through configuration files did not resolve this.

Created some debug executables and it was noticed that there was an uncaught access violation on line 1064 in MSWindowsScreen::onEvent.

As a quick solution we ended up setting m_nextClipboardWindow to NULL in MSWindowsScreen::enable, and building a set of executables based on that.

### Other info ###

* Is there a way to work around it? Yes, but need to plug in a keyboard/mouse into the Windows machine in order to relaunch the clients.
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by XinyuHou** [comment] 2017-05-08 10:38
Duplicate of #4705

**Closed by XinyuHou** 2017-05-08 10:38 UTC
