### ISSUE TITLE
Mouse Disappears/Crashes when moving onto and using client.

### ISSUE THREAD

**Issue by Verequies** [symless/synergy#5783] opened 2016-12-28 11:38 UTC
Server: Debian Unstable (Xanmod Kernel 4.9.0-3 64-bit)
Client: Windows 10 November Update (64-bit) (1511)
Synergy Version: 1.8.6-stable
Desktop Environment: MATE

Whenever I'm using Synergy, there is a random chance that if I move my mouse to the client and or use my mouse within the client, the mouse crashes and disappears requiring me to restart my display manager. This has been an ongoing past few months and I have tested many Synergy nightlies hoping that one has included a fix. There is no way that I know of to work around this issue, however it does not stop me from using Synergy. 

I have attached a log  with level DEBUG2 from the last time it crashed on the host side.

[synergy.1.txt](https://github.com/symless/synergy/files/675497/synergy.1.txt)
[synergy.txt](https://github.com/symless/synergy/files/675498/synergy.txt)

**Comment by XinyuHou** [comment] 2016-12-30 15:38
Please try to disable clipboard sharing to see if that changes anything. Thanks.

**Comment by Verequies** [comment] 2017-01-03 09:16
I tried disabling clipboard sharing as you suggested however it still crashed. I attached the lastest logs.
[synergy.1.txt](https://github.com/symless/synergy/files/681928/synergy.1.txt)
[synergy.txt](https://github.com/symless/synergy/files/681929/synergy.txt)

**Comment by Verequies** [comment] 2017-01-03 09:19
While testing I've found a bug, I didn't realise it at the time, but if you disable Clipboard Sharing then restart Synergy, its automatically turned on. So I have to do some more testing.

**Comment by Verequies** [comment] 2017-01-03 11:51
Okay still happens after making a custom config disabling Clipboard Sharing. Latest logs attached.
[synergy.1.txt](https://github.com/symless/synergy/files/682172/synergy.1.txt)
[synergy.txt](https://github.com/symless/synergy/files/682173/synergy.txt)

**Comment by XinyuHou** [comment] 2017-02-28 14:51
Duplicate of #5643

**Closed by XinyuHou** 2017-02-28 14:51 UTC
