### ISSUE TITLE
Use "interface" preference for client also

### ISSUE THREAD

**Issue by packwidth** [symless/synergy#6060] opened 2017-06-09 14:56 UTC
### Operating Systems ###

Server: Windows 10 x64 1607
Client: macOS 10.12.5

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Set interface option in preferences of client. (eg, en0)
2. Remove cable from specified interface.
3. Synergy connects to server using another interface (eg, en1).

### Other info ###

I connect my laptop to my work network using ethernet (at my desk where I'd like to use Synergy) and wifi (when moving about the lab where I don't want to use Synergy). My laptop is the client and a desktop is the server. I'd like to restrict the Synergy client on the laptop to only connect to the server through the ethernet interface.

In the preferences, I set the interface option, but the client still connects through other interfaces. If this option is only intended for telling the server code which interface to bind to, it should also be used to restrict the interface that the client will use.

**Comment by XinyuHou** [comment] 2017-06-30 14:20
Duplicate of #4253

**Closed by XinyuHou** 2017-06-30 14:20 UTC
