### ISSUE TITLE
No screen savers

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4010] opened 2014-10-13 07:50 UTC
**Imported issue:**
- Author: Dean Taylor
- Date: 2014-06-10 20:53:02
- Legacy ID: 4080

**Steps to reproduce:**
1. Set a Windows 8.1 x64 running Synergy 1.5.0 as server.
2. Set a separate Windows 8.1 x64 running Synergy 1.5.0 as client.
3. Set server to "Synchronize screen savers" under the Advanced Server settings.
4. Wait for Screen savers to start.
5. Interrupt screen savers (move the mouse or something).
6. Screen savers will never kick back up again until the machines are rebooted.

**Versions and operating systems:**

Windows 8.1 x64 on both.
Synergy 1.5.0 on both.

**Temporary workarounds:**

None that I currently know of.

**Similar bugs:**

None that I currently know of.

**Additional comments:**

This bug also existed in previous versions of Synergy.
My server also uses Encryption.

**Comment by XinyuHou** [comment] 2017-04-21 15:00
Duplicate of #4116

**Closed by XinyuHou** 2017-04-21 15:00 UTC
Labels: bug
