### ISSUE TITLE
Mouse sharing issue

### ISSUE THREAD

**Issue by StoneMoe** [symless/synergy#5668] opened 2016-10-15 06:17 UTC
### Operating Systems ###

Client: Microsoft Windows 10 Pro (Version 1607, Build 14393.321)

Server: macOS Sierra 10.12

### Synergy Version ###

Client&Server: 1.8.4-stable-a6ff907

### Steps to reproduce bug ###

Moving cursor to left and top is faster than moving it to bottom and right

### Other info ###

Any workaround? (Use Windows as Server and Mac as Client won't reproduce this issue)
Does this bug prevent you from using Synergy entirely? (No, But confusing)

**Comment by XinyuHou** [comment] 2016-10-17 13:04
Duplicate of #5607

**Closed by XinyuHou** 2016-10-17 13:04 UTC
