### ISSUE TITLE
Conflicts with adobe creative suite

### ISSUE THREAD

**Issue by gorkacortazar** [symless/synergy#5485] opened 2016-07-20 09:50 UTC
Version: 1.8.1 beta (server)
OS: Windows 10

Some adobe applications doesnt work correctly when synergy is installed:

- Photoshop CC (2015.5): Unable to do selections (main window only), or anything related to hold the mouse. Modifier keys (Shift, Control and Alt) doesn't work.
- Illustrator CC (2105.3): Selections works errqatically (need to restart the software after a while). Modifier keys also works erratically.

It happens when synergy is installed, regardless is running or not. My workaround solution for now is fully uninstall synergy :-/

**Comment by THPubs** [comment] 2016-07-20 12:38
Same issue here!

**Comment by XinyuHou** [comment] 2016-07-21 10:45
Duplicate of #3044

**Closed by XinyuHou** 2016-07-21 10:45 UTC

**Comment by simsketch** [comment] 2016-07-24 10:24
I am having this issue in Photoshop, Illustrator, and Gmail as far as I can tell.

**Comment by simsketch** [comment] 2016-07-24 10:30
i updated to the most recent version synergy-v1.7.6-stable-bcb9da8-Windows-x64 and it appears to be working just fine. thanks!
