### ISSUE TITLE
Synergy ignores small mouse movements on a macOS Sierra server

### ISSUE THREAD

**Issue by cchrisman** [symless/synergy#5795] opened 2017-01-11 22:53 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.2
Client: Windows 10 (Build 10240)

### Synergy Version ###

1.8.6 (also occurs on 2016/1/11 nightly)

### Steps to reproduce bug ###

1. Move mouse diagonally to the left or right, and a very small amount down. The client mouse will ignore all downward movement, and move perfectly horizontally.  

2. Move the mouse diagonally up and a very small amount to the right.  The client mouse will ignore all movement to the right and move perfectly vertically.

3. When you increase movement above a certain velocity, it will finally move, but it will be obvious that it's not tracking movement correctly.

4. You can also quickly tell if this is happening by moving the mouse in small clockwise circles.  The mouse on the client screen will gradually drift up and to the left instead of the desired stationary circle.

### Other info ###

* This is pretty much a dealbreaker for me using Synergy, since you're constantly fighting against buggy movement, it also doesn't appear to be terribly difficult to reproduce.
* I first noticed this when upgrading to the latest version of OSX El Capitan (10.11.6), it also occurs on all versions of macOS Sierra that I've tried.
* I tried older builds (1.7.5) and newer builds (latest nightly) and the bug is present in all of them.
* This forum post appears to describe a similar behavior (or maybe they're just  misdiagnosing it): http://symless.com/forum/viewtopic.php?f=16&t=2114

**Comment by koopatroopa120** [comment] 2017-01-12 01:18
This issue sounds like the one documented here: https://github.com/symless/synergy/issues/5648. it sounds exactly like the link you posted at least.

**Comment by MagnumPl** [comment] 2017-01-24 00:09
I believe this is the EXACT ISSUE.  This makes using synergy so much of a pain.  I'm ready to dump it and move on to something else.  It's really frustrating that hotkey fixes are getting prioritized over this, we can live with out hotkeys, this affects just normal mouse usage.  How can we help raise the visibility of these issues?

**Comment by nlyan** [comment] 2017-02-10 00:19
Duplicate of #5648

**Closed by nlyan** 2017-02-10 00:19 UTC
