### ISSUE TITLE
Non-SSL client causes 'passive ssl error limit' error

### ISSUE THREAD

**Issue by KaptenJansson** [symless/synergy#4847] opened 2015-07-07 07:44 UTC
I noticed while I was upgrading all my clients to 1.7.3 that the server suddenly stopped accepting connections and disconnected all existing connections. This was due to turning on additional clients  running Synergy 1.6.3 which tries to automatically connect on startup. Basically it's DDOSing the server.

Could you add a mechanism preventing this from happening?

**Comment by eclipsenet** [comment] 2015-07-13 11:37
I am getting this error between a Windows server and a Linux client, both are on the same 1.7.3 Pro version. It happens when one or the other screen locks, the connection never recovers. The Linux client will die while the Windows server stays up. Only way to repair is to stop and restart the Linux client a few times until it connects again. :(

**Comment by XinyuHou** [comment] 2015-07-14 17:34
@eclipsenet 
Could you try this nightly?

http://synergy-project.org/nightly?filter=2de27

**Comment by eclipsenet** [comment] 2015-07-26 21:16
Will do, for some reason I did not see the reply :)

**Comment by XinyuHou** [comment] 2017-03-08 12:12
Duplicate of #5898

**Closed by XinyuHou** 2017-03-08 12:12 UTC
Labels: bug
