### ISSUE TITLE
Problem with letter S when i press space Mac osx <-> W10

### ISSUE THREAD

**Issue by Hilas** [symless/synergy#5468] opened 2016-07-13 17:08 UTC
When i press space on mac osx this press the letter "s" i use windows 10 and mac osx 11, the server is windows and the client is mac. . plz help me i just buy this program .

**Comment by XinyuHou** [comment] 2016-07-18 16:11
Duplicate of #2765

**Closed by XinyuHou** 2016-07-18 16:11 UTC
