### ISSUE TITLE
Mac Scroll Gestures Broken

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy#5375] opened 2016-06-13 17:58 UTC
Credit to Synergy User "Alexandre":

Synergy Version: Unknown
Server: Mac OSX
Client: Linux Debian
App: Chrome

Problem: 

Two finger scroll on Mac is broken in Chrome. Specifically, scrolling through pages is unreliable, and seems to be related to the pressure applied to the touchpad.

Solution:

Was able to resolve by adding "--yscroll 20" to the command line on the Linux side. Now scrolling is smooth.

**Comment by nlyan** [comment] 2016-06-27 11:18
I think this is a duplicate of #2905

**Closed by nlyan** 2016-06-27 11:18 UTC
