### ISSUE TITLE
External Display mouse fake edge

### ISSUE THREAD

**Issue by alexandercerutti** [symless/synergy#5742] opened 2016-11-15 14:51 UTC
### Operating Systems ###

Server: macOS Sierra
Client: Windows 10

### Synergy Version ###

1.8.5

### Steps to reproduce bug ###

There's not really steps to follow. The problem is, easily, that when I use an external HDMI monitor (as extended - my case is that the monitor has a smaller resolution than my Surface Pro 3 because older), the primary screen is "extended" in a weird way. Given the mouse on the client, I move it on the right to reach the external display: it can reach the external display until a "specific line". Once reached that line, the mouse comes back to the main display at "another specific line" and then I can move it to reach the right edge of the external monitor.
I already tried to restart Synergy and start synergy both after and before connect the external display. I also tried to log to Debug2 Level and then Debug. I attach it there.
Any fixes? Thank you.

[synergy.txt](https://github.com/symless/synergy/files/592289/synergy.txt)

**Comment by XinyuHou** [comment] 2016-12-05 15:42
Duplicate of #3744

**Closed by XinyuHou** 2016-12-05 15:42 UTC
