### ISSUE TITLE
Script build fails on OSX/qt5, but works with manual GUI build

### ISSUE THREAD

**Issue by ravenium** [symless/synergy#5994] opened 2017-04-12 23:39 UTC
### Operating Systems ###

Server: Ubuntu Linux 14.04
Client: MacOS X 10.12.4

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

Brew recently deprecated qt4 to the dust bin and qt5's keg is now qt.  Going forward it's likely that the majority of OSX users will have some version of qt5 as their primary qt install.

I'm following the build instructions for OSX - I get to the build part and it errors out with:

_Error: [Errno 2] No such file or directory: '/Developer/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Contents/Info.plist'_

I realized that I'd forgotten to change the path in commands1.py, but there's still no Info.plist in /usr/local/opt/qt/Frameworks/QtCore.framework, thus it errors out.

I went to dist mac the bundle up and installed from dmg, and found that my gui is a blank nonfunctional screen.  However, synergyc still works to connect to my Linux workstation. Clearly something went horribly wrong with qt.

But a fix!

1. cd into src/gui
2. make && qmake
3. cd back up to your synergy build folder, then bin/Synergy.app/Contents/MacOS
4. Copy Synergy into the equivalent folder in /Applications/Synergy.app/Contents/MacOS.  Do not drag and drop as it will wipe out the cli binaries.
5. Launch Synergy as usual and approve.

This definitely appears to be a gui/qt problem and does not affect the synergyc/synergys binaries themselves (I ran it via CLI for a couple days before I fiddled).  My guess is that I've probably created a dependency on my installed qt (I had to recompile it after Brew updated my qt install), so this isn't a "real" fix for making a static compile as it's skipping that step by merely make/qmaking.

### Other info ###

* When did the problem start to occur? When I compile/build from source on OSX
* Is there a way to work around it? Yes!
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment] 2017-04-21 11:28
Duplicate of #4572

**Closed by XinyuHou** 2017-04-21 11:28 UTC
