### ISSUE TITLE
Command key stuck (Mac client, Windows server)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#4057] opened 2014-10-13 07:56 UTC
**Imported issue:**
- Author: Mike Wyant
- Date: 2014-08-14 14:56:50
- Legacy ID: 4127

**Steps to reproduce:**
1. _Important:_ Provide numbered steps to reproduce the bug.
2. If you don't provide steps, your issue will be marked as invalid.
3. Replace this example text with your own (or you will look silly).
4. You should also provide: expected, actual, versions, workarounds, etc.

Expected: Daily functioning continues unabated

Actual: After several minutes to an hour of use, the remote machine will begin acting like the Command key is held down.  Sometimes using Command-Tab to switch through apps will reset this, but it's about a 50%% chance of success.

**Versions and operating systems:**

Server: Windows 7 Home Premium SP1
Client: Mac OS X 10.9.4

**Temporary workarounds:**
As mentioned, sometimes using Command-Tab will reset this functionality; otherwise I need to close down the connection (either from client or server) to get full functionality back,

**Similar bugs:**

There are some others related to modifier keys sticking, but this one is very specific and happens whether Office or Photoshop is open at all

**Additional comments:**

TODO

**Comment by 128keaton** [comment] 2015-02-17 05:04
Same problem here, (Win8.1 x64, 10.10.2) really sad :(

**Comment by cra5370** [comment] 2015-02-21 18:31
I'm experiencing this issue as well on a consistent enough basis that I've gotten used to spam pressing the command key after I use it so that it clears the stickiness (which only works half the time). Would love to see this fixed.

**Comment by adamnovak** [comment] 2015-02-23 22:54
I can reproduce this with an Ubuntu 12.04 host on Synergy 1.6.3 and an OS X Yosemite client on 1.6.2.

If I am moving the mouse when I press or release a modifier key, that modifier key does not change state. I have to hold the mouse still and tap the relevant key to reset it.

**Comment by mengesb** [comment] 2015-03-25 19:42
I have the same issue with 1.6.3 server on ubuntu and my windows 7 client only. My other ubuntu machines operate just fine, no ctrl stuck.

**Comment by ryanwillis** [comment] 2015-03-26 20:15
I have had this issue for a year, it persists through each update. Windows 7 server, mac client. I never experience this on the server, only on the client.

**Comment by indoctrine** [comment] 2015-03-28 03:29
1.6.3, Windows 7 64 bit server and Mac OSX Yosemite client. Getting the sticking on the client only, it's a real pain, especially when trying to paint. It started a few minutes after I opened the connection, I thought it was lag at first.

**Comment by ematthews** [comment] 2015-04-07 16:05
I've nearly destroyed 3 keyboards with this error. I have experienced this version with the latest stable release with both Windows & Linux synergy server and the mac system acting as a client.

**Comment by adamnovak** [comment] 2015-04-07 17:23
OK, we've established that this error exists and is replicable with a
variety of servers and a Mac client.

Which developer has the appropriate skills (and the time), or, better yet,
the responsibility, to actually track down what's wrong in the Mac client
code and fix it?

**Comment by beporter** [comment] 2015-04-07 18:49
The bug has been around for six years (read the history for #9). If this was easy to fix, the primary devs would have been able to nail it down by now. I have to believe it's going to take an extremely deep, concerted effort on someone's part to kill this bug.

**Comment by xxin** [comment] 2015-04-13 02:34
This happens a lot to me. Here is my setup:
Ubuntu 12.04 server on Synergy 1.6.3
OS X Yosemite client on 1.6.3

When I use my mac as a server, it functions well though.

**Comment by Corben78** [comment] 2015-04-16 09:12
Can confirm the sticky ctrl-key on OS X (Yosemite) client with Synergy 1.6.3 and Ubuntu 14.04 LTS as server.

In 1.6.2 when ctrl+c (copy) some text on the server (Ubuntu), and trying to insert it on the client (OS X), I have to tap ctrl twice again to release it.

In 1.6.3 I can copy from server and insert on client normally, but when copying with ctrl+c on the client (mapped super -> ctrl, ctrl -> super on OS X client for windows/linux shortcuts on OS X), the ctrl-key gets stuck again, and I have to tap it twice to release it again. Only on OS X client, on Ubuntu server the key doesn't never got stuck.

**Comment by josiahhalme** [comment] 2015-04-22 05:39
Version 1.6.2
Server: Windows 7 1.6.2
Client: OSX Yosemite 1.6.2

When holding down command and moving the mouse it becomes sticky, can resolve by tapping command again to reset it.

**Comment by jpmcmu** [comment] 2015-04-23 00:38
I created a pull request to fix this issue, but I have only been able to test it on my setup. If anyone can test the following code branch on their setup and report back on the pull request, I would appreciate it.

Code Branch: https://github.com/jpmcmu/synergy/tree/MacOSX-Sticky-Key-Fix
Pull Request: https://github.com/synergy/synergy/pull/4564

**Comment by hidden72** [comment] 2015-04-23 18:35
Happy to test, but not the compiling-sort.  Let me know if there's a way to get hands-on the Win7x64 and OSX 10.10 binaries and I'd love to put it through the paces.  Thanks!

**Comment by raphael** [comment] 2015-04-23 19:51
Been testing it for the whole morning and so far no stuck keys! liberating... (Win7x64 server and OSX 10.10 client). Been using the 7.1 synergy release for the server and compiled the Mac client.
@hidden72 this is what I followed to compile the client:
http://stackoverflow.com/questions/26923227/how-to-compile-synergy-on-mac
+
https://github.com/synergy/synergy/issues/4442#issuecomment-92191685

**Comment by beporter** [comment] 2015-04-24 13:36
Signal boosting: There is [a new nightly build available](https://github.com/synergy/synergy/pull/4564#issuecomment-95926896) that may fix this issue (and is installable without having to compile from source). If anyone monitoring this thread is able to test it, it would be appreciated.

**Comment by hidden72** [comment] 2015-04-24 16:08
beporter:  Thanks for the link... I was banging my head trying to figure out how to compile...  

I upgraded to the test nightly build about 30 minutes ago and so far not a single stuck command key.  Will continue testing, but I'm extremely hopeful!

**Comment by hidden72** [comment] 2015-04-24 19:33
Been using it all day and not a single stuck key.  This is awesome!!!

**Comment by jpmcmu** [comment] 2015-04-25 17:34
@raphael, @hidden72 and @beporter thanks for testing and getting the word out. I am glad to hear that the fix has been working for you guys. I thought it would fix the issue for Mac clients regardless of the system setup but it is good to get confirmation.

**Comment by roaet** [comment] 2015-05-01 15:53
I can confirm after 3 days of working that it hasn't been a problem. Once CTRL was stuck but I haven't been able to recreate that.

**Comment by zorrobyte** [comment] 2015-05-02 12:56
Same issue as of 1.7.1 https://github.com/synergy/synergy/issues/4604

**Comment by sngz** [comment] 2015-05-05 22:15
thanks for fixing this issue @jpmcmu working perfectly

**Comment by DominikDeak** [comment] 2015-06-02 10:03
Experiencing the same sticky problems with the CTRL key. This also happens to ALT, but not as often. Running a server 1.6.3 on Windows 7 x64, and Yosemite client. the config file:

```
section: screens
   OSX:
      ctrl = super
      alt = ctrl
      super = alt
      halfDuplexCapsLock = false
      halfDuplexNumLock = false
      halfDuplexScrollLock = false
      xtestIsXineramaUnaware = false
      switchCorners = none
      switchCornerSize = 0
   WINDOWS:
      halfDuplexCapsLock = false
      halfDuplexNumLock = false
      halfDuplexScrollLock = false
      xtestIsXineramaUnaware = false
      switchCorners = none +top-right +bottom-right
      switchCornerSize = 0
end

section: aliases
end

section: links
   OSX:
      right = WINDOWS
   WINDOWS:
      left = OSX
end

section: options
   heartbeat = 1000
   relativeMouseMoves = false
   screenSaverSync = true
   win32KeepForeground = false
   switchCorners = none
   switchCornerSize = 0
   switchNeedsAlt = true
   switchNeedsControl = true
end

```
Interestingly, if I run the On-Screen Keyboard utility on Windows (under Accessories -> Ease of Access) the sticky key problem happens less frequently. The idea was to use On-Screen Keyboard to check if the sticky key is persistent on Windows as well.

**Comment by jpmcmu** [comment] 2015-06-02 11:15
@DominikDeak Is it sticking on the Mac OSX side or the Windows side? If it is the Mac OSX side try modifying your key mapping configuration to work like the following. I had found a bug where the CTRL key would stick due to odd/misconfigured key mappings. Yours seems to be correct, but it is worth a shot. 
```
ctrl = super
super = ctrl
```

**Comment by DominikDeak** [comment] 2015-06-03 03:47
> Is it sticking on the Mac OSX side or the Windows side?

For version 1.6.3, it is sticking on the OSX side. 

Interestingly, when I used Synergy 1.3.x some time ago, using the same client/server machines and config, I had sticky ALT keys on the windows machine only (i.e. the server). Now the situation seems to be reversed.

I do a lot of copying and pasting text in xcode and that is when I notice the sticky CTRL the most. 

> try modifying your key mapping configuration to work like the following

Gave it a shot, but the problem persists.

**Comment by XinyuHou** [comment] 2016-12-05 15:06
Fix has been merged.

**Closed by XinyuHou** 2016-12-05 15:06 UTC
Labels: bug, priority-2-next

**Comment by skimania** [comment] 2017-07-14 18:12
What version was this fixed in?
