### ISSUE TITLE
Mac client doesn't send special keys(like shift, control, meta, ..) to Parallels Desktop.

### ISSUE THREAD

**Issue by hgijeon** [symless/synergy#5799] opened 2017-01-16 04:49 UTC
### Operating Systems ###

Server: Ubuntu Desktop 16.04
Client: macOS Sierra 10.12.2

### Synergy Version ###

1.8.6

I installed Parallels Desktop 12 on my macOS(client position of Synergy), and running Windows 10 as a virtual machine on the Parallels. When I'm using Ubuntu 16.04 as Synergy server, activate VM Windows program(like notepad.exe), and type key combination, even 'Shift + a' to type a capital letter 'A', shift key doesn't seem working.

Which means, I cannot type uppercase letters, copy, paste, and close program with Alt+F4, when I using programs in Windows VM with MacOS client + Ubuntu server.

Is that caused by a difference between "postEventToQueue" and "CGEventPost"? or problem of Sierra?
Inside of OSXEventQueueBuffer::addEvent() on OSXEventQueueBuffer.cpp, it seems Synergy is using postEventToQueue(), but I found this page
http://stackoverflow.com/questions/17512500/whats-the-right-replacement-for-postevent
, which says PostEventToQueue is not for a low-level OS event.

I really wish to type capital letters on my Windows VM.
Thanks!

**Comment by XinyuHou** [comment] 2017-02-28 17:21
Duplicate of ##3083

**Closed by XinyuHou** 2017-02-28 17:21 UTC

**Comment by RyanDrx** [comment] 2018-07-24 23:00
#3083
