### ISSUE TITLE
Mouse and Keybroad stuck on Client (Enterprice/Domain Enviroment)

### ISSUE THREAD

**Issue by sweetrush** [symless/synergy#5514] opened 2016-07-30 07:46 UTC
Mouse and Keyboard are locked at the client when the server is on windows lock screen / Login screen when using synergy on a domain computer or Enterprise Desktop.

**Comment by XinyuHou** [comment] 2016-08-02 16:46
Duplicate of #5294

**Closed by XinyuHou** 2016-08-02 16:46 UTC
