### ISSUE TITLE
Cursor Invisible on Ubuntu host when it has no mouse input directly connected

### ISSUE THREAD

**Issue by axlan** [symless/synergy#6063] opened 2017-06-09 20:49 UTC
### Operating Systems ###

Server: Ubuntu 17.04
Client: Windows 10 Pro Version 1703

### Synergy Version ###

1.9.0-rc3-f987381

### Steps to reproduce bug ###

If Ubuntu starts up without any mouse input connect the pointer from synergy will be invisible. Attaching a mouse makes the cursor visible.

**Comment by LuoYuWuSheng** [comment] 2017-06-11 01:30
I got this problem too, Any one can fix this one ?

**Comment by LuoYuWuSheng** [comment] 2017-06-13 00:55
**gsettings set org.gnome.settings-daemon.plugins.cursor active false**
This command helped me .
Some one had already commit this bug.You can have a look

[Ubuntu's bug report](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1243078)
[The same problem link of synergy](https://github.com/symless/synergy/issues/4289)

**Comment by axlan** [comment] 2017-06-13 17:43
While this fixes the behavior after login, I'm also using synergy at boot to enter the credentials. There's probably a way to make a similar setting change that affects that as well.

**Comment by LuoYuWuSheng** [comment] 2017-06-16 03:22
Do you mean the login page to enter your password? If yes, you can try this guide [SynergyHowto](https://help.ubuntu.com/community/SynergyHowto),For me, The LightDM works according to that guide.

**Comment by nlyan** [comment] 2017-06-30 14:56
Duplicate of #4289

**Closed by nlyan** 2017-06-30 14:56 UTC
