### ISSUE TITLE
Can't type exclamation point on Windows client

### ISSUE THREAD

**Issue by mherger** [symless/synergy#5851] opened 2017-02-17 09:43 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.3
Client: Windows 7 (6.1, build 7601, SP1)
Client 2. macOS El Cap 10.11.6

### Synergy Version ###

1.8.7 stable (both Server and Client)

### Steps to reproduce bug ###

I'm using the Swiss German keyboard on all machines. In the upper row, right hand side, there are the keys (from left to right) "uiopü¨". That last character is a dead key. With shift, this should be "UIOPè!" (the U umlaut becomes the accented E - that's correct, as we have German as the primary language, and French/Italian secondary).

When I'm controlling the Windows client, the "!" would not type, no character at all would show up on the client. The dead "¨" OTOH would. But when pressed followed by u (to make the ü umlaut), it would become the accented è. No matter what modifier key I'm using, I can't get the exclamation mark on the Windows client.

Controlling the other Mac I don't see this issue.

Unfortunately I'm not sure when this started, as I moved from 1.6.x to 1.8.x. It certainly was not there in 1.6, but has been in 1.8.x for a few minor versions now.

My only workaround for now is to move my hand over to the controlled Windows laptop's keyboard :-)

**Comment by XinyuHou** [comment] 2017-03-01 11:42
Duplicate of #4280

**Closed by XinyuHou** 2017-03-01 11:42 UTC
