### ISSUE TITLE
Synergy Server 1.8.3 segfaults on Ubuntu

### ISSUE THREAD

**Issue by Carles-Figuerola** [symless/synergy#5621] opened 2016-09-26 15:20 UTC
### Operating Systems ###

Client: Windows 7

Server: Ubuntu 16.04

### Synergy Version ###

1.8.3-stable-db9181b

### Steps to reproduce bug ###

Synergy segfaults when accepting client connection:

```
$ /usr/bin/synergys -f --no-tray --debug DEBUG --name cfiguerola --enable-crypto --log /home/cfiguerola/log/synergy.lo
g -c /home/cfiguerola/.synergy.conf --address :24800                                                                                                   
[2016-09-26T10:11:30] DEBUG: opening configuration "/home/cfiguerola/.synergy.conf"
[2016-09-26T10:11:30] DEBUG: configuration read successfully
[2016-09-26T10:11:30] DEBUG: plugins dir: /home/cfiguerola/.synergy/plugins
[2016-09-26T10:11:30] DEBUG: loading plugin: libns.so
[2016-09-26T10:11:30] DEBUG: plugin loaded: libns.so (version 1.3)
[2016-09-26T10:11:30] DEBUG: XOpenDisplay(":1")
[2016-09-26T10:11:30] DEBUG: xscreensaver window: 0x00000000
[2016-09-26T10:11:30] DEBUG: screen shape: 0,0 2680x1920 (xinerama)
[2016-09-26T10:11:30] DEBUG: window is 0x03000004
[2016-09-26T10:11:30] DEBUG: adopting new buffer
[2016-09-26T10:11:30] DEBUG: opened display
[2016-09-26T10:11:30] DEBUG: registered hotkey ScrollLock (id=ef14 mask=0000) as id=1
[2016-09-26T10:11:30] NOTE: started server, waiting for clients
[2016-09-26T10:11:30] DEBUG: event queue is ready
[2016-09-26T10:11:30] DEBUG: add pending events to buffer
[2016-09-26T10:11:30] DEBUG: screen "cfiguerola" shape changed
Segmentation fault (core dumped)
$ 
```
Further debug levels don't show any more useful information than this. The segfaults are immediately following a client try to connect.

### Other info ###

Rolling back to v1.8.2-stable-36cd521 on both client and server fixes the problem (ssl seems to be incompatible across versions)

**Comment by raidoz** [comment] 2016-09-26 15:49
Same thing happens to me on LUbuntu 16.04 server with a Windows 10 client.

**Comment by jtbraun** [comment] 2016-09-26 15:56
Re-running the config wizard (File->Run Wizard) downloaded new SSL plugin binaries on both client and server.  Fixed it for me.

**Comment by Carles-Figuerola** [comment] 2016-09-26 16:06
Updated the server again, run the wizard and it's now using a new plugin (mine was manually downloaded before as the wizard was failing):
```
~/.synergy/plugins$ ls -ltrh
total 0
lrwxrwxrwx 1 cfiguerola cfiguerola 40 Sep 26 10:59 libns.so -> /usr/bin/../lib/synergy/plugins/libns.so
```
Server 1.8.3 with client 1.8.2 worked properly but upon updating the client I'm getting this error:
```
[2016-09-26T11:03:44] ERROR: ssl error occurred (system call failure)
[2016-09-26T11:03:44] ERROR: eof violates ssl protocol
[2016-09-26T11:03:44] ERROR: failed to accept secure socket
[2016-09-26T11:03:44] INFO: client connection may not be secure
[2016-09-26T11:03:45] INFO: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by nlyan** [comment] 2016-09-26 16:10
@Carles-Figuerola Did you rerun the wizard on the client-side too?

**Comment by jonathankonrad** [comment] 2016-09-26 16:13
I re-ran the wizard on both my Server - Ubuntu 15.10 and Client - Windows 8.1 And they can no longer create a secure connection. Turning off SSL of course works, so that is what I will need to do today. Tough, since 1.8.2 was working perfectly this morning.

**Comment by jonathankonrad** [comment] 2016-09-26 18:16
And YES, that did actually work for me after doing it again. One thing I did differently is I made sure the "use ssl" was checked BEFORE running the wizard. I believe earlier I had already reverted to unchecking the SSL before I run the wizard then tried turning it on later. Anyway, re-running the wizard on both client and server worked.

**Comment by nlyan** [comment] 2016-09-27 09:51
Close as now obviously a dupe of #5617 . Sorry guys.

**Closed by nlyan** 2016-09-27 09:51 UTC
