### ISSUE TITLE
Won't connect if VmWare is loaded

### ISSUE THREAD

**Issue by eddyq** [symless/synergy#5949] opened 2017-03-27 23:58 UTC
### Operating Systems ###

Windows 10 on both sides

### Synergy Version ###
1.8.8-stable-25a8cb2 and many previous versions

### Steps to reproduce bug ###

1. One side I clicked Server, Configure interactively, and Apply. The other side I clicked Client, Auto config and Apply.

Server side lists a few ip addresses but the one in bold is wrong: 192.168.56.1 (that is my VmWare IP address). My IP address is 192.168.1.76 (listed but not bold).

I was having problems so I loaded the latest version. But I still can’t get Synergy to work. I can ping the client (192.168.1.76) and I can reach it using Remote Desktop. I notice Synergy is trying to connect to 192.168.56.1 but that I not any of the computers on my network (I’m on subnet 1).

**Comment by XinyuHou** [comment] 2017-03-30 15:45
Duplicate of #5765

**Closed by XinyuHou** 2017-03-30 15:45 UTC
