### ISSUE TITLE
Client missed if other client was disabled

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5861] opened 2017-02-25 22:46 UTC
### Operating Systems ###

Server: Windows Seven SP1 EN AMD64
Client: Linux Mint 17.3 and Linux Armbian (debian arm)

### Synergy Version ###

1.8.8-rc1-fc3cc78

### Steps to reproduce bug ###

I have one main PC (server), second PC (at left), notebook (at left) and single-board computer Orange Pi One over second PC. You can see my shema at next screnshot

![2017-02-26_01-32-26_5ceciaah](https://cloud.githubusercontent.com/assets/1897605/23335336/c0544354-fbc4-11e6-851c-029e6a059a1d.png)

Orange Pi One works fine while second PC is enabled. But if second PC disabled I can't move cursor to Orange Pi area, only main PC and notebook can be used.

**Comment by XinyuHou** [comment] 2017-03-01 12:10
Duplicate of #4801

**Closed by XinyuHou** 2017-03-01 12:10 UTC
