### ISSUE TITLE
Linux (server) to Windows 7 (client) CTRL sticks down

### ISSUE THREAD

**Issue by jenelcohen** [symless/synergy#5509] opened 2016-07-27 22:02 UTC
Moving from a Linux (server) to Windows 7 (client), sometimes the CTRL key gets stuck down.

Steps to reproduce:

1. Create a "lock screen" shortcut; right-click on desktop, create a shortcut with target "C:\Windows\System32\rundll32.exe user32.dll, LockWorkStation" and shortcut key of CTRL+ALT+L.

2. Press CTRL+ALT+L on the Windows machine. It fails better if CTRL and ALT are held down for a good while.

The Windows machine synergy client disconnects and reconnects every time the Windows machine is locked and unlocked:

{code} 
[2016-07-25T10:22:09] INFO: switch from "hutw6365" to "HUTW5972" at 1199,960 
[2016-07-25T10:22:09] INFO: leaving screen

// CTRL+ALT+L pressed to lock the Windows machine.

[2016-07-25T10:22:15] NOTE: client "HUTW5972" has disconnected 
[2016-07-25T10:22:15] INFO: jump from "HUTW5972" to "hutw6365" at 600,800 
[2016-07-25T10:22:15] INFO: entering screen 
[2016-07-25T10:22:18] NOTE: accepted client connection 
[2016-07-25T10:22:18] NOTE: client "HUTW5972" has connected 
[2016-07-25T10:22:20] INFO: switch from "hutw6365" to "HUTW5972" at 1199,504 
[2016-07-25T10:22:20] INFO: leaving screen

// Moved mouse pointer to client again, password typed in on locked screen.

[2016-07-25T10:22:27] NOTE: client "HUTW5972" has disconnected 
[2016-07-25T10:22:27] INFO: jump from "HUTW5972" to "hutw6365" at 600,800 
[2016-07-25T10:22:27] INFO: entering screen 
[2016-07-25T10:22:30] NOTE: accepted client connection 
[2016-07-25T10:22:30] NOTE: client "HUTW5972" has connected 
{code}

My suspicion is that Synergy doesn't like being restarted with the CTRL key pressed.

Sometimes pressing the CTRL key or other modifier keys on the client resolves the situation.

**Comment by XinyuHou** [comment] 2016-08-09 09:58
Duplicate of #4980

> The Windows machine synergy client disconnects and reconnects every time the Windows machine is locked and unlocked:

This is by design. In 1.8.2-stable we introduce a new feature to stop reconnecting if the process is already elevated.

**Closed by XinyuHou** 2016-08-09 09:58 UTC
