### ISSUE TITLE
Changing display configuration is not taken into account by Synergy

### ISSUE THREAD

**Issue by rprots** [symless/synergy#6146] opened 2017-09-11 16:27 UTC
### Operating Systems ###

Ubuntu 16.04.

### Synergy Version ###

1.9.0

### Steps to reproduce bug ###

1. Synergy server and client running.
2. e.g. in multi-monitor client modify display configuration - disable one of the displays
3. Can move mouse on client behind the screen like there is another display.

### Other info ###

Workaround is to restart client.

**Comment by XinyuHou** [comment] 2017-09-13 13:54
Duplicate of #4762

**Closed by XinyuHou** 2017-09-13 13:54 UTC
