### ISSUE TITLE
synergy 1.8.8 can`t copy file from mac to win7 or win7 to mac

### ISSUE THREAD

**Issue by zminds** [symless/synergy#5978] opened 2017-04-06 06:06 UTC
### Operating Systems ###

Server: macos 10.12.2 
Client: win7 x64 professional 7601 sp1

### Synergy Version ###

both  1.8.8

### Steps to reproduce bug ###

windows 7 debug log

```
[2017-04-06T14:05:15] INFO: entering screen
[2017-04-06T14:05:15] DEBUG: recv grab clipboard 0
[2017-04-06T14:05:15] DEBUG: open clipboard
[2017-04-06T14:05:15] DEBUG: empty clipboard
[2017-04-06T14:05:15] DEBUG: close clipboard
[2017-04-06T14:05:15] DEBUG: recv grab clipboard 1
[2017-04-06T14:05:15] DEBUG: open clipboard
[2017-04-06T14:05:15] DEBUG: empty clipboard
[2017-04-06T14:05:15] DEBUG: close clipboard
[2017-04-06T14:05:15] DEBUG: start receiving clipboard data
[2017-04-06T14:05:15] DEBUG: receiving clipboard 0 size=4
[2017-04-06T14:05:15] DEBUG: received clipboard 0 size=4
[2017-04-06T14:05:15] DEBUG: open clipboard
[2017-04-06T14:05:15] DEBUG: empty clipboard
[2017-04-06T14:05:15] DEBUG: close clipboard
[2017-04-06T14:05:15] INFO: clipboard was updated
[2017-04-06T14:05:15] DEBUG: start receiving clipboard data
[2017-04-06T14:05:15] DEBUG: receiving clipboard 1 size=4
[2017-04-06T14:05:15] DEBUG: received clipboard 1 size=4
[2017-04-06T14:05:15] DEBUG: open clipboard
[2017-04-06T14:05:15] DEBUG: empty clipboard
[2017-04-06T14:05:15] DEBUG: close clipboard
[2017-04-06T14:05:15] INFO: clipboard was updated
```

and win7 right click on desktop ,it had no paste item

But ,any text or Screenshot could copy and paste throught synergy

**Comment by XinyuHou** [comment] 2017-04-06 12:26
@zminds 

Currently Synergy doesn't support file copy and paste. It's on our roadmap. Please sit tight.

Duplicate of #4199

**Closed by XinyuHou** 2017-04-06 12:26 UTC
