### ISSUE TITLE
Serial key textbox on activation screen overflows on Mac

### ISSUE THREAD

**Issue by XinyuHou** [symless/synergy#5471] opened 2016-07-15 10:17 UTC
Mac 10.11

1. Open wizard
2. Go to activate page

On Mac
![image](https://cloud.githubusercontent.com/assets/9194706/16871236/b700edfa-4a7d-11e6-87dc-b8f2708fc72c.png)

On Windows
![image](https://cloud.githubusercontent.com/assets/9194706/16871261/debb8e0e-4a7d-11e6-85d5-f539bb01dae8.png)

**Comment by mightysnowdog** [comment] 2016-07-22 16:53
verified resolved with 
![screen shot 2016-07-22 at 10 58 14 am](https://cloud.githubusercontent.com/assets/7856203/17064581/c97d0b0a-5002-11e6-8e07-30e6d7365292.png)
synergy-v1.8.2-rc1-12e0120

**Comment by XinyuHou** [comment] 2016-08-02 09:30
https://github.com/symless/synergy/issues/5490#issue-167075589

**Comment by XinyuHou** [comment] 2016-08-02 09:32
https://github.com/symless/synergy/issues/5492#issue-167099278

**Comment by cmerlo441** [comment] 2016-08-02 12:09
1.8.2, OS X 10.11.6, I can't reproduce the original error.

**Closed** 2016-08-05 11:40 UTC
Labels: bug
