### ISSUE TITLE
Lose Control after Server Restart!!!

### ISSUE THREAD

**Issue by yidhoe** [symless/synergy#5756] opened 2016-11-29 18:49 UTC
### Operating Systems ###

Server: Windows 10 (x64) 1607
Client: Windows 10 (both x32 & x64) 1607

### Synergy Version ###

1.8.5

### Steps to reproduce bug ###

Synergy Server is on Gaming PC.
Synergy Client on TV Box and also Office PC and Tablet.

1. Restart Synergy Server PC with Clients still running.
2. Watch mouse jump to Client PC and won't respond, have to restart Synergy clients to get mouse back on Host PC so that you can login! :/

### Other info ###

Around 1.8.2 I would guess but not sure, I have relative mouse enabled on the server along with Don't Take Foreground Window on Windows servers.

I forgot to mention this but when a friend of mine brought it after I linked him the Black Friday deal he has noticed it too.

Thanks

**Comment by XinyuHou** [comment] 2016-12-05 16:29
Duplicate of #5075

**Closed by XinyuHou** 2016-12-05 16:29 UTC
