### ISSUE TITLE
After update 1.8.3, i cannot connect to server anymore

### ISSUE THREAD

**Issue by demonguy** [symless/synergy#5625] opened 2016-09-27 04:17 UTC
### Operating Systems ###

Client: Ubuntu 14.04

Server: windows 10

1. It's alright when i'm using 1.8.2
2. After updating 1.8.3 today(windows by .msi, ubuntu by .deb, both downloaded from your http://symless.com/synergy/)
3.now the client always tried to connect server and timed out

client log:
```
[2016-09-27T12:16:18] NOTE: connecting to '192.168.0.11': 192.168.0.11:24800
[2016-09-27T12:16:18] NOTE: server fingerprint: 34:62:A3:31:6D:3D:58:48:B9:C8:EE:91:C3:F6:5F:E4:7B:F5:FF:CD
[2016-09-27T12:16:34] WARNING: failed to connect to server: Timed out
```

server log:
```
[2016-09-27T12:19:25] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-09-27T12:19:25] INFO: accepted secure socket
[2016-09-27T12:19:25] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-09-27T12:19:42] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-09-27T12:19:42] INFO: accepted secure socket
[2016-09-27T12:19:42] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
```

**Comment by pmario** [comment] 2016-09-27 07:50
I just got an e-mail with this info: 

```
There's a known issue in Synergy 1.8.3 where the SSL plugin can be out of date, which stops the client connecting to the server. To fix this, please re-run the wizard on all of your machines.

1. Open Synergy on the server
2. If Windows: Go to the Edit, then click Settings
3. If macOS: Go to Synergy, then click Preferences
4. Ensure the "Use SSL encryption" checkbox is enabled
5. Go to File, then Run Wizard
6. Click Next until you see the Activation screen 
7. Enter your login details or serial key 
8. Click "Continue" and finish the wizard
9. Repeat those steps for each client

I'm sorry you had to do that, it's a pretty major screw up on our part, sadly we didn't see this while testing. If those steps don't help, please let us know so we can troubleshoot further. Thanks for your patience!
```

For me it fixed the problem. ... AND I did restart both of my computers :)

**Comment by pmario** [comment] 2016-09-27 07:52
imo is related to  #5617

**Comment by demonguy** [comment] 2016-09-27 08:19
Thanks. Actually i did the same thing but it doesn't help.
And now i finally found that i shouldn't start server before running client wizard. At first, i think i can start server after running server wizard and then run client wizard.
Now it solved. thanks

**Comment by nlyan** [comment] 2016-09-27 09:50
Dupe of #5617

**Closed by nlyan** 2016-09-27 09:50 UTC

**Comment by thomasttvo** [comment] 2017-05-22 08:42
I have the same problem. Tried what demoguy suggested, didn't work. Tried the SSL route, the checkbox is greyed out :|

**Comment by mgserafi** [comment] 2017-07-17 17:01
@thomasttvo how did you manually change the IP address?
