### ISSUE TITLE
Use the keyboard and mouse from any computer

### ISSUE THREAD

**Issue by spronkey** [symless/synergy#4588] opened 2015-04-28 23:49 UTC
One of the configurations I like to use is laptop sitting in front of a series of displays, and I'll use the laptop keyboard, but the mouse that's connected to the desktop machine.

What I'd like to be able to do in this case is have Synergy work two-ways, i.e. so I can use either keyboard/mouse to control either machine that's connected.

**Comment by richcarl** [comment] 2015-05-28 11:27
This is a duplicate of a ticket that I voted for, back when the issues weren't on github. I can't find it now. But this is exactly what I want - there's no room for putting the desktop keyboard in front of the laptop, and I can't put it _on_ the laptop.

**Comment by richcarl** [comment] 2018-06-21 20:39
Too bad you're closing this. It was literally the only feature that I was hoping for which made me pay for Synergy to begin with.

**Comment by nbolton** [comment] 2018-06-21 20:45
@richcarl Have you tried Synergy 2 Beta? https://symless.com/synergy/features/s2

**Comment by richcarl** [comment] 2018-06-21 20:49
I did, briefly, but couldn't see anything about bidirectional sharing there either.

**Comment by nbolton** [comment] 2018-06-21 21:21
Bidirectional sharing works in Synergy 2. Give it a try.

**Comment by richcarl** [comment] 2018-06-21 21:32
Sounds good - will do.

**Comment by richcarl** [comment] 2018-06-26 08:50
Can't get Synergy 2 (2.0.12) to run on the Macbook - stuck in a loop of fail - restart server - retry - login - fail ...
And why does it keep trying to authenticate after each retry on the Mac, while it seems to be happy with only doing it once on Windows?

**Comment by nbolton** [comment] 2018-06-26 10:00
Hmm, sounds like a bug!

**Comment by richcarl** [comment] 2018-06-26 16:38
Pretty much the situation reported here: https://github.com/symless/synergy-core/issues/6187 - except for the repeated request to log in on every retry. Also, I've never had it work even once, despite multiple restarts and reboots.

**Comment by nbolton** [comment] 2018-06-27 08:59
@richcarl Thanks, I've reopened #6187.

**Comment by richcarl** [comment] 2018-09-03 12:42
After removing all of ~/Library/Synergy and /Applications/Synergy.app and reinstalling, I got away from the weird re-authentication loop. Still can't connect to the Windows 10 machine from the Mac but that seems to be because of the "Invalid JSON request: bad numeric conversion: negative overflow" problem - see e.g. https://symless.com/forums/topic/5571-209-mac-connection-problem/

**Comment by richcarl** [comment] 2019-09-04 12:26
With Synergy 1.10.3, I can finally get Mac OS and Windows 10 to work together again. Since Synergy 2 has gone back to the drawing board, can I ask again how hard it would be to get Synergy 1 to send mouse and keyboard events both ways?

**Comment by nbolton** [comment] 2019-09-05 13:11
@richcarl Being able to use any mouse/keyboard was one of the major benefits to Synergy 2, so we'll certainly be adding it to the next major version. We don't have any plans to add this to Synergy 1.

**Comment by Pomax** [comment] 2019-09-19 17:12
Unless there is a roadmap for synergy 2, please consider adding this to v1 _as well_ because if we have to wait a year for v2 to come out, that's a year of "we could have had this for a year now". Something this important to laptop+desktop setups shouldn't have to wait for a v2 release =)

**Comment by nbolton** [comment] 2024-09-06 21:59
This is implemented in Synergy 3, so I will close this issue.

**Closed by nbolton** 2024-09-06 21:59 UTC
Labels: enhancement, triage, unanswered
