### ISSUE TITLE
synergy does not work with wayland?

### ISSUE THREAD

**Issue by d3acon** [symless/synergy#5763] opened 2016-12-05 14:30 UTC
### Operating Systems ###

Server: Fedora 25 64bit
Client: Windows 10 64bit

### Synergy Version ###

1.8.5 (synergy-master-stable-6a7703f-Linux-x86_64.rpm)
But I tried different versions: 1.8.3, 1.8.6-rc1

### Steps to reproduce bug ###

Start the server on Fedora 25 and move the mouse to a client.
Fedora 25 uses Xorg 1.19 (xorg-x11-server-Xwayland-1.19.0-1.fc25.x86_64). I guess the problem is related to the use of wayland. The client connects without problems to the server. Once you move the mouse over to the client, the client says that the server is dead. The mouse cursor is now only visible in the console window, where the server was started, until you kill the server. The debug trace is not very useful, but can be provided if necessary.  

### Other info ###

* When did the problem start to occur? When I...
upgraded the system to fedora 25. Before it was working with the same config and the same client.
* Is there a way to work around it? No/Yes, you can...
I haven't found one yet.
* Does this bug prevent you from using Synergy entirely? Yes/No
yes

Put anything else you can think of here.

**Comment by mallardduck** [comment] 2016-12-07 16:35
Just a heads up, this is a duplicate of #4090 which has been largely ignored by the developers since around 2014.

Initially when I found it I excused it as 'Oh, 2014 Wayland wasn't too common then'. As I read and saw the date jumping nearer and nearer to the present I got less optimistic. Wayland is becoming fairly popular at this point and on some systems it's a requirement; not having proper Wayland support when 2017 is around the corner doesn't  give me good feelings about future support for this app.

**Comment by SirScott** [comment] 2016-12-09 15:51
> Is there a way to work around it? No/Yes, you can...
>I haven't found one yet.

FWIW, you can disable Wayland by setting `WaylandEnable=false` in `/etc/gdm/custom.conf`  This worked for me in F25 64bit.

Would still love to have Wayland supported in Synergy though.

**Comment by mallardduck** [comment] 2016-12-09 16:46
It should be noted that this is not a workaround. This is turning off
Wayland and as I mentioned that is NOT an option for certain users.

**Comment by polarathene** [comment] 2016-12-12 06:15
Paid user here if that makes any difference. I'd like to start using Wayland in 2017, hope this gets some attention and someone responds with a status update on the other issue @mallardduck . With Gnome having switched Wayland on as default(I get that you can change it), newer releases(and I assume rolling distro's already) will be very common in hitting this problem.

**Comment by d3acon** [comment] 2016-12-12 11:59
Unfortunately turning off wayland does not work for me (this is another story - and another bug report). Nevertheless... it looks like Xorg is going to be fully replaced in all systems and therefore this project has to fix this, or remove the debian and ubuntu signs from their page.

**Comment by aairey** [comment] 2016-12-16 08:15
@d3acon and Fedora, they've been using wayland as default for more as a month now.
Which will soon be in RHEL and CentOS. (end 2017 at the soonest)

**Comment by inet-pwnZ** [comment] 2016-12-20 02:45
paid user really looking forward to the wayland update

**Comment by polarathene** [comment] 2016-12-21 21:47
Although there is no response on these issues I've contacted support and have some good news:

> Synergy will indeed support Wayland in 2017, as we're working hard on this!

**Comment by XinyuHou** [comment] 2016-12-30 14:58
Duplicate of #4090

**Closed by XinyuHou** 2016-12-30 14:58 UTC

**Comment by nbolton** [comment] 2024-08-30 15:41
Fixed by: https://github.com/symless/synergy/pull/7449
