### ISSUE TITLE
Synergy on ARM (UNIX)

### ISSUE THREAD

**Issue by jrjhealey** [symless/synergy#6051] opened 2017-05-28 23:05 UTC
### Operating Systems ###
Rapbian Jesse
Version:April 2017
Release date:2017-04-10
Kernel version:4.4

### Synergy Version ###

1.8.π

Hi I was wondering whether it's possible to run synergy on ARM architecture? All the precompiled binaries appear to be incompatible at present.

If it can be done, are there any additional steps needed to compile from source on an ARM system?

**Comment by XinyuHou** [comment] 2017-06-06 13:30
Duplicate of #6029

**Closed by XinyuHou** 2017-06-06 13:30 UTC
