### ISSUE TITLE
Synergy eats a lot of RAM when move to other pc : Screenshot in Clipboard

### ISSUE THREAD

**Issue by Scottvishnu** [symless/synergy#5677] opened 2016-10-17 17:29 UTC
### Operating Systems ###

Client: Archlinux x64

Server: Microsoft Windows 10 Home

### Synergy Version ###

1.8.5 = Server
1.8.4 = Client

### Steps to reproduce bug ###

1. Press the Desktop Screenshot Button
2. Move to Second PC
3. Synergy fill the RAM completely full
4. System laggs because of full ram

https://youtu.be/dpbqO3HRuHY

### Other info ###

* When did the problem start to occur? When I did move to a new Synergy Version.
* Is there a way to work around it? No.
* Does this bug prevent you from using Synergy entirely? Yes.

**Comment by XinyuHou** [comment] 2016-10-19 10:11
Duplicate of #5138

**Closed by XinyuHou** 2016-10-19 10:11 UTC
