### ISSUE TITLE
Windows - UAC disables client's and server's connection

### ISSUE THREAD

**Issue by piotrva** [symless/synergy#5718] opened 2016-10-31 16:33 UTC
### Operating Systems ###

Server: Windows 7 x64
Client: Windows 7 x64

### Synergy Version ###

v1.8.5-rc1-b66043e

### Steps to reproduce bug ###

1. Connect Client and Server with SSL
2. On client start some installation that displays User Account Control message (and fades the screen on client)
3. When UAC message is displayed and closed cursor moves back to the center of the server's primary screen

### Other info ###

Server log:
[2016-10-31T17:21:38] INFO: switch from "Piotr-PC" to "Piotr-Laptop" at 0,546
[2016-10-31T17:21:38] INFO: leaving screen
[2016-10-31T17:21:55] NOTE: client "Piotr-Laptop" has disconnected
[2016-10-31T17:21:55] INFO: jump from "Piotr-Laptop" to "Piotr-PC" at 960,540
[2016-10-31T17:21:55] INFO: entering screen
[2016-10-31T17:22:01] INFO: OpenSSL 1.0.2 22 Jan 2015
[2016-10-31T17:22:01] INFO: accepted secure socket
[2016-10-31T17:22:01] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2016-10-31T17:22:01] NOTE: accepted client connection
[2016-10-31T17:22:01] NOTE: client "Piotr-Laptop" has connected

**Comment by piotrva** [comment] 2016-10-31 17:56
Same happening when UAC is doing its stuff on server. Server crashes with Windows: synergys.exe stopped working.

**Comment by XinyuHou** [comment] 2016-11-25 16:56
Duplicate of #5663

**Closed by XinyuHou** 2016-11-25 16:56 UTC
