### ISSUE TITLE
Unable to drag-select in MS Office

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3044] opened 2014-10-13 06:23 UTC
**Imported issue:**

* Author: Jaspreet Sidhu
* Date: 2012-02-21 07:22:43
* Legacy ID: 3113
* Version: 1.4.7

**Steps to reproduce:**  
  
1. Click and drag no longer works when using 1.4.6 or 1.4.7. Using a Logitech Performance Mouse MX and in applications such as Chrome address bar, Photoshop, Microsoft Word, I can double-click to select/highlight a word, but cannot click & hold to select/highlight text. In Photoshop, I can not draw a selection box by clicking and dragging.   
  
Expected: should be able to select, highlight text  
Actual: unable to create a selection box and/or highlight text  
  
**Versions (Synergy, OS):**  
  
Server: 1.4.7 Windows 7 x64 both as a service and just running normally  
Client 1: 1.4.7 Mac OS X 10.7.3  
  
**Workaround:**  
  
Disable server  
  
**Comments:**  
  
log shows no errors, is there a debug version?

Also applies to, Photoshop, and other applications

**Comment by ashenkin** [comment] 2015-03-19 15:17
I seem to be having the same issue in 1.6.2 on Win 7 Ent x64.  Intermittent.

**Comment by shadeflayer** [comment] 2015-04-16 11:18
I have the same issue but its limited to tables within Office 2013 on the Win8.1 system.  However it seems to be intermittent and I can not easily replicate it.  Synergy setup is as follows:  I have a Linux Mint 64bit client (v17 Cinnamon) on the left, Win8.1 server in the middle (dual screen), and a Macbook Pro client (OS X v10.10.3) on my right (laptop).

FYI - The crazy mouse movement problem still exists in WoW.  Scroll Lock is enabled.  Shutting down the Synergy server solves the problem.  

Server config file is as follows:

section: screens
	Linux:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
	PALADIUM-D:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
	MacBookPro:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
end

section: aliases
end

section: links
	Linux:
		right = PALADIUM-D
	PALADIUM-D:
		right = MacBookPro
		left = Linux
	MacBookPro:
		left = PALADIUM-D
end

section: options
	relativeMouseMoves = true
	screenSaverSync = false
	win32KeepForeground = false
	switchCorners = none 
	switchCornerSize = 0
end

**Comment by Amatyr** [comment] 2015-08-15 15:22
This has started to be a problem for me in 1.7.4 after moving to Windows 10. Worked perfectly for me on Win7.

**Comment by BenKelada** [comment] 2015-08-26 06:16
win 7 x64 1.7.4 word 2007 , cant drag and select text
having come back to synergy, and updating to a paid user account my memory was that it used to be a lot more stable! thanks for fixing the cpu bug if you could fix this it would improve the usability

**Comment by bogardpd** [comment] 2015-08-28 03:38
I'm having the same thing happening as Amatyr. Running Synergy 1.7.4 and Word 2013 on Windows 7 it worked fine; I upgraded to Windows 10 and now Word isn't letting me consistently drag to highlight or change table column width. Stopping Synergy fixes the problem.

**Comment by altjx** [comment] 2015-10-19 17:34
Any updates on this? I just identified this problem when trying to select text in Microsoft Word. Seemed like it was a race with selecting as much text as I can before my "drag select" stops working.

**Comment by sthilaire** [comment] 2015-10-21 19:01
The "click drag" issue with the combination of Windows 10 and Word 2013 is confirmed here also.

**Comment by askay4** [comment] 2015-10-23 21:39
Same here; upgraded to Win10 and highlighting and drag capability went away; returns when I turn off Synergy on the server side. 1.7.4

**Comment by bitroniq** [comment] 2015-11-03 11:10
Same thing here. On host @Win10 64bit Synergy 1.8.0-alpha-19835b6 only double-tap-Win-key helps.

**Comment by lucanos** [comment] 2015-11-06 01:47
Same Problem Here:

Synergy Pro v1.7.4
Windows 7 (64 bit)

**Comment by ajn1985** [comment] 2015-12-11 20:00
I'm experiencing the same issue (cannot click, drag to select text), mainly with microsoft office programs. The moment I turned off the synergy server the issue is resolved.

Temporary solution:
Turn off and on (or stop/start) the synergy server. I'm able to click drag to select in office.

**Comment by zdyang** [comment] 2015-12-20 06:04
I have the same issue.
Synergy 1.7.6
Windows 10 (64 bit) with MS Office 2016.

Double-tap win key works for me but very annoying.

**Comment by lucanos** [comment] 2015-12-20 15:45
@nbolton, this is a "priority-issue" according to your own tags, but has seen no resolution for over 12 months. Can we at least get an update? An indication that some action is underway?

**Comment by jk3us** [comment] 2016-03-16 22:37
I've noticed this problem as well, but for me just opening the Synergy UI and clicking "Apply" (making it restart the service) temporarily fixes the problem.  

It might be related to what I described at https://github.com/symless/synergy/issues/5202#issuecomment-195030954, where certain "pseudo-events" seem to get swallowed by synergy and don't make it to the intended application.

**Comment by jk3us** [comment] 2016-03-18 21:01
This also causes problems with Ctrl+Backspace, which usually deletes the previous word, but when this problem occurs it doesn't work in outlook, it prints a square instead.

**Comment by arbourp** [comment] 2016-04-19 01:04
Version 1.7.6 on Windows 7 x64 enterprise.
Problem occurs, as noted, fix by jk3us works, stop and restart synergy.  I'm connected through a VPN, so my remote system can't find me, and thus I can't leave the local screen, but i suspect if I jump in and out to a remote screen the problem will re-occur.

Will test some iterations tomorrow.

**Comment by ENickRyan** [comment] 2016-04-27 14:40
@nbolton I am a long time Synergy user. Love this product! Please fix this bug. It breaks my workflow 10 times a day. Stopping and restarting Synergy is a pain to do that often. I am running 1.7.6 at this moment with a Windows 7 Pro server and El Capitan client. I suspect this one is impacting to many users so it warrants a quicker fix.

**Comment by cmalmqui** [comment] 2016-04-28 14:03
Same problem with version 1.7.6 on Win7 64bit making selection via mouse in Word/Outlook useless. Had to uninstall the software as I unfortunately spent most of my time there. 

Used Synergy extensively in multimachine setups on offshore survey installations 2005 to 2010 and will not ask for refund as I was mighty happy back then and hope to see the project make a living.

**Comment by LittleLama** [comment] 2016-05-06 08:57
So much annoying bug ... please fix it before I throw my laptop threw the window lol. 
Happening on MS Word.

**Comment by MitchTalmadge** [comment] 2016-05-08 01:48
I am also facing this problem and have been ever since I first installed Synergy. The latest version still has the same issues. Please fix this!

**Comment by ashenkin** [comment] 2016-05-11 07:57
One year later, problem persists

**Comment by ITN1nja** [comment] 2016-05-17 19:08
I face this issue. Is it true that the issue has roots back to a 2012 version?

I am on Win7 x64, Synergy 1.7.6.

As some have mentioned logitech mouses (mice? meeces?), I am using a M705 with a unified receiver. I can work around the issue on the host by simply stopping the service.

**Comment by prophoto** [comment] 2016-05-17 19:44
@ITN1nja I've had this issue for years...

**Comment by dvassy** [comment] 2016-05-19 02:41
I have tracked it down to the following (Windows 7-64 environment):

-     If synergy server is running, then a press on the CTRL key will inhibit the ability to select text, or drag-and-drop text, in some applications (including Word, Outlook, Skype - list not necessarily exhaustive) on the server machine
- A press on WIN key (and back) will return the Mouse selection behavior it to normal, until the CTRL key is pressed again
-     Stopping the Synergy server fixes the problem
-     Restarting the Synergy server dos not make the problem reappear until a client connects
-     This issue does not show up when Synergy is being run in client mode

The problem is very easy to reproduce, just follow the protocol above.

**Comment by MitchTalmadge** [comment] 2016-05-19 03:15
Nice find @dvassy! It should be much easier to track down and solve the problem after knowing how to reproduce it.

**Comment by dvassy** [comment] 2016-05-19 05:11
Thanks @MitchTalmadge. Also worthy of note, contrary to what the title picked by @nbolton for the bug report suggests, this behaviour is not dependent on the type of mouse being used, as far as I can say. At least for me, Bluetooth mouse or wired mouse => same story.

**Comment by jk3us** [comment] 2016-05-19 16:01
@dvassy Maybe this is what you meant, but it does appear that pressing CTRL _while focused on a client_ causes the problem.  Pressing CTRL while focused on the server doesn't.

The WIN key fix only fixes some of the problems for me. Selecting text in outlook works again, but things like mouse keys mapped to keypresses and print screen key triggering greenshot still require synergy to be restarted.

**Comment by dvassy** [comment] 2016-05-19 23:44
Fair comment @jk3us. Also, it appears that reproducing the bug may be less straightforward than I thought. After doing it reliably for 3 days in a row, I cannot reproduce it anymore. Not idea yet "what has changed". Il will document that when I find out

**Comment by lucanos** [comment] 2016-05-20 08:17
It's terrific that so many users are working together to try and locate the cause of the problem, or at least the conditions under which the problem can be reliably reproduced, but unless the Synergy Developers are getting involved in the discussion, we're discussing the angle of the list on a sinking ship - no matter how detailed we can get in describing the problem, the damned ship is still sinking.

We really need the Synergy Devs to start taking ownership of this critical bug and giving us some feedback on when we can expect it to be resolved.

**Comment by prophoto** [comment] 2016-05-20 12:49
@lucanos 2nd that.

I've been dealing with this issue for years, ever since I found synergy.

**Comment by prophoto** [comment] 2016-05-20 12:51
Seems there is a fair bit of discussion about using ctrl key on the client. This happens to me on the server all the time until I stop the service.

**Comment by ITN1nja** [comment] 2016-05-20 15:21
A few additional comments on the symptoms. 

I, too, have verified that the issues is presenting when a CTRL key is press while a client is in focus. However, it does not appear to be consistent. 
 
The actions also seem to affect my ability to scroll with the mouse wheel as well when the conditions are triggered.

**Comment by genepool99** [comment] 2016-06-01 21:45
I can confirm the issue on windows 7 with Windows as the server and ubuntu 16.04 client. I can also confirm clicking the crtl key on the client then going back to windows temporally resolves the issue.

**Comment by nlyan** [comment] 2016-06-10 15:34
We have reproduced this reliably with Wordpad on a Windows 10 server. 

Steps to reproduce:
1. Start Synergy server
2. Start Wordpad and type something
3. Try to select text with the mouse

Expectation:
Text selected

Results:
Nothing happens

**Comment by cooch17** [comment] 2016-06-10 16:14
Confirmed -- using Win 7 Pro SP 2 as server (Synergy 1.7.6), with GNU/Linux client (RH 6, running 1,7,6). Problem is intermittent (i.e., it doesn't always happen, and sometimes, if you wait for a minute or two, things revert back to normal). 

Makes using Synergy really a tough choice at present. I'm frequently trying to cut/copy code from a terminal on Windows machine to paste into my number crunching Linux box, but at this point, can't even use the mouse to select the code. I can use various keystroke solutions to select text, but using the mouse to select blocks of text is not functioning consistently.

**Comment by nothinelse** [comment] 2016-06-10 17:18
Just adding my 2 cents on this very annoying issue:

Synergy 1.7.6
Synergy server on my Win7 SP1 64-bit laptop
No client connected

I take my laptop to work and regularly experience the issue when the client is not connected. It seems Synergy works along happily for a while and then eventually gets into the fault state where selecting text is blocked (in Outlook for me). Once it is in this fault state I can 100% reproduce the problem by alt+tabbing away from Outlook and then back again. Hitting the Windows key twice will clear it but the very next alt+tab combination brings it back every time. If I open up the Synergy client and click Apply, the fault clears and remains cleared for some time (alt+tab combo no longer reproduces the fault). As for what gets it into the fault state I haven't made that connection yet.

**Comment by iamlolz** [comment] 2016-06-13 22:36
This effects me in photoshop with version 1.7.6 on win10 64-bit. A shame really, I wouldn't have purchased this if I'd known, it's quite disruptive.

**Comment by MitchTalmadge** [comment] 2016-06-13 22:39
1 year and 8 months with not even a word from the developers :+1:

**Comment by virtualdxs** [comment] 2016-06-14 01:49
@MitchTalmadge I see that 3 days ago Jerry referenced it.

**Comment by MitchTalmadge** [comment] 2016-06-14 01:54
I stand corrected; 1 year, 7 months, and 27 days and finally a word from the developers. Hope it gets fixed soon

**Comment by orcinus** [comment] 2016-06-19 00:25
Keep hoping, i hear hope dies last.

**Comment by orcinus** [comment] 2016-06-19 00:26
"priority-soon"... fucking LOL.

**Comment by nothinelse** [comment] 2016-06-20 17:28
Hi everyone if you're using Windows only I've found the solution. Follow these easy steps:

- uninstall Synergy
- install Input Director (http://www.inputdirector.com/downloads.html - I installed the v1.3 beta which hasn't been updated since 2012 but still functionally better than Synergy, works fine in Win10 even though it gives a warning)
- follow the easy configuration setup
- problem solved

For cross platform users:

- continue to wait
- never get a fix

good luck!

**Comment by iamlolz** [comment] 2016-06-20 22:09
I have been able to reproduce this fix in my local environment.

**Comment by jmacko** [comment] 2016-06-25 19:38
This one bug makes the product nearly unusable for me.  So much so that I'm forced to only turn it on selectively.  

I'm at a loss for if it's a bigger pain to reach for the keyboard or start synergy.  Rather disappointing that this isn't a critical bug.  Given the sheer number of people that use Microsoft Office, I would of expected this to be a critical must fix now bug.

**Comment by cooch17** [comment] 2016-06-25 19:51
It isn't just MS Office that is impacted -- in fact, I don't use Office at all. I do, though, use any number of other applications (coding editors, statistical and mathematical software), where I have the same problem. I suspect that all of the affected applications use the same basic API for mouse calls etc, that doesn't play nice with Synergy (the end result being that Synergy breaks those applications). 

This is a known problem -- and I suspect that Synergy folks are working on it. But what is a bit disconcerting is that it has been known for some time. 100% of dev effort should be on this bug. Period. Not on folder drag and drop or other such things, and especially not on irrelevancies like what the Synergy GUI looks like. Synergy now has a near-fatal flaw. It breaks the work environment for a *lot* of people. It didn't used to. Something has been added between 1.2 (when I started using Synergy) and the most recent build, which breaks things. I don't have the time to roll back through every earlier version of Synergy to see where the problem first showed up -- but that is what the dev team should be doing. Full time. Full stop.

**Comment by orcinus** [comment] 2016-06-25 21:37
"Some time" in this case being almost 10 years, like with most Synergy issues.

**Comment by prophoto** [comment] 2016-07-01 14:21
Does the latest beta address this issue? I filled out the beta request form, how do I install it on Win10x64 to test?

**Comment by nlyan** [comment] 2016-07-06 15:54
The latest betas do not address this issue, but we're currently working on it. Its an extremely curious issue and, although we know precisely when it occurs, we cannot yet explain the behavior.

**Comment by cooch17** [comment] 2016-07-06 16:09
Three quick comments:

1\ thanks for the update. Nice to get an 'official' comment on the status of things -- even if the news isn't announcing a solution...

2\ a point I made earlier -- and worth remembering. This isn't an Office-specific bug. I suspect a number of people might assume as much, but I suspect that is an artifact of said people spending a lot of time working in Office. I rarely spend time using office (unless I have to), so I have more experience with the 'bug' as it affects other applications. And it affects a lot of applications. And not simply drag-select. Any number of 'mouse actions' are DOA if I'm runnng Synergy -- again, not all the time, just some of the time. And, only on the server, and not on the client (I run Win 7 server, GNU/Linux clients). 

3\ sorry, but this bug renders Synergy all but useless for me and a number of folks -- t the moment, I have a couple of .bat files on my desktop -- one to turn the Synergy service on, and one to turn it off. I turn it on long enough to switch over to my GNU/Linux machines to start some number-crunching project, then switch it off once I'm finished. Kind of annoying to have to do this, no?

4\ whats odd is that this is a *new* bug. Back in the 1.4.x, 1.5.x days, never saw this bug. There is something in the 'new (but apparently 'not improved') version of Synergy that is causing the problem.

**Comment by kimling** [comment] 2016-07-07 07:36
I changed to Elevate mode and now I can drag-select in MS Word

**Comment by XinyuHou** [comment] 2016-07-11 12:52
Can anyone test this nightly?
http://symless.com/nightly?filter=85bbbd4

**Closed** 2016-07-11 12:51 UTC
Labels: bug

**Comment by cooch17** [comment] 2016-07-11 13:17
Trying it now. So far so good (buts it's only been 20 minutes ;-)

**Comment by MitchTalmadge** [comment] 2016-07-11 13:21
Nightly solves all the issues I've been having with Photoshop and Illustrator. As stated above, it's only been 20 minutes, so I'll report again later.

**Comment by bambooLoutre** [comment] 2016-07-11 13:24
seems okay for me too

**Comment by MitchTalmadge** [comment] 2016-07-11 13:47
Still working perfectly. I think you take the cake on this one, @XinyuHou

**Comment by joubertredrat** [comment] 2016-07-13 14:55
Hi guys, 

About https://github.com/symless/synergy/issues/4768#issuecomment-232332581

On nightly http://symless.com/nightly?filter=0034ca4 the problem doesn't happen, work normally.

**Comment by XinyuHou** [comment] 2016-07-14 09:33
> Random read client with 0034ca4, was after open World of Tanks game client to test about caps lock.
> 
> https://gist.github.com/joubertredrat/a990637e4323ce94bf934bda991ea4c2

**Comment by XinyuHou** [comment] 2016-07-14 09:34
@joubertredrat 
Did you run WoT in full screen mode?

**Comment by joubertredrat** [comment] 2016-07-14 10:57
@XinyuHou no, I run in windowed mode.

**Comment by XinyuHou** [comment] 2016-07-14 13:22
@joubertredrat 
I can't reproduce this on my Mac 10.10 server and Windows 10 client. 

Running World of Warships on windowed mode. Use Mac keyboard and press caps lock and random keys doesn't do anything weird. 

Could you give me some instructions about how to reproduce this.

**Comment by prophoto** [comment] 2016-07-14 15:31
Just tested 85bbbd4 on Windows 10 x64 in a domain (server) with macOS Sierra beta 16A238m (guest) and so far so good. Drag to select bug seems to be gone! Tested in Photoshop CC 2016.5 and Lightroom 2015.6 (both latest versions, not beta). I've not had any issues so far, drag/select works fine in chrome and Outlook 2016 too. Yay! I can use synergy again!

**Comment by staaronis3** [comment] 2016-07-17 16:36
I have just updated to 1.8.2-beta-85bbbd4 and I think that it resolves the problems with Photoshop/Office/Dell Display Manager. I have tried to reproduce following the steps that I had posted on issue #4508.

**Comment by GollyRojer** [comment] 2016-07-23 18:05
So, is this thread closed?  It says, so.  But I received a notice to test it on June 22nd, yesterday.  So I will report anyway.  I followed the instructions as given.  The selected text was highlighted successfully.

**Comment by LeadManPL** [comment] 2016-07-27 14:22
Tested Issue #3044:
1. Configure as server on Windows
2. Edit > Settings > Ensure 'Elevate mode' is ticked
3. Click 'Apply'
4. Start Microsoft Word or Wordpad
5. Type some text then try to drag select
6. See that text is highlighed sucessfully

Synergy Version: 1.8.2-rc1-12e0120
Tested OS: Windows 7 Pro

Result: SUCCESS. I was able to highlight text in Word.

**Comment by TxRxFx** [comment] 2016-07-28 11:51
Followed instructions:

Works on both Win10 and Win7 x64

synergy-v1.8.2-rc1-12e0120-Windows-x64

**Comment by btg308** [comment] 2016-08-01 12:53
Tested and working on Win10, Word 2016.
synergy-v1.8.2-rc1-12e0120-Windows-x64
