### ISSUE TITLE
L-shaped Monitor Setup

### ISSUE THREAD

**Issue by Morl0ck** [symless/synergy#5182] opened 2016-01-14 20:11 UTC
This is my current monitor setup.

```
-------------  ------------
|     1     |  |    2     |
-------------  ------------
-------------  ------------
|     3     |  |  Laptop  |
-------------  ------------
```

Monitor 1, 2, & 3 are part of my desktop that is running the synergy server.

I want to be able to move my mouse to my laptop using the bottom side of screen 2 and the right side of screen 3 of my dektop.

Is this possible?

**Comment by XinyuHou** [comment] 2016-01-18 20:07
Unfortunately this is not supported right now. I will mark this as a feature request.

**Comment by poxin13** [comment] 2016-01-26 15:11
I have this exact setup, would love support for this.

In this same example is it possible to make the right side of monitor 3 move to the 'Laptop' ? Currently it's using the right side of monitor 2. Can't figure the configuration out.

**Comment by ramon-villain** [comment] 2016-02-25 20:37
Same here. :(
![display](https://cloud.githubusercontent.com/assets/1520006/13333560/5ff284de-dbe6-11e5-83c1-ab86a74760e6.jpg)

**Comment by jettero** [comment] 2016-08-22 18:17
Well, fooey. I always used to love synergy, but if I can't tell it which monitor edges to use on dual and tripples, it's completely broken on the machines I wanted to use it on.

I wish there was any alternative. The $20 doesn't bother me, but the mouse moves sure do.

**Comment by poxin13** [comment] 2016-09-01 22:58
Ditto @jettero I ended up switching to their product since the monitor setup wizard is leaps and bounds better

**Comment by xhoy** [comment] 2017-01-05 07:45
I have a similar issue with 3 screens and a linux laptop.

```` 
    -------------  ------------ -------------  
    |  pc1-1    |  |   pc1-2  | |   pc1-3   |
    -------------  ------------ -------------  
-------------  
|   laptop  |
-------------  

```` 

Why cant i just add pc1, 3x as 3 different monitor's  on the grid? that the laptop and screen dont align exactly isn't the best thing but it works :)

**Comment by xhoy** [comment] 2017-01-05 07:47
Ow This seems to be a duplicate of issue #4173

**Comment by nbolton** [comment] 2017-01-17 10:08
@XinyuHou  @xhoy Yes, this is a dupe of #4173

**Closed by nbolton** 2017-01-17 10:08 UTC
Labels: feature
