### ISSUE TITLE
Failed RPM dependencies on Fedora

### ISSUE THREAD

**Issue by DerEnderKeks** [symless/synergy#5904] opened 2017-03-12 01:05 UTC
### Operating Systems ###

Server: Fedora 25
Client: Fedora 25

### Synergy Version ###

1.8.8-1 (master branch, commit [ec56ac4](https://github.com/symless/synergy/tree/ec56ac4485ef8e3cf986107b8456949b5aec3527))

### Steps to reproduce bug ###

1. Build synergy (`./hm.sh conf -g1 && ./hm.sh build`)
2. Package synergy as RPM (`./hm.sh package rpm`)
3. Try to install the created RPM on a Fedora 25 system (`sudo rpm -i synergy-master-stable-ec56ac4-Linux-x86_64.rpm`)

### Other info ###

Error Message:
```
error: Failed dependencies:
	libcrypto.so.1.0.0()(64bit) is needed by synergy-1.8.8-1.x86_64
	libcrypto.so.1.0.0(OPENSSL_1.0.0)(64bit) is needed by synergy-1.8.8-1.x86_64
	libcurl.so.4(CURL_OPENSSL_3)(64bit) is needed by synergy-1.8.8-1.x86_64
	libssl.so.1.0.0()(64bit) is needed by synergy-1.8.8-1.x86_64
	libssl.so.1.0.0(OPENSSL_1.0.0)(64bit) is needed by synergy-1.8.8-1.x86_64
```

Libaries are available (at least as newer versions):
```
$ ls /usr/lib64/libcrypto*
lrwxrwxrwx. 1 root root   19 Feb  6 17:04 /usr/lib64/libcrypto.so -> libcrypto.so.1.0.2k
lrwxrwxrwx. 1 root root   19 Feb  6 17:04 /usr/lib64/libcrypto.so.10 -> libcrypto.so.1.0.2k
lrwxrwxrwx. 1 root root   30 Mar 12 01:00 /usr/lib64/libcrypto.so.1.0.0 -> /usr/lib64/libcrypto.so.1.0.2k
-rwxr-xr-x. 1 root root 2.4M Feb  6 17:04 /usr/lib64/libcrypto.so.1.0.2k

$ ls /usr/lib64/libssl*
-rwxr-xr-x. 1 root root 308K Feb 22 13:53 /usr/lib64/libssl3.so
lrwxrwxrwx. 1 root root   16 Feb  6 17:04 /usr/lib64/libssl.so -> libssl.so.1.0.2k
lrwxrwxrwx. 1 root root   16 Feb  6 17:04 /usr/lib64/libssl.so.10 -> libssl.so.1.0.2k
-rwxr-xr-x. 1 root root 460K Feb  6 17:04 /usr/lib64/libssl.so.1.0.2k

$ ls /usr/lib64/libcurl*
lrwxrwxrwx. 1 root root   16 Dec 23 11:10 /usr/lib64/libcurl.so.4 -> libcurl.so.4.4.0
-rwxr-xr-x. 1 root root 513K Dec 23 11:10 /usr/lib64/libcurl.so.4.4.0
```

Possibly related with #5491

**Comment by yupi2** [comment] 2017-03-12 02:39
if you do have the openssl and libcurl libraries installed on the computer you're trying to install the rpm on then it could be because `libssl.so.1.0.0` doesn't exist (try symlinking it)

also you could try branch v1.9 but you'll have to do [rpm stuff manually](https://github.com/symless/synergy/blob/master/ext/toolchain/commands1.py#L1088) along with needing qt5-devel
```
mkdir build ; cd build
cmake -DCMAKE_BUILD_TYPE=Release ../
cmake --build ./ -- -j$(nproc)
```

**Comment by DerEnderKeks** [comment] 2017-03-13 19:09
Doesn't work with branch v1.9 either. Even with symlinked libraries.

**Comment by XinyuHou** [comment] 2017-03-15 15:11
Duplicate of #5491

**Closed by XinyuHou** 2017-03-15 15:11 UTC

**Comment by wolvyreen** [comment] 2017-04-04 12:23
grrr!  when will this be fixed!  its so annoying that I can't install the app....sym links are not working for me.  tried the master  build, and 1.8.8.  no joy.
