### ISSUE TITLE
Server's mouse/keyboard stuck after moving mouse to client area while on Windows lock screen on server

### ISSUE THREAD

**Issue by azizLIGHT** [symless/synergy#5854] opened 2017-02-21 20:59 UTC
### Operating Systems ###

Server: Windows 7 x64 (Version 6.1 Build 7601: Service Pack 1)
Client: Windows 8.1 x86 (Version 6.3 Build 9600)
### Synergy Version ###

1.8.7-stable-9799e96
on both server and client

### Steps to reproduce bug ###

1) on Server, lock the screen with Win+L
2) move mouse to where client is (for me: left of primary display)
3) try to move mouse back to server 

### Other info ###

If server is on Windows Lock screen, and mouse is moved to client at that time, then the mouse/keyboard become partially unresponsive on both server and client.

Mouse becomes locked to top left on client and is unable to move properly within client screen: 1) Mouse on client responds to vertical movement momentarily but returns back to top left corner 2) It responds to right/left click events, but is useless because you only get to left/right click the top leftmost pixel on client screen.

After moving the mouse to client, keyboard is also on client, but is able to perform normally: wherever the client's keyboard focus is, is where typing can be done with the server's keyboard input device.

Since the mouse cannot be moved on client at this point, there is no way to move the mouse to server side and control the server, besides disconnecting the client from the network. This causes the mouse/keyboard to return back to the server.

This issue also occurs when a screensaver with option to lock screen is enabled on the server, and after the screensaver is woken and while on lock screen the server's mouse is moved offscreen to client area.

**Comment by QuAzI** [comment] 2017-02-25 22:49
Looks like #5768

**Comment by XinyuHou** [comment] 2017-03-01 12:12
Duplicate of #5772

**Closed by XinyuHou** 2017-03-01 12:12 UTC
