### ISSUE TITLE
Auto config on Thunderbolt reports incorrect IP address to client

### ISSUE THREAD

**Issue by drewwells** [symless/synergy#5846] opened 2017-02-14 17:47 UTC
### Operating Systems ###

Server: Mac OS X Sierra 
Client: Mac OS X Sierra USB-C <-> TB2 adapter

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

1. Connect Thunderbolt
2. Wait for computers to self-assign IP addresses (this requires restarting server if it was running prior to connection)
3. Once server Starts, two IP addresses are shown ethernet/wifi and the thunderbolt network bridge address
4. Go to Client, click Auto Config
5. See successful message on Server: 
```
NOTE: accepted client connection
NOTE: client "dummbar" has connected
```
6. Read log on Client, it reports connecting to Server's Ethernet address which is impossible
```
NOTE: connecting to 'ipv4': ipv4:24800
```
### Other info ###

* When did the problem start to occur? Immediately upon attempting auto config by the client.
* Is there a way to work around it? Yes, manually enter the IP address to the server on the client
* Does this bug prevent you from using Synergy entirely? No

**Comment by SamRimmer** [comment] 2017-02-15 15:46
This is most likely caused by the Thunderbolt adapters using an IP range that isn't prioritised by Synergy.
As you said, the workaround is to just enter the address manually.

**Comment by drewwells** [comment] 2017-02-15 15:52
It's possible that is the cause. Maybe a better workaround is to configure the OS to choose IP addresses in a different IP range or set a static one? Even with manual IP addresses, the connection drops a lot making the host computer unusable for 10-30seconds. The flakiness is surprisingly for a direct wired connection.

**Comment by SamRimmer** [comment] 2017-02-16 15:50
Do you get drops running a ping between the two machines? Or is it only Synergy that gives you issues?

**Comment by drewwells** [comment] 2017-02-16 20:08
Back on the TB2-3 IP address thing, manually set static IP addresses: 
Server 20.20.20.20
Client 20.10.20.10 :

1. I started the server without being connected to WiFi/Ethernet 
2. Alert box pops up on server start "Failed to get local IP address. Please manually type in server address on your clients". This doesn't prevent the server from starting. 
3. Client auto-config contacts the server, but Auto-Config from the server fails. Client receives some ACK from the server and then attempts to connect to its own IP address which is weird.

I'll try the Ping trick. So far no drops today though :)

**Comment by XinyuHou** [comment] 2017-03-01 11:41
Duplicate of #4251

**Closed by XinyuHou** 2017-03-01 11:41 UTC
