### ISSUE TITLE
Windwos 10 to Windows 10 language type issue

### ISSUE THREAD

**Issue by AlexanderVladimirov9090** [symless/synergy#6149] opened 2017-09-13 11:47 UTC
### Windows 10 ###

On Windows 10 to Windows 10 machine. When trying to type on client machine with different language set on it, it immediately change it to default language. When on server and client side are change to the same language it just outputs  ????????? characters. For Windows to Linux it does not have any problem, just on Windows to Windows.

### Synergy Version ###

1.8.9-stable-25a8cd2
This is the version used.

### Steps to reproduce bug ###
The bug is simple to recreate.

Bug1 immediately change to default language input:
1. Change language input on the Client but not on the Server.
2. Type things.
3. It immediately change back to default language input on the Client side.

Bug2 Outputs ???? when input languages in server and client is changed to other besides default input. 
1. Change language input on the Server and Client side.
2. Type things.
3. outputs ????? characters .

### Other info ###

* When did the problem start to occur?
* Is there a way to work around it? - I think that you have to look in to windows encoding of the characters and make it a special case or something like that. 
* Does this bug prevent you from using Synergy entirely?-This bug is bad user experience. Sometimes I have to work on to same OS on different machines. 

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.
Overall this application is super effective and easy to use.

**Comment by XinyuHou** [comment] 2017-09-13 15:20
Duplicate of #5395 and #4309

**Closed by XinyuHou** 2017-09-13 15:20 UTC
