### ISSUE TITLE
Tab mismatched to shift tab

### ISSUE THREAD

**Issue by oujinliang** [symless/synergy#5373] opened 2016-06-13 12:33 UTC
Version: 1.8.3-beta

Server: Mac OS X, 10.11
Client: Ubuntu, 16.04 LTS
Logged in: YES

Problem: after mouse moved to the client machine, open any editor, press TAB key, it behaves like "Shift TAB"

Here is the log from server side and client side:

Server:
```
DEBUG1: onKeyDown id=61193 mask=0x0001 button=0x0031
DEBUG1: send key down to "oujinliang-OptiPlex-7040" id=61193, mask=0x0001, button=0x0031
DEBUG1: event: Key event kind: 11, keycode=48
DEBUG1: new mask: 0x0001
DEBUG1: onKeyUp id=0 mask=0x0001 button=0x0031
DEBUG1: send key up to "oujinliang-OptiPlex-7040" id=0, mask=0x0001, button=0x0031
DEBUG1: event: Key event kind: 10, keycode=48
DEBUG1: new mask: 0x0001
```

Client

```
DEBUG1: recv key down id=0x0000ef09, mask=0x0000, button=0x0031
DEBUG1: mapKey ef09 (61193) with mask 0000, start state: 0000
DEBUG1: find best:  0000 0000
DEBUG1: best key index 2 of 2 (exact)
DEBUG1: found key in group 0
DEBUG1: state: 0000,0001,0001
DEBUG1: flip: 0001 (0000 vs 0001 in 0001 - 0000)
DEBUG1: desired state: 0000 0001,0001,0001
DEBUG1: flip: 0000 (0001 vs 0000 in fffe - 6020)
DEBUG1: mapped to 017, new state 0000
DEBUG1: keystrokes:
DEBUG1:   032 (00000000) down
DEBUG1:   017 (00000000) down
DEBUG1:   032 (00000000) up
DEBUG1: recv key up id=0x00000000, mask=0x0000, button=0x0031
DEBUG1: keystrokes:
DEBUG1:   017 (00000000) up
```

**Comment by nlyan** [comment] 2016-06-14 10:07
I can't see anything wrong in this log. Can you please give details of your keyboard configuration under both Ubuntu and Mac OS X's UI, your keyboard model number, as well as the output of the following command (on Ubuntu)

`setxkbmap -query`

**Comment by bcbomb47** [comment] 2016-06-14 16:47
I am having the same issue running version: 1.8.3-beta
Server: Mac OS X, 10.11.5
Client: Windows 10 64bit

I am using a wired Apple Keyboard on my Macbook Pro.

**Comment by alexwhitman** [comment] 2016-06-21 08:51
Same issue for me.

Synergy version 1.8.3-beta

Server: Ubuntu 16.04 64bit
Client: Windows 10 64bit

**Comment by mf-lit** [comment] 2016-06-21 12:45
Same here.

Synergy version 1.8.3-beta
Server: Ubuntu 16.04 64bit
Client: Ubuntu 16.04 64bit

**Comment by XinyuHou** [comment] 2016-06-27 12:18
Master - Dual Boot (Linux Mint 17.3 & Windows 10)
Slave - Windows 10

Works under 1.8.1-beta-b25ed99 but fails under 1.8.3-beta-723a8a9. Issue appears when running putty on slave. Occurs when attempting to change directory using tab completion or when attempting to insert tab into text document using nano. Nano reports 'Unknown Command'

Possibly related to #5373 ??

**Comment by XinyuHou** [comment] 2016-06-27 12:18
Same here.

Synergy version 1.8.3-beta
Server: Ubuntu 16.04 64bit
Client: Ubuntu 16.04 64bit

**Comment by mkeydevelop** [comment] 2016-06-29 07:16
revert commit 3de98a2 will fix this problem,
I think everybody will happy except MAC and it's space bar.

In addition, because of this, press character key also blink client's physical keyboard's
Caps Lock led.

**Comment by xPathin** [comment] 2016-07-05 04:41
Same issue with arch server and win10 client...

**Comment by XinyuHou** [comment] 2016-07-18 16:03
> I'm running Synergy 1.8.2-beta-8da57cd on Ubuntu 16.04
> 
> When pressing the backspace key on the server, the client has this in the logs:
> 
> [2016-07-12T13:22:42] DEBUG1: recv key down id=0x0000ef08, mask=0x0000, button=0x0016
> [2016-07-12T13:22:42] DEBUG1: mapKey ef08 (61192) with mask 0000, start state: 2000
> [2016-07-12T13:22:42] DEBUG1: find best:  2000 0000
> [2016-07-12T13:22:42] DEBUG1: best key index 2 of 2 (exact)
> [2016-07-12T13:22:42] DEBUG1: found key in group 0
> [2016-07-12T13:22:42] DEBUG1: state: 2000,0001,0001
> [2016-07-12T13:22:42] DEBUG1: flip: 0001 (2000 vs 0001 in 0001 - 0000)
> [2016-07-12T13:22:42] DEBUG1: modifier 0001 modified by 0004
> [2016-07-12T13:22:42] DEBUG1: unable to match modifier state (0001,0001) for key 22
> [2016-07-12T13:22:42] DEBUG1: can't map key
> [2016-07-12T13:22:42] DEBUG1: recv key up id=0x0000ef08, mask=0x0000, button=0x0016
> and the backspace key is not sent to the application on the client.
> 
> The following may be related:
> The client is using a bi-lingual keyboard setup with two keyboard layouts - this is what setxkbmap -print shows:
> 
> xkb_keymap {
>         xkb_keycodes  { include "evdev+aliases(qwerty)" };
>         xkb_types     { include "complete"      };
>         xkb_compat    { include "complete"      };
>         xkb_symbols   { include "pc+us+il(lyx):2+inet(evdev)+group(alt_shift_toggle)"   };
>         xkb_geometry  { include "pc(pc101)"     };
> };
> while the server is using a standard us layout.

**Comment by XinyuHou** [comment] 2016-07-18 16:03
> On the remote client machine, when attempting to tab, the keystroke is recognized as shift+tab. Version 1.8.2-beta-7d0cb34, Debian 8 on both machines.
> 
> Output from logs:
> 
> [2016-07-12T11:54:39] DEBUG2: want to read, error=2, attempt=1
> [2016-07-12T11:54:39] DEBUG2: msg from server: DKDN
> [2016-07-12T11:54:39] DEBUG2: readf(%2i%2i%2i)
> [2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 61193 (0xef09)
> [2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 0 (0x0)
> [2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 23 (0x17)
> [2016-07-12T11:54:39] DEBUG1: recv key down id=0x0000ef09, mask=0x0000, button=0x0017
> [2016-07-12T11:54:39] DEBUG1: mapKey ef09 (61193) with mask 0000, start state: 0000
> [2016-07-12T11:54:39] DEBUG1: find best: 0000 0000
> [2016-07-12T11:54:39] DEBUG1: best key index 2 of 2 (exact)
> [2016-07-12T11:54:39] DEBUG1: found key in group 0
> [2016-07-12T11:54:39] DEBUG1: state: 0000,0001,0001
> [2016-07-12T11:54:39] DEBUG1: flip: 0001 (0000 vs 0001 in 0001 - 0000)
> [2016-07-12T11:54:39] DEBUG1: desired state: 0000 0001,0001,0001
> [2016-07-12T11:54:39] DEBUG1: flip: 0000 (0001 vs 0000 in fffe - 6020)
> [2016-07-12T11:54:39] DEBUG1: mapped to 017, new state 0000
> [2016-07-12T11:54:39] DEBUG1: keystrokes:
> [2016-07-12T11:54:39] DEBUG1: 032 (00000000) down
> [2016-07-12T11:54:39] DEBUG1: 017 (00000000) down
> [2016-07-12T11:54:39] DEBUG1: 032 (00000000) up
> [2016-07-12T11:54:39] DEBUG2: writef(CNOP)
> [2016-07-12T11:54:39] DEBUG2: wrote 4 bytes

**Comment by XinyuHou** [comment] 2016-08-11 16:30
Guys, could you test this nightly please?
http://symless.com/nightly?filter=issue2765-spacebar-issue-beta-b57e8ad

Note: we backed out the immature fix from v1.8.2-stable which would introduce more problems than it solved. So please be aware v1.8.2 won't fix this issue.

**Closed** 2016-08-15 09:58 UTC
Labels: bug, sprint-should

**Comment by LeadManPL** [comment] 2016-08-23 08:55
SRV: synergy-v1.8.3-rc1-e36a7ae-Linux-x86_64
CLN: synergy-v1.8.3-rc1-e36a7ae-Windows-x64

PASSED. Client behaves as described in steps to reproduce.

**Comment by LeadManPL** [comment] 2016-09-22 10:52
Retested bug with RC2 for regressions:

SRV: synergy-v1.8.3-rc2-89c9c58-Linux-x86_64
CLN: synergy-v1.8.3-rc2-89c9c58-Windows-x64

Issue #5373
1. Connect a Linux or a Windows client to any server
2. Open the Synergy GUI on your client
3. Double click anywhere in the 'Log' field
4. Press Tab key
5. Confirm the focus changes to 'Apply'
6. Press Shift + Tab keys
7. Confirm the focus is going back to 'Log' field

PASSED. Client behaves as described in steps to reproduce.
