### ISSUE TITLE
weird behavior with multiple screens setup (#5489 reopen)

### ISSUE THREAD

**Issue by FSLMobile** [symless/synergy#5570] opened 2016-08-29 15:10 UTC
Don't know how to reopen a closed one, so adding information here : 

[synergyd.txt](https://github.com/symless/synergy/files/442682/synergyd.txt)
![surface-macpro](https://cloud.githubusercontent.com/assets/3227495/18056191/372306e8-6e0b-11e6-89f5-9b7ac20ea4c8.png)
![macpro-surface](https://cloud.githubusercontent.com/assets/3227495/18056192/37282e3e-6e0b-11e6-8a1a-3bf244e34ffa.png)

First email:
---------------------------------------------------
My setup is 
Windows 10 (surface book with 3 screens) (named PC0 below)
OSx 10.10 (Macbook pro with 2 screens) (named PC1)

I can switch only from main screen to main screen:

PC0-0 PC0-1 PC0-2 / PC1-0 PC1-1 -> Not working (mouse never go from PC0-2 to PC1-0).
PC1-1 PC1-0 / PC0-0 PC0-1 PC0-2 -> Working (mouse is going fine from PC1-0 to PC0-0).

As long as the main screens are along, this is working. As soon as they are not, the mouse is stucked on the latest screen (PC0-2 in my case).

In both case, setup is working fine and client and server discover and connect without trouble.

It was working fine with previous released version.

From @XinyuHou  
----------------------------------------------------------------
@FSLMobile 
What version of Synergy are you using?

Could you send us some logging by using gist?

Answer
----------------------------------------------------------------
The last version I tested is the last one (1.83 rc1), The problem is still there.

Attached is log from the program folder.

The setup is this one :

In Synergy configuration, the system is defined as
Surface / MacPro (see picture)

On each computer, I have 2 or 3 screens (2 in current setup).

Surface screen1 / Surface screen2 / MacPro Screen2 /MacPro Screen1

Surface is Server

In this config, the mouse get stuck between Surface screen2 and cannot go to MacPro Screen2

If I just change the synergy config, moving the Macfred computer to the left:
MacPro/Surface (see picture)

The PC remains server

The config is working fine but my mac is supposed to be at the left of the pc where it's not...

Let me know if there is anything else I can do to help.

Cheers,

**Comment by XinyuHou** [comment] 2016-08-30 15:33
Reopened the original issue.

**Comment by XinyuHou** [comment] 2016-08-30 15:33
Duplicate of #5489

**Closed by XinyuHou** 2016-08-30 15:33 UTC
