### ISSUE TITLE
Different resolution with high DPI used causes cursor stuck on client

### ISSUE THREAD

**Issue by kusuriya** [symless/synergy#5186] opened 2016-01-17 17:06 UTC
It appears to happen in all of the 1.7 branch with win 10. I have two monitors connected to the server a 1920x1080 and a 2880x1620 running win10, the client has a single 1600x900 display running archlinux, they are configured with the 1600x900 display being to the right of the 2880x1620 display. If I move off of the 2880x1620 display onto the 1600x900 display the mouse gets stuck there, when I try to come back it briefly enters the screen and then exits back to the client. The logs even on debug two tell me that it is entering and exiting, and the server says that there is no screen found below my client at 0,892

As a note if I move the client to the edge of the 1920x1080 screen it works without a problem, and it also works fine if I turn the res on the HIDPI monitor down to 1920x1080.

Logs:
[server.txt](https://github.com/synergy/synergy/files/93511/server.txt)
[client.txt](https://github.com/synergy/synergy/files/93512/client.txt)

**Comment by daemeh** [comment] 2016-02-15 17:50
Same issue here. I'm using a Windows 10 server with a 4k display, to which I'm connecting a Macbook Pro Retina with an additional external 1920x1200 display. When the server is at 4k resolution(with 175% apps scaling), the mouse cursor will get stuck in the lower-right corner of the client when moving to it. If I switch the server PC to 1920x1080 resolution(with 100% app scaling), then the problem disappears. Of course, I'd like to use the 4k display with app scaling, as everything looks blurry when using the 1920x1080 resolution.

**Comment by the-wes** [comment] 2016-02-19 23:40
to everyone who is experiencing this: what version of synergy are you running?

**Comment by kusuriya** [comment] 2016-02-23 16:35
Doesnt matter really any of the 1.6 - 1.7 branches take your pick. Im all the way up to latest stable but I can step back all the way to 1.6.0 I havent tried older than that.

**Comment by daemeh** [comment] 2016-02-25 12:45
I'm using the latest stable v1.7.6 on both machines.

**Comment by kusuriya** [comment] 2016-02-25 23:32
Oh and the work around for my self, funny enough, is move who has the keyboard and mouse to the non hi-dpi screen

**Comment by XinyuHou** [comment] 2016-04-11 11:04
#5222
@Craz3Coyote thinks this is related to certain programs

**Comment by kamakazikamikaze** [comment] 2016-05-09 03:41
Same issue here. Maybe I need to rearrange my monitors.

Retina MacBook Pro is on the left. The PC has three monitors to the right of it. In order, from left to right, the total four screens are:

1920 x 1200 (HiDPI) |  3840 x 2160 | 2560 x 1400 | 2560 x 1400

If I set the server on the PC, either the mouse will "bounce" back to the PC when trying to cross borders (each try shifts it back a few hundred pixels) or the mouse gets stuck in the bottom-right corner of the MacBook Pro screen. If I set the server on the Mac, both devices claim that an SSL connection was successful but they both retain control of their own mouse.

**Comment by brminnick** [comment] 2016-07-08 16:01
I had a similar issue and found the fix here:

**Comment by kusuriya** [comment] 2016-07-08 16:14
https://github.com/symless/synergy/issues/4041 for people that dont want to dig for it. It is an interesting work around but honestly having the root cause of it fixed I think would be better, or at least detection for it.

**Comment by kamakazikamikaze** [comment] 2016-07-12 21:01
@kusuriya I can confirm that the workaround does resolve the issue. This is just another Windows "feature" to add onto my "why I hate Windows" list

**Comment by chevex** [comment] 2016-09-11 17:27
I started using a feature of my nvidia driver called DSR (Dynamic Super Resolution). It renders video at a higher resolution and then compresses it back down to native monitor resolution. Older games like World of Warcraft look superb this way and allows you to turn anti-aliasing completely off. Game looks better and I get higher FPS out of it. I'm on Windows 10 anniversary update btw.

With synergy running I have this exact same issue. My desktop renders at native resolution so if I'm on the desktop synergy works fine, but the minute I go into WoW while using 4k DSR resolution in the game my mouse will get stuck on the client (macbook pro) and the cursor doesn't render though I can see I'm mousing over some things on the client. Only way to fix this is to disable synergy on the client and then things return to normal on the PC.

I tested using 4k DSR for my normal desktop resolution as well thinking it might be the fact that only one game is using it and not the whole desktop. As soon as I did that synergy stopped working out of game as well. Same side effects. Take mouse to edge of screen and boom, stuck on client again. Not sure what to do. For now I'm just not using synergy while I play WoW because the benefits of DSR on my GPU performance seem to be absolutely superb.

**Comment by nlyan** [comment] 2016-09-12 11:02
I'll be pushing for this to be fixed in v1.8.4

**Comment by nlyan** [comment] 2016-10-07 13:23
Can anyone experiencing this issue please try 1.8.4 RC3?

http://symless.com/nightly?filter=synergy-v1.8.4-rc3

**Comment by matonmacs** [comment] 2016-10-25 16:35
I'm still having this problem with 1.8.4 stable. Server: Win 10 (Anniv) w/ 4k monitor; Client: Mac 10.11.6 MacBook Pro internal display + external 1440p display. I tried the workaround mentioned above (disabling display scaling on the Windows server), but it did not seem to affect the problem on my machines. When switching to the Mac client the cursor is still pinned to the bottom right of the screen (keyboard works fine).

**Comment by XinyuHou** [comment] 2016-10-28 13:45
Can anyone test this nightly please?
http://symless.com/nightly?filter=issue5186-different-dpi-rc1-8d193c7

**Closed by XinyuHou** 2016-10-28 13:45 UTC
Labels: bug, sprint-must

**Comment by Kapps** [comment] 2016-10-30 22:01
No luck with 'synergy-issue5186-different-dpi-rc1-8d193c7-Windows-x64.msi'

````
[2016-10-30T15:58:53] INFO: using last known command: "C:/Program Files/Synergy/synergys.exe" -f --no-tray --debug INFO --name DESKTOP-85R6CM8 --ipc --stop-on-desk-switch --enable-drag-drop --profile-dir "C:\Users\opant\AppData\Local" -c "C:/Users/opant/AppData/Local/Temp/qt_temp.Hp4784" --address :24800 --res-w 2560 --res-h 1440 --prm-wc 1280 --prm-hc 720

[2016-10-30T15:58:53] INFO: service command updated
[2016-10-30T15:58:53] INFO: starting new process
[2016-10-30T15:58:53] INFO: activeDesktop:Default
[2016-10-30T15:58:54] INFO: starting new process
synergys.exe: unrecognized option `--res-w'
Try `synergys.exe --help' for more information.

[2016-10-30T15:58:55] ERROR: failed to launch, error: process immediately stopped
[2016-10-30T15:58:55] INFO: backing off, wait=2s, failures=1
[2016-10-30T15:58:56] INFO: watchdog status: error
[2016-10-30T15:58:57] INFO: starting new process
[2016-10-30T15:58:57] INFO: activeDesktop:Default
[2016-10-30T15:58:57] INFO: starting new process
synergys.exe: unrecognized option `--res-w'
Try `synergys.exe --help' for more information.
````

**Comment by XinyuHou** [comment] 2016-10-31 16:28
@Kapps 
Thanks for the feedback. We will remember to handle the parameters as deprecated ones before we release.

**Comment by bsmedberg** [comment] 2016-11-03 13:55
To test this do I need to install both the client and server version, or just a new server? The different-dpi test build doesn't come in Linux x64 RPM.

**Comment by XinyuHou** [comment] 2016-11-08 11:31
@bsmedberg 
Sorry for the late reply. This nightly has fixes for Windows server with high DPI scaling enabled. So you only need to update on your Windows server side. Thanks

**Comment by bsmedberg** [comment] 2016-11-09 17:41
I can verify that the different-dpi-rc1 test build fixes my issues with a windows host. Using it now and looking forward to 1.8.6!

**Comment by pbrianmackey** [comment] 2016-11-15 02:01
What is generally the most stable nightly option?  In this case, 1.8.6-stable or 1.8.6-rcI?

**Comment by PhRX** [comment] 2016-12-22 07:55
#5201 got closed as a duplicate of this issue, but I don't quite see how, as it describes much more accurately what I'm seeing than this issue (my cursor doesn't get stuck). So I'll post my comment here as well : 

This seems still broken in 1.8.6. Setup : laptop runs Win10, with High-DPI screen (3840x2160) [S1], with second monitor (1920x1080) [S2] to the right. Second is set as Main. Laptop runs synergy 1.8.6 as client.
Desktop runs linux, also 2 monitors (1600x1200 left, main [S3]; 1920 x 1080 right [S4]). Runs synergy 1.8.6 as server. Laptop screen is set to left of desktop screen.
so, it looks like : S1 - S2 - S3 - S4

I get the "looping" effect : start cursor on S3, move to S2 then S1. About 30% in S1 the cursor jumps again to the right of S2, continue moving to left then traverses S2 and S1 "normally". Jump/loop also occurs in exact reverse when moving cursor to the right again.
Still broken in 1.8.6. Setup : laptop runs Win10, with High-DPI screen (3840x2160) [S1], with second monitor (1920x1080) [S2] to the right. Second is set as Main. Laptop runs synergy 1.8.6 as client.
Desktop runs linux, also 2 monitors (1600x1200 left, main [S3]; 1920 x 1080 right [S4]). Runs synergy 1.8.6 as server. Laptop screen is set to left of desktop screen.
so, it looks like : S1 - S2 - S3 - S4

I get the "looping" effect : start cursor on S3, move to S2 then S1. About 30% in S1 the cursor jumps again to the right of S2, continue moving to left then traverses S2 and S1 "normally". Jump/loop also occurs in exact reverse when moving cursor to the right again.

**Comment by birdman7260** [comment] 2016-12-24 05:34
I agree with @PhRX , there is another issue around multiple monitors that have different scaling. I wrote #5547 detailing my experience. What it boils down to is:

1. Client is Windows
2. Client has two monitors
3. Set the monitors to have different scaling (set one to 100% and the other to 125%)
4. Move cursor across these two monitors and notice how the cursor "loops".

The width of the loop is directly related to the difference in the scaling.
My personal monitors are: Client [4k and 1440] - Server [1440]
The issue is seen whether I set the resolution to be the same across monitors or not (i.e. it's the scaling that is the issue).

Please let me know if there is anything you'd like me to test to get you more information, I'm really looking forward to getting this particular bug fixed :)

**Comment by llavalle** [comment] 2017-04-03 19:55
I have the same issue as @birdman7260 .  Running 1.8.8 stable right now and having the problem when the client has 2 monitors with different scaling.

Getting cursor loop.  This issue isn't fixed.

**Comment by giammin** [comment] 2017-04-27 08:10
> Getting cursor loop. This issue isn't fixed.

confirm

**Comment by mtvcp** [comment] 2018-06-11 15:24
I am running 1.9.0-rc3 and have this issue. I think windows update 1803 caused this to be a problem again.
