### ISSUE TITLE
Clipboard buffer doesn't work for Linux in 1.8.4

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5715] opened 2016-10-30 21:39 UTC
### Operating Systems

Client: Linux Mint 17.3

Server: Linux Mint 17.3
### Synergy Version

1.8.4-stable-a6ff907 on both sides
### Steps to reproduce bug

Copy/paste doesn't work. Absolutely. Clipboard empty always after copying.

**Comment by nlyan** [comment] 2016-10-31 12:58
Are you by any chance using a virtual machine?

**Comment by QuAzI** [comment] 2016-10-31 13:00
No. Physical machines only.
PC at the server side and notebook at the client side.

**Comment by nlyan** [comment] 2016-10-31 13:04
Can you still copy and paste locally on the server when Synergy is connected to your notebook?

**Comment by QuAzI** [comment] 2016-10-31 13:10
Yes. Local buffer works. But remote buffer cleaned after Ctrl+C or
Ctrl+Insert

Best regards,
Ruslan Yakauleu

**Comment by nlyan** [comment] 2016-10-31 14:24
Could you set both client and server to DEBUG1 and provide us with the logs of a new session where this presents?

**Comment by XinyuHou** [comment] 2016-12-05 12:20
Closed because of insufficient information.

**Comment by QuAzI** [comment] 2016-12-11 11:48
On Mint I use Firefox. For test I try 
1) copy link through "copy link" dialog - buffer empty, "Paste" menu field disabled.
2) copy text from web page through Ctrl+C  - buffer empty, "Paste" menu field disabled.
3) copy page URL from URL edit through Ctrl+Insert - Trash copied (#5659)

Logs attached.

[synergy-mint17.log.txt](https://github.com/symless/synergy/files/644397/synergy-mint17.log.txt)
[synergy-win7.log.txt](https://github.com/symless/synergy/files/644398/synergy-win7.log.txt)

**Comment by XinyuHou** [comment] 2016-12-30 13:25
Duplicate of #5729

**Closed by XinyuHou** 2016-12-30 13:25 UTC
