### ISSUE TITLE
Entering client switches keyboard layout on Windows server

### ISSUE THREAD

**Issue by xhpohanka** [symless/synergy#5530] opened 2016-08-10 07:01 UTC
I found a strange issue. I have Windows 10 server and client with Arch Linux (Cinnamon DE). When windows command line (`c:\Windows\System32\cmd.exe`) is running and in top then entering client screen switches keyboard layout on server (from English to Czech and vice versa in my case)

**Comment by nlyan** [comment] 2016-08-15 16:12
Can you give us precise instructions on how to reproduce this issue?

**Comment by xhpohanka** [comment] 2016-08-17 06:59
**Server configuration**
Synergy 1.8.2, Windows 10, Czech Language pack, English (US) and Czech (QWERTY) layout defined

**Client configuration**
Synergy 1.8.2, Arch Linux, Cinnamon 3.0.7, English (US) and Czech (QWERTY) layout defined

Now when I run `c:\Windows\System32\cmd.exe` (eg. by Win+R) and keep it focused I can see that keyboard layout icon on _server_ toggle when I move cursor into client screen.

I'm seeing this behavior for a long time also with 1.7 synergy versions, windows 8 and earlier arch versions...

**Comment by Link-Satonaka** [comment] 2017-06-23 02:03
I have this issue too, simply W10 pro on both client and server.

Driving me insane. In order to get the desired layout on the client, I sometimes have to flip between client/server upwards of 6 times before it settles on the right layout on the client.

**Comment by alexteves** [comment] 2017-06-23 10:10
Only happens with bash/cmd prompt in focus, notepad/browser don't trigger this behavior.
Only have one input language, this toggles me between that and the EN-US one.

**Server**: Windows 10 (v1703 Creator's Update)
**Client**: macOS 10.12.5
**Synergy**: 1.8.8-stable-25a8cb2 on both

**Comment by heeen** [comment] 2017-07-27 14:27
I have the same issue on Windows 10, German layout, client Ubuntu 16.04 also German layout.
It also happens with the linux subsystem ("ubuntu/bash on windows") window.
I even tried deleting the Eng layout from my windows machine altogether but it still comes back.

easily reproducible and has been happening as early as 1.6.7 if I remember correctly.

Server: win10, 1.8.8
Client: ubuntu 16.04 1.8.8

**Comment by jpnurmi** [comment] 2017-09-15 07:45
Same problem. It seems that turning on the `Don't take foreground window on Windows servers` setting in `Configure Server...` => `Advanced server settings` prevents the spurious keyboard layout switch, but according to the [FAQ](https://github.com/symless/synergy-core/wiki/User-FAQ#How_do_I_stop_my_game_from_minimizing_when_I_leave_the_screen) it's not really an optimal solution either.

> If you turn this on then be aware that Synergy may not function correctly when certain programs, particularly the command prompt, are the foreground when you switch to other screens. Simply make a different program the foreground before switching to work around that.

**Comment by XinyuHou** [comment] 2017-11-23 12:39
> Operating Systems
> 
> Server: Windows 10 Pro (Personal notebook)
> Client: Windows 10 Pro (Work desktop)
> 
> *Same keyboard, language and country set up
> 
> Synergy Version
> 
> 1.8.8
> 
> Steps to reproduce bug
> 
> Turn on cmd on server side
> Mouse navigate from client side to server side screen
> The keyboard input language switch in auto (not the current input)
> For me, it is English-US keyboard (HKSAR) switch to Chinese- Microsoft Quick(HKSAR)
> or
> Chinese- Microsoft Quick(HKSAR) switch back to English-US keyboard (HKSAR)
> Other info
> 
> Impact: It makes me typing Chinese when I wanna type command lines. I just want the server side with cmd opened, even when I back to server screen, my keyboard remain US keyboard as always.
> 
> When started: not sure until recently check out why the issue happened
> 
> Cover: seems only cmd.exe will cause the issue
> 
> Wild guess: although they are both Windows 10, underlying a bit different.
> Especially on cmd code page, client side is using "850 oem multilingual latin i" in default while server side uses "950 (ansi/oem - traditional chinese big5)". Not sure the single byte and double bite things related.
> 
> Is there a way to work around it: keep switch keyboard with shortcut...
> 
> Does this bug prevent you from using Synergy entirely: No, but very annoying for the language switch
> 
> Server side log: https://gist.github.com/marco-globalluxe/f846076e6424d76d2804ee3820f2d633
> Client side side: https://gist.github.com/marco-globalluxe/28c0493d63b7b036d5362cde45e025a1

**Comment by nbolton** [comment] 2024-09-06 21:30
I'm closing this issue due to limited activity. Please let me know if you want it to be reopened.

**Closed by nbolton** 2024-09-06 21:30 UTC
Labels: bug, triage, unanswered
