### ISSUE TITLE
Ctrl+Zoom makes mouse crazy, uncontrollable, without any way to take control back

### ISSUE THREAD

**Issue by NoICE** [symless/synergy#5849] opened 2017-02-16 16:22 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.3 (16D32)
Client: Windows 10 1607

### Synergy Version ###

1.8.7 on both server and client.

### Steps to reproduce bug ###

1. Enable "Use scroll gesture with modifier keys to zoom" in SysPreferences -> Accessibility -> Zoom, defaults to "^Control"
2. Use Control+Scroll to zoom in on macOS desktop (or Ctrl+two finger scroll on touchpad, Ctrl+one finger scroll on mouse, whatever)
3. Move mouse to the side of the desktop, so it should teleport to the other Synergy clients
4. See the mouse stuck on the side, totally uncontrollable, without any ability to move back to the server. Ctrl is now being sent to the other computer, so you cannot unzoom.

### Other info ###

Only way you can take back control of the mouse is:
* on the Synergy Client (computer where you ended up when the mouse jumped of your zoomed Synergy Server desktop), use your real mouse and keyboard to shutdown Synergy client (if that's the computer which is hosting your keyboard and mouse, you are screwed?) 
* the mouse will jump back to the Synergy Server

* When did the problem start to occur? When I... every time when you zoom and you accidentally move the mouse to the border
* Is there a way to work around it? No/Yes, you can... no
* Does this bug prevent you from using Synergy entirely? no

**Comment by sweetrush** [comment] 2017-02-18 05:43
I have had a similar problem with my setup but i had made a small tweak to my config file to help me switch screen. 

**The following below is my KeyEvents** 

	keystroke(control+F1) = switchToScreen(HC1)
	keystroke(control+F2) = switchToScreen(HC2)
	keystroke(control+F3) = switchToScreen(H4)
	keystroke(control+F4) = switchToScreen(HC5)

HC1,HC2,H4,HC5 are Alias to my computers Yep they are 4 Computers all mapped with Synergy.

**Layout I have** 
# Screen Arrangements 
# [---------]-[--------]-[-------]
# [   HC1   ]-[   HC3  ]-[   HC5 ]
# [---------]-[--------]-[-------]
# [    |    ]-[    |   ]-[    |  ]
# [---------]-[--------]-[-------]
# [   HC1   ]-[   HC2  ]-[  HC2  ]
# [---------]-[--------]-[-------]

I believe this is caused by something to do with either the Kernal Call permission on (Unix/Linux) Systems 
cause my setup is a Windows-Linux type most windows users don't have this problem

**Comment by sweetrush** [comment] 2017-02-18 05:46
You can try that and see it that will work for you.

**Comment by XinyuHou** [comment] 2017-03-01 11:48
@NoICE 
Do you mean with ctrl+zoom, you can move cursor to your clients and everything works as expected?

When you move your cursor over, did you hold the ctrl key?

**Comment by NoICE** [comment] 2017-03-02 11:34
With ctrl+zoom on the server you can move the mouse and everything is ok, but when you move your mouse to any of the clients, it goes haywire. And because you are on the client and not on the server, you can't unzoom.

**Comment by XinyuHou** [comment] 2017-03-08 11:53
Duplicate of #3289

**Closed by XinyuHou** 2017-03-08 11:53 UTC
