### ISSUE TITLE
Mouse position recenter when screen loses focus

### ISSUE THREAD

**Issue by ddnguyen** [symless/synergy#6097] opened 2017-07-07 22:29 UTC
### Operating Systems ###

Server: Windows 10
Client: Windows 10

### Synergy Version ###

1.8.2
 
### Steps to reproduce bug ###

Have a program which uses the absolute position of the mouse cursor for some logic, like in a game.

1) move mouse off screen onto another computer
2) mouse position is reset to center when that screen loses focus
3) this results in the program acting broken it now uses the new re-centered position

### Other info ###

Normally the mouse is hidden on the sleeping screens but its position is reset as well, this causes applications which use the mouse position to act oddly and reset their state as well. Since the mouse is hidden, there is no need imo, to also reset the position of it so applications which depend upon the mouse location do not also inturn fail.

**Comment by XinyuHou** [comment] 2017-07-14 11:38
@ddnguyen 
This behavior is by design. We need to recenter the cursor to calculate the mouse movement on the server.
If you are after a solution that could stop cursor moving to next screen, you can use scroll lock key to lock the cursor to this screen.

**Closed by XinyuHou** 2017-07-14 11:39 UTC
