### ISSUE TITLE
Only meta keys sent to Windows 8 client (Mac server)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3640] opened 2014-10-13 07:19 UTC
**Imported issue:**
- Author: Christian Tucci
- Date: 2013-08-10 01:00:41
- Legacy ID: 3710

**Steps to reproduce:**
1. Connect Windows 8 client to OS X v10.8 server.
2. Move mouse off OS X screen to Windows 8 screen.
3. Click into a text box and type.
4. Text appears on OS X screen, not Windows 8 textbox.

**\* THE ONLY KEYS THAT DO WORK ARE SHIFT, CTRL, ALT, AND COMMAND ***

Expected: Text will type into fields on Windows 8 using keyboard connected to OS X.

Actual: Text does not type into Windows 8 but OS X reacts to buttons being pressed.

**Versions and operating systems:**

Versions tried (issue the same across all)

v1.4.12 (OS X and Windows x64)
v1.4.13 (OS X and Windows x64)

**Temporary workarounds:**

None that I know of...

**Additional comments:**

Using "DEBUG1" level, the log shows no sign that any keys are being transmitted except the Shift, Ctrl, Alt, and Command keys.

**Comment by XinyuHou** [comment] 2017-04-21 13:55
Duplicate of #5203

**Closed by XinyuHou** 2017-04-21 13:55 UTC
Labels: bug
