### ISSUE TITLE
Mouse caught in client when Server enters lock screen

### ISSUE THREAD

**Issue by proforce2k** [symless/synergy#4511] opened 2015-04-08 18:22 UTC
Synergy Server is Windows 8.1, client is Windows 10. If the cursor is left in the Windows 10 screen, and the server sits idle and is left to go into lock screen, when you try and unlock the server, the cursor stays stuck in the client window.

**Comment by ruve1k** [comment] 2016-07-05 18:25
I have the same issue where both server and client are Windows 7. If the cursor (mouse pointer) is on the client, and then the server remains idle causing the lock screen to come up, then the pointer gets stuck on the client screen. When I hit CTRL+ALT+DELETE the login screen on the server shows up (because thankfully at least that is not passed to the client) but all other keyboard entry goes to the wherever the mouse pointer is on the client. so cannot enter my login info on the server. The only option to get out of this mess is to stop the Synergy service on the client. That puts the cursor back on the server. I would like to see the cursor able to move back to the server even when the lock screen is up.

**Comment by XinyuHou** [comment] 2016-11-25 16:45
Duplicate of #5075

**Closed by XinyuHou** 2016-11-25 16:45 UTC
Labels: bug
