### ISSUE TITLE
Starting synergy 4k display issue

### ISSUE THREAD

**Issue by lukesUbuntu** [symless/synergy#5561] opened 2016-08-23 21:13 UTC
When starting synergy on a 4k monitor/screen it starts up in wrong scale.  Tested on several windows 10 64 bit & Elementary 0.3 Frey with same outcome.

Attached screenshot : Synergy 1.8.3

![image](https://cloud.githubusercontent.com/assets/6184757/17910119/a22ccd0e-69db-11e6-9ca3-9e8d53bf578d.png)

Steps to reproduce,
1.. Load up synergy on windows with 4k monitor at 3200 x 1800 resolution

**Comment by XinyuHou** [comment] 2016-08-30 15:21
Duplicate of #5436

**Closed by XinyuHou** 2016-08-30 15:21 UTC
