### ISSUE TITLE
Debian build is not compatible with stretch

### ISSUE THREAD

**Issue by wysman** [symless/synergy#6110] opened 2017-07-21 07:36 UTC
### Operating Systems ###

Server: -
Client: Debian stretch

### Synergy Version ###

1.8.8-stable-25a8cb2
Download from the website with Basic account

### Steps to reproduce bug ###

On Debian stretch (Client)
- run synergy gui
- start in client mode -> crash loop of synergyc

### Other info ###

synergyc is linked with libssl and libcrypto in version 1.0.0, but debian provide version 1.0.2, so initial link of dynamic libs failed. Creating symlink is not a working solution because the binary search explicitly the version 1.0.0.

Debian stretch is available since some weeks now, please update official.

Best regards,

**Comment by XinyuHou** [comment] 2017-07-21 10:47
Duplicate of #4592

**Closed by XinyuHou** 2017-07-21 10:47 UTC
