### ISSUE TITLE
Clipboard problems when using Excel on client

### ISSUE THREAD

**Issue by elierh** [symless/synergy#5947] opened 2017-03-27 23:09 UTC
### Operating Systems ###

Server: Windows 7 Enterprise 6,1
Client: MacOS Sierra 10.12.3

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

When I use Excel 2010 in the server, and when I copy some information on the cells, and try to paste on the client, the mouse is stuck in the middle of both systems. I need to move the mouse several times to the client in order to "unstuck" from the client. After that I need to clear clipboard from the server in order to have working again Synergy on the client.

### Other info ###

* Is there a way to work around it? No, the only way is to clear the clipboard from the server, but the info that I need to copy from the server to the client is lost, I can't.
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by XinyuHou** [comment] 2017-03-30 15:43
@elierh 
Currently Synergy doesn't support large clipboard data very well. Please sit tight.

Duplicate of #5531

**Closed by XinyuHou** 2017-03-30 15:43 UTC
