### ISSUE TITLE
Windows monitor power save not working

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#19] opened 2014-10-12 23:35 UTC
**Imported issue:**
- Author: tra...@travisanddenise.com (Google user)
- Date: 2009-03-26 00:00:00
- Legacy ID: 28
- Version: 1.5.0

The power save setting are set the same on both machines. The vista  
computer shuts monitor off correctly but the xp machine stays on.  

**What version of the product are you using? On what operating system?**  
Client windows xp Pro SP3  
Server Vista  

I am using version 1.3.3

**Comment by XinyuHou** [comment] 2017-04-21 12:28
Duplicate of #4116

**Closed by XinyuHou** 2017-04-21 12:28 UTC
Labels: bug
