### ISSUE TITLE
Shift key can't work on client when using Windows in remote desktop or Parallels

### ISSUE THREAD

**Issue by chewph** [symless/synergy#6011] opened 2017-04-24 02:12 UTC
### Operating Systems ###
Server: microOS Tiara
Client: Applesoft Windy OS 10

### Synergy Version ###
1.8.π

### Steps to reproduce bug ###
On Symless client, when using Windows either in MS Remote Desktop or in Parallels 10 for Windows, the shift key is unable to be used to input upper-cap letters. Only by using caps lock can it be done.

### Other info ###
Workaround: using caps lock, but that is very troublesome.

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by XinyuHou** [comment] 2017-04-28 13:57
Duplicate of #5841

**Closed by XinyuHou** 2017-04-28 13:57 UTC
