### ISSUE TITLE
Hotkey keystroke is not performed on the server

### ISSUE THREAD

**Issue by jasonfisherjlf** [symless/synergy#6386] opened 2018-08-07 00:31 UTC
### Operating Systems ###

Server: Windows 10 Version 1709
Client: Windows 10 Version 1709
Client: Ubuntu 18.04

### Synergy Version ###

1.10.0-stable-275cdc1c
synergys 1.10.0, protocol version 1.6

### Command Line ###

N/A - Running from UI

### Steps to reproduce bug ###

After trying just about everything I can possibly think of, I can't get a hotkey to work on my server computer "Jason_work_lappy". Calling it out explicitly (a.k.a. "keystroke(Alt+F12,Jason_work_lappy)") does nothing. Telling it to run on all (a.k.a. "keystroke(Alt+F12,*)") does nothing. Telling it to "press", "release", or "press and release" does nothing. Telling the action to happen when the hotkey is "pressed" or "released" makes no difference. Yet, when I perform the keystroke manually on "Jason_work_lappy" (the server), the hotkey works fine and does what I would expect. This makes using hotkeys with Synergy INCREDIBLY annoying, and far less useful...

Using config file
1. Open config file
2. Under "section: options" add line: "keystroke(Control+Shift+End) = keystroke(Alt+F12,Jason_work_lappy)"
3. On server UI, click "Apply"
4. Perform keystroke "Control+Shift+End"
5. ***Nothing happens on server machine*** All other machines receive keystroke and perform hotkey successfully.
6. Open config file again, and change hotkey line to "keystroke(Control+Shift+End) = keystroke(Alt+F12,*)"
7. On server UI, click "Apply"
8. Perform keystroke "Control+Shift+End"
9. ***Nothing happens on server machine*** All other machines receive keystroke and perform hotkey successfully.
10. On server perform keystroke "Alt+F12"
11. Hotkey works as expected

### Other info ###

* When did the problem start to occur? I'm a new user, so it has always been doing this...
* Is there a way to work around it? Perform the keystroke on the server AFTER all other machines receive keystroke and the hotkey is activated for them.
* Does this bug prevent you from using Synergy entirely? No

**Comment by kLabz** [comment] 2020-08-07 07:38
Same issue here, and I fail to use the workaround

> Is there a way to work around it? Perform the keystroke on the server AFTER all other machines receive keystroke and the hotkey is activated for them.

How do you do that?

**Comment by reversefold** [comment] 2021-01-28 23:53
Yep, same for me. I don't know what the workaround is saying to do exactly but nothing seems to work to send keys to the server, even something relatively simple like

keystroke(KP_2) = keystroke(Plus)

works only on clients and not on the server

**Comment by likuilin** [comment] 2021-07-07 16:06
I contacted Synergy Support about this problem today, linking this issue, and here was their reply: 

> I can log this in our internal tracking system for the dev team to review, but I tested just now and was unable to get it working either. You have helped so far by providing this information, but going forward it would be for our team to reproduce the issue and release an update to Synergy to resolve it. 
> 
> I can't provide a timeline but I will add your ticket to the open issue so you receive notification of any progress made. I will close this ticket for now however, as beyond logging the issue I won't be able to offer additional assistance on this.

So I hope this will be fixed soon, even though the issue is three years old.

**Comment by jasonfisherjlf** [comment] 2021-07-07 19:17
@likuilin Awesome, thank you for contacting them! I honestly had given up hope of them ever even considering fixing this issue. I also hope that they will get someone to look at and fix this issue.

**Comment by likuilin** [comment] 2023-10-28 10:24
Bump

**Comment by nbolton** [comment] 2024-09-06 22:10
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Closed by nbolton** 2024-09-06 22:10 UTC
Labels: bug, triage, unanswered
