### ISSUE TITLE
Build fail on Yosemite Error: [Errno 2] No such file or directory: ‘/Library/Frameworks/QtCore.framework/Contents/Info.plist’

### ISSUE THREAD

**Issue by Bashar** [symless/synergy#5634] opened 2016-10-01 22:36 UTC
Build fails on OSX Yosemite 10.10.5 with the error
Error: [Errno 2] No such file or directory: ‘/Library/Frameworks/QtCore.framework/Contents/Info.plist’

the solution was to edit command1.py and change the path based on this japanese or chinese blog post (thanks to google translate) https://blog.update.sh/archives/410

Basically i changed the frameworkRootDir to /usr/local/Cellar/qt/4.8.6/Frameworks and build worked.

also a side note it would be great to put examples of --mac-sdk and --mac-identity because i had to google and guess --mac-sdk 10.11 --mac-identity Yosemite because its missing from the wiki

**Comment by nlyan** [comment] 2016-10-05 10:16
Duplicate of #3797

**Closed by nlyan** 2016-10-05 10:16 UTC
