### ISSUE TITLE
Data on clipboard makes mouse unbearably laggy

### ISSUE THREAD

**Issue by maqp** [symless/synergy#6134] opened 2017-08-22 20:46 UTC
### Operating Systems ###

Server: Ubuntu 16.04x64
Client: Ubuntu 17.04x64

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

1. Start server and all clients
2. Empty clipboard (e.g. copy a password in server's keepass2 and let program clear it from clipboard)
3. Move mouse around different screens, works beautifully
4. Copy large image to clipboard using server
5. Mouse moves more and more sluggish the "further" the client is from server in Server configuration layout
6. Empty the clipboard (e.g. using server's keepass2 again)
7. Works beautifully

(Note that I tried generalizing [clipboard cleaning with xsel](https://askubuntu.com/questions/287444/how-to-clean-the-clipboard) but this doesn't seem to fix it, keepass2 however does)

### Other info ###

I have no information about what other versions this affects.
It does not prevent me from using Synergy, but makes use unbearable.

My proposal for a solution is to have Synergy update the clipboard only when CTRL+C / is pressed, and immediately share the clipboard to server and all clients to prevent mouse from lagging.

**Comment by yupi2** [comment] 2017-08-22 22:34
Seems to be a problem with the clipboard formats, at least on X. The `text/plain` format does not get the cursor lag on screen switch for me.

**Comment by XinyuHou** [comment] 2017-09-05 14:28
Duplicate of #5531

**Closed by XinyuHou** 2017-09-05 14:28 UTC
