### ISSUE TITLE
Redundant restart for elevation when already elevated

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3241] opened 2014-10-13 06:46 UTC
**Imported issue:**

* Author: Nick Bolton
* Date: 2012-07-31 21:33:12
* Legacy ID: 3311
* Version: 1.4.15

1. Check the "Elevate" option
2. Click Apply
3. Cause a UAC dialog to display

Expected: Mouse is usable immediately

Actual: Mouse can't be used for ~5 secs while server/client restarts for elevation (when already elevated)

**Comment by dpolivy** [comment] 2015-11-24 21:55
Is this fix still relevant, and can in be incorporated into the latest builds? It really seemed to help back when I was using 1.4.x, and it seems there are a bunch of other issues here that would be solved by adding this in for all.

**Comment by dpolivy** [comment] 2015-12-02 00:13
Quick update, I pulled the latest commits into my fork, and then re-applied this diff, and sure enough, if I run Synergy in elevated mode, then I don't lose the connection when UAC prompts appear!

The updated diff is:
````
@@ -527,7 +527,9 @@ void MainWindow::startSynergy()
		// is switched; this is because we may need to elevate or not
		// based on which desk the user is in (login always needs
		// elevation, where as default desk does not).
-		args << "--stop-on-desk-switch";
+		if (!appConfig().elevateMode()) {
+			args << "--stop-on-desk-switch";
+		}
#endif
	}
````

I don't know what the current issues are with always running in an elevated mode, but if they're minimal or have been addressed since this was originally opened, I'd strongly suggest pulling this change in.

**Comment by ktiedt** [comment] 2015-12-02 01:06
Subscribing, plus curious, how has this gone over a year w/o being fixed when there is a patch!?!?!? Are you waiting for a pull request? Especially considering how annoying this problem is (I actually have to restart my server to reconnect it seems -- or maybe I just dont wait long enough...).

**Comment by pmkane** [comment] 2016-04-10 02:15
Still seeing this behavior with Synergy Pro 1.7.6.

**Comment by XinyuHou** [comment] 2016-04-15 16:14
Can someone test this nightly?
http://synergy-project.org/nightly?filter=synergy-pr5139-fix-redundant-restart-for-elevation-beta-06c853a

**Comment by babist1st** [comment] 2016-04-17 21:06
I have been using it for about 2 days on my windows 10 laptop.
The server is an Arch linux machine with the latest stable release.

The UAC popup doesn't disconnect me anymore and it also seems to fix a similar disconnect when unlocking windows after having locked windows with win key+l

This might be a different problem.
There is a slight freeze if you move the mouse when unlocking but no disconnect.
(and that might result in a jittery mouse movement that goes back to normal after a minute or two.
The jittery mouse i can't always reproduce it so it might be unrelated or even due to my network)

Anyway it doesn't seem there is any freeze when the UAC appears/disapears so overall this a great fix and i hope it makes it to stable

**Comment by XinyuHou** [comment] 2016-06-10 15:10
Fixed by cb6012f91be4c0fe67c6d7a58dbded89dc6e0941

**Closed by XinyuHou** 2016-06-10 15:10 UTC
Labels: bug, sprint-could

**Comment by ktiedt** [comment] 2016-06-27 15:55
Is there an ETA on when this version might get released?

**Comment by LeadManPL** [comment] 2016-08-23 09:21
ssue #3241
1. Open GUI on Windows
2. Ensure client mode is used
3. Go to Edit->Settings
4. For Elevate mode, select 'Always'
5. Click OK, then click Apply
6. Press Win+R
7. Paste: C :  \ Windows \ System32 \ UserAccountControlSettings . exe
8. Make a note of your current setting
9. Set notify level to highest level (always notify)
10. Click OK, then click Yes
11. Press Win+R
12. Paste: C :  \ Windows \ System32 \ UserAccountControlSettings . exe
13. Synergy should stay connected when UAC dialog appears
14. Cancel the UAC dialog
15. Change your setting back to the original

SRV: synergy-v1.8.3-rc1-e36a7ae-Linux-x86_64
CLN: synergy-v1.8.3-rc1-e36a7ae-Windows-x64

PASSED. Synergy stayed connected.

**Comment by LeadManPL** [comment] 2016-09-22 11:09
Retested bug with RC2 for regressions:

SRV: synergy-v1.8.3-rc2-89c9c58-Linux-x86_64
CLN: synergy-v1.8.3-rc2-89c9c58-Windows-x64

Issue #3241
1. Open GUI on Windows
2. Ensure client mode is used
3. Go to Edit->Settings
4. For Elevate mode, select 'Always'
5. Click OK, then click Apply
6. Press Win+R
7. Paste: C : \ Windows \ System32 \ UserAccountControlSettings . exe
8. Make a note of your current setting
9. Set notify level to highest level (always notify)
10. Click OK, then click Yes
11. Press Win+R
12. Paste: C : \ Windows \ System32 \ UserAccountControlSettings . exe
13. Synergy should stay connected when UAC dialog appears
14. Cancel the UAC dialog
15. Change your setting back to the original

PASSED. Synergy stayed connected.
