### ISSUE TITLE
connect single client to multiple servers OR reverse sharing model

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#292] opened 2014-10-13 00:41 UTC
**Imported issue:**
- Author: brendan.hide (Google user)
- Date: 2009-12-02 00:00:00
- Legacy ID: 301

We'd like to allow a large number of users (perhaps as much as 5) to be  
able to work on a desktop which has a wall-mounted large (40") viewable screen.  

The "bigscreen", as we call it, is used by us to monitor graphs. If at any  
time we need to change any options / open a different graph / etc then we  
used to get up and use the "bigscreen"'s own keyboard and mouse off the  
floor (no desk).  

We now have a single person who has it set up via synergy who can quickly  
and simply do the necessary changes however no-one else can perform this  
task remotely.  

I see 2 ways that this could be achieved:  
1. Allow a single client to connect to multiple servers  
2. Allow a reversal of the client-server model (allow multiple client  
keyboard/mouses to control the server instead of single server  
keyboard/mouse control multiple clients)  

I believe 2 would be easier to implement however it depends much on how  
synergy had been developed up to now. synergy-plus developers are more  
qualified to answer that question.

**Comment by TekBear** [comment] 2015-11-21 23:54
re:  problem mentioned by "brendan.hide":  Would it not be possible to run 5 instances of the synergy client on your "bigscreen" PC (the wall-mounted large (40") viewable screen PC). Then each staff PC which is running a synergy server instance. As only one staff member at a time does access at a time combined with "scroll lock" it would bee manageable.

**Comment by TekBear** [comment] 2015-11-22 00:13
@Phaestion  you would need a mouse on each machine and have to move the mouse to other screen to share the keyboard you must move the attached mouse to the other screen to change keyboard focus, so either 2 mice with both running servers and client instances or 1 mouse and 1 keyboard on same machine.
You maybe able to do it with "hotkey" without the extra mouse:
````
section: options
        keystroke(alt+kp_1) = switchToScreen(machineUbuntu)
        keystroke(alt+kp_2) = switchToScreen(machineMac)
end
````
(assuming synergy 1.3.1 config syntax is still valid in later releases)

**Comment by digitalextremist** [comment] 2015-11-30 07:00
:+1: to "multiple servers per client" approach

**Comment by XinyuHou** [comment] 2017-04-21 12:32
Duplicate of #4232

**Closed by XinyuHou** 2017-04-21 12:32 UTC
Labels: enhancement
