### ISSUE TITLE
A Server running SSL tries too many times to connect to a client with SSL disabled

### ISSUE THREAD

**Issue by speaker** [symless/synergy#4694] opened 2015-05-21 00:20 UTC
A server with SSL turned on will keep trying to connect to a client with SSL turned off too many times.

If the encryption state between the server and client are mismatched, the connection attempts should cease and a meaningful message should be displayed to help explain how to correct the problem.

**Comment by XinyuHou** [comment] 2017-03-08 12:12
Duplicate of #5898

**Closed by XinyuHou** 2017-03-08 12:12 UTC
Labels: bug
