### ISSUE TITLE
Wrong keystrokes sent to client using British layout

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3961] opened 2014-10-13 07:47 UTC
@ == q
" == @
\ == #

**Imported issue:**
- Author: Aaron C
- Date: 2014-04-29 20:51:49
- Legacy ID: 4031

This is a very frustrating problem that has existed for years and it's never been given proper attention. (Seems to affect German layouts too. Possibly a problem with **_all**_ non-US layouts?!)

**Steps to reproduce:**
1. Install 1.4.17 on server with encryption.
2. Install 1.4.17 on client with encryption.
3. Start session.
4. Type. Watch random characters break.

Expected: Symbols like @, ", \, should appear.
Actual: Symbols like q, @, -, actually appear respectively. Many other symbols don't work. 

Here are all keys pressed on server and client for comparison, from top to bottom, left to right, no shift then shift and with workaround applied.

```
`1234567890-=qwertyuiop[]asdfghjkl;'#\zxcvbnm,./        ### SERVER, NOSHIFT
`1234567890-=qwertyuiop89asdfghjkl;'\-zxcvbnm,./        ### CLIENT, NOSHIFT, BEFORE HACKY XMODMAP WORKAROUND
`1234567890-=qwertyuiop[]asdfghjkl;'#\zxcvbnm,./        ### CLIENT, NOSHIFT, AFTER HACKY XMODMAP WORKAROUND
!"$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%^&*()_+QWERTYUIOP{}ASDFGHJKL:@~|ZXCVBNM<>?     ### SERVER, SHIFT
~!@#$%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%^&*()_+QWERTYUIOP{}ASDFGHJKL:q|~ZXCVBNMZX?     ### CLIENT, SHIFT, BEFORE HACKY XMODMAP WORKAROUND
 !" $%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%^&*()_+QWERTYUIOP{}ASDFGHJKL:@~|ZXCVBNM<>?     ### CLIENT, SHIFT, AFTER HACKY XMODMAP WORKAROUND (notice  and  are omitted entirely)
```

**Versions and operating systems:**

SERVER and Locale  
Linux 3.8.0-19-generic #29-Ubuntu SMP Wed Apr 17 18:16:28 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux  
LANG=en_GB.UTF-8  
LANGUAGE=  
LC_CTYPE="en_GB.UTF-8"  
LC_NUMERIC="en_GB.UTF-8"  
LC_TIME="en_GB.UTF-8"  
LC_COLLATE="en_GB.UTF-8"  
LC_MONETARY="en_GB.UTF-8"  
LC_MESSAGES="en_GB.UTF-8"  
LC_PAPER="en_GB.UTF-8"  
LC_NAME="en_GB.UTF-8"  
LC_ADDRESS="en_GB.UTF-8"  
LC_TELEPHONE="en_GB.UTF-8"  
LC_MEASUREMENT="en_GB.UTF-8"  
LC_IDENTIFICATION="en_GB.UTF-8"  
LC_ALL=  

CLIENT and locale  
Linux 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux  
LANG=en_GB.UTF-8  
LANGUAGE=en_GB:en  
LC_CTYPE="en_GB.UTF-8"  
LC_NUMERIC="en_GB.UTF-8"  
LC_TIME="en_GB.UTF-8"  
LC_COLLATE="en_GB.UTF-8"  
LC_MONETARY="en_GB.UTF-8"  
LC_MESSAGES="en_GB.UTF-8"  
LC_PAPER="en_GB.UTF-8"  
LC_NAME="en_GB.UTF-8"  
LC_ADDRESS="en_GB.UTF-8"  
LC_TELEPHONE="en_GB.UTF-8"  
LC_MEASUREMENT="en_GB.UTF-8"  
LC_IDENTIFICATION="en_GB.UTF-8"  
LC_ALL=  

**Temporary workarounds:**

On client run:

```
xmodmap -e "keycode 24 = q Q at at at at"
```

This seems to fix many. GBP symbol (****) still broken, others too.

**Similar bugs:**

http://synergy-foss.org/spit/issues/details/71/

http://superuser.com/questions/77734/synergy-linux-keyboard-problem

https://bugs.launchpad.net/ubuntu/+source/synergy/+bug/52534

http://synergy-foss.org/spit/issues/details/3197 (Thanks Chris Ferebee)

**Additional comments:**

This has never been fixed. Can't we please get some love in the UK? I will genuinely mail you an en_GB USB keyboard completely for free if that's what it takes to get this fixed. I'd love to donate more and keep the project alive but it's hard to take it seriously when bugs like this don't receive attention. Lots of potential for encoding cock-ups here on the forums, so here's a raw paste of the issue submission: http://paste.ubuntu.com/7361578/

Thanks

Edit 2014-04-29 20:55:30: More sensible char layout  
Edit 2014-05-01 13:30:30: Added Chris' bug #3197
Edit 2014-05-01 13:45:35: Better locale paste

**Comment by XinyuHou** [comment] 2017-04-21 14:45
Duplicate of #4280

**Closed by XinyuHou** 2017-04-21 14:45 UTC
Labels: bug
