### ISSUE TITLE
Store configurations in the cloud

### ISSUE THREAD

**Issue by claell** [symless/synergy#5537] opened 2016-08-14 11:24 UTC
I'd like to be able to have my configuration synced to my Smyless account in order to easily reuse them on other setups.

**Comment by nlyan** [comment] 2016-08-15 09:27
Interesting idea. I'll be sure to bring this up. We certainly have the infrastructure for it.

**Comment by 0x9090** [comment] 2016-08-18 22:23
Please be careful to not embed any passwords/hashes/keys in configs that are pushed to the cloud

**Comment by nlyan** [comment] 2016-10-25 16:54
Duplicate of #3988

**Closed by nlyan** 2016-10-25 16:54 UTC
Labels: enhancement, gui-two-ideas
