### ISSUE TITLE
Cannot write characters that requires Alt Gr

### ISSUE THREAD

**Issue by ninjalf2** [symless/synergy#6109] opened 2017-07-20 22:46 UTC
### Operating Systems ###

Server: Arch Linux kernel 4.11.9
Client: Windows 10 version 1703 (build 15063.483)

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###
1. Go to any text input
2. Attempt to write "@" with Alt Gr + 2 (Danish layout)
3. Only the number 2 appears

### Other info ###

* When did the problem start to occur? For as long as I remember
* Is there a way to work around it? Using Ctrl+Alt sometimes works
* Does this bug prevent you from using Synergy entirely? No

Touchpad driver:
xf86-input-synaptics 1.9.0-1

All OS languages in English but keyboard layout on all machines is Danish.

This happens with any character that requires the Alt Gr key to be pressed (@, £, $ and so on).

**Comment by XinyuHou** [comment] 2017-07-21 10:46
Duplicate of #4411 #5185

**Closed by XinyuHou** 2017-07-21 10:46 UTC
