### ISSUE TITLE
Use alt key to change languages doesn't work on client

### ISSUE THREAD

**Issue by ghost** [symless/synergy#5251] opened 2016-03-23 22:48 UTC
jinjae4000 commented 7 days ago
I use alt-key to change language on my server. Same should work on the client.
 @XinyuHou
 Symless member
XinyuHou commented 2 days ago
Please give us more information about your system and which version of Synergy you are using.

I will close this issue for now.
 :-1: 1  
 @XinyuHouXinyuHou closed this 2 days ago
@jinjae4000

jinjae4000 commented a day ago
Here is the version. And I'm on windows 7 for both client and server.
Stable version (1.7.6 - Mar 15, 2016)

**Comment by XinyuHou** [comment] 2017-04-21 15:26
Duplicate of #5798

**Closed by XinyuHou** 2017-04-21 15:26 UTC
Labels: bug
