### ISSUE TITLE
Tab key recognized as shift+tab

### ISSUE THREAD

**Issue by thetechstewart** [symless/synergy#5465] opened 2016-07-12 16:08 UTC
On the remote client machine, when attempting to tab, the keystroke is recognized as shift+tab.  Version 1.8.2-beta-7d0cb34, Debian 8 on both machines.

Output from logs:
>[2016-07-12T11:54:39] DEBUG2: want to read, error=2, attempt=1
>[2016-07-12T11:54:39] DEBUG2: msg from server: DKDN
>[2016-07-12T11:54:39] DEBUG2: readf(%2i%2i%2i)
>[2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 61193 (0xef09)
>[2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 0 (0x0)
>[2016-07-12T11:54:39] DEBUG2: readf: read 2 byte integer: 23 (0x17)
>[2016-07-12T11:54:39] DEBUG1: recv key down id=0x0000ef09, mask=0x0000, button=0x0017
>[2016-07-12T11:54:39] DEBUG1: mapKey ef09 (61193) with mask 0000, start state: 0000
>[2016-07-12T11:54:39] DEBUG1: find best:  0000 0000
>[2016-07-12T11:54:39] DEBUG1: best key index 2 of 2 (exact)
>[2016-07-12T11:54:39] DEBUG1: found key in group 0
>[2016-07-12T11:54:39] DEBUG1: state: 0000,0001,0001
>[2016-07-12T11:54:39] DEBUG1: flip: 0001 (0000 vs 0001 in 0001 - 0000)
>[2016-07-12T11:54:39] DEBUG1: desired state: 0000 0001,0001,0001
>[2016-07-12T11:54:39] DEBUG1: flip: 0000 (0001 vs 0000 in fffe - 6020)
>[2016-07-12T11:54:39] DEBUG1: mapped to 017, new state 0000
>[2016-07-12T11:54:39] DEBUG1: keystrokes:
>[2016-07-12T11:54:39] DEBUG1:   032 (00000000) down
>[2016-07-12T11:54:39] DEBUG1:   017 (00000000) down
>[2016-07-12T11:54:39] DEBUG1:   032 (00000000) up
>[2016-07-12T11:54:39] DEBUG2: writef(CNOP)
>[2016-07-12T11:54:39] DEBUG2: wrote 4 bytes

**Comment by TafThorne** [comment] 2016-07-13 14:48
I am seeing this on 1.8.2-beta-85bbbd4 as well.  I have an Ubuntu 16.06 server with a Windows 7 client.  When I am in a webform or email client this manifests by the tab key navigating backward through the input fields instead of forwards.

**Comment by Cdingo** [comment] 2016-07-14 16:40
Duplicate of #5373

**Closed** 2016-07-18 16:03 UTC
