### ISSUE TITLE
Linux client freezes with memory leak

### ISSUE THREAD

**Issue by cmellwig** [symless/synergy#4363] opened 2015-02-13 19:27 UTC
Synergy 1.6.2 freezes my PC 5 minutes after rebooting and allocates the remaining 13GB of RAM. There are no logs (synergy or linux) regarding the issue.

Client: Linux 3.18.6-1-ARCH #1 SMP PREEMPT Sat Feb 7 08:44:05 CET 2015 x86_64 GNU/Linux
Host: Win 8.1
Synergy 1.6.2

**Comment by nbolton** [comment] 2015-03-06 13:14
Hey @cmellwig - I'm guessing its the Windows machine that freezes after running out of RAM?

**Comment by nbolton** [comment] 2015-03-06 13:15
@cmellwig Are you running in debug log level?
I have a hunch this is because of our crappy IPC logging.

**Comment by cmellwig** [comment] 2015-03-06 13:57
The Linux machine runs out of RAM and crashes. The problem dissolves after restarting the windows server though. Restarting the Linux client and keeping the Windows server up, results in another freeze after a couple of minutes.
I'm on debug log level now.

**Comment by nbolton** [comment] 2015-03-06 14:04
Oh, so the issue is on the Linux client... how long does it take for the RAM to get from 0 to 13GB?

**Comment by cmellwig** [comment] 2015-03-06 14:16
I havent got exact figures, but it seems to be a matter of seconds

**Comment by nbolton** [comment] 2015-03-06 14:20
Woah, that's no good. Does this happen in the nightly builds too? http://synergy-project.org/nightly

**Comment by cmellwig** [comment] 2015-03-06 15:49
The Windows machine tend to crash as well. I cant use mouse or keyboard until I CTRL-ALT-DEL and reboot from there. Tried the nightly but synergy crashed after a minute on my Windows machine. This beaviour occured first on 1.6.2. v1.5.1 worked fine.

**Comment by nh2** [comment] 2016-04-07 20:11
I can confirm this bug, yesterday and today it disabled my computer within a second so that I had to hard-reboot.

Here's some extra info that may be useful for you:

* For me it happened on the synergy server (`Share` tab in quicksynergy), `synergys 1.4.12`
* For me it happened when the other side was Linux too (`synergyc 1.4.12`)
* Its behaviour is nasty in that it somehow Linux's OOM-killer (I'm not using a swap so usually the "bad" processes get killed, but synergy kept making my computer unusable for > 10 minutes when I hard-rebooted)
* For me it happened after I moved my cursor from the server to the client, closed an `xpra` client program over there, and then moved the cursor back. Instant computer death, no mouse or keyboard input possible.

**Comment by andyneff** [comment] 2016-10-13 17:37
I can confirm I had this problem on version 1.8.3. Over 15GB!

```
> ps -o drs,%mem 2411
```

DRS|%MEM
---|---
15091673|45.4

Maybe it's because synergy no longer crashes due to clipboard, but synergy 1.8.3 has been running for 9 days now, and I noticed today it's using a significant amount of memory. Before the clipboard fix, synergy never ran more than a day for me, I always had to restart it.

```
PID  PPID  C STIME TTY      STAT   TIME CMD
2411     1  0 Oct04 ?        Ssl   41:03 synergys --daemon --debug INFO --name turing --enable-crypto --log /home/andy/.config/Synergy/synergys.log -c /home/andy/.config/Synergy/synergy_1.8.3.conf --address :24800
```

Running synergy server 1.8.3 on Linux Mint 18, and synergy client 1.8.3 on Windows 10 (Memory there is about 2MB, so good)

**Comment by nlyan** [comment] 2016-11-01 11:50
I wonder if this is the same virtual memory leak we're seeing on macOS. Current theory is it's something to do with autoconfig. 

@andyneff Do you have autoconfig enabled?

**Comment by andyneff** [comment] 2016-11-10 16:14
@nlyan I think the answer is no? I do not use the `synergy` command to start `synergys`, except to figure out the initial configuration. Once I get my conf file how I like it, I start synergy with the following command

    bash -c 'pkill -9 synergys; synergys --daemon --debug INFO --name my_server_name --enable-crypto --log /home/andy/.config/Synergy/synergys.log -c /home/user/.config/Synergy/synergy_1.8.3.conf --address :24800'

And my conf file is

```
section: screens
	my_server_name:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
	my_laptop_name:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
	my_tablet_name:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
end

section: aliases
end

section: links
	my_server_name:
		right = my_laptop_name
	my_laptop_name:
		left = my_server_name
		right = my_tablet_name
	my_tablet_name:
		left = my_laptop_name
end

section: options
	relativeMouseMoves = false
	screenSaverSync = true
	win32KeepForeground = false
	clipboardSharing = true
	switchCorners = none 
	switchCornerSize = 0
	mousebutton(6) = keystroke(WWWBack)
	mousebutton(7) = keystroke(WWWForward)
	keystroke(Meta+Shift+Left) = switchInDirection(left)
	keystroke(Meta+Shift+Right) = switchInDirection(right)
	keystroke(Meta+Shift+Up) = switchInDirection(up)
	keystroke(Meta+Shift+Down) = switchInDirection(down)
end
```

For the most part, this problem has not occurred again, and I've changed nothing to prevent it.

I'm upgrading to 1.8.5 today

**Comment by cmellwig** [comment] 2016-11-11 09:32
Same for me again, version 1.8.5. I didn't notice this behavior for quite some time. I use `synergy` to start the server. No autoconfig

**Comment by nh2** [comment] 2018-06-24 13:57
Was this fixed? Which commit fixed it?

**Comment by yupi2** [comment] 2018-06-26 15:38
I had a memory leak for Linux that would do this. It appeared to originate from the `std::vector<asdf> pfds` in `SocketMultiplexer::serviceThread()` for me. Resizing the vector or clearing it didn't help so moving it into the for-loop eventually help. It's not a good fix but it worked for some reason. https://github.com/yupi2/synergy/commit/df99d53a9658f51ee39915d8c531f7fef79d15c9

The leak didn't... leak on Windows so that's why it was ifdef'd away for Unix/Linux only.

**Comment by nbolton** [comment] 2024-09-06 21:57
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Closed by nbolton** 2024-09-06 21:57 UTC
Labels: bug, triage, unanswered
