### ISSUE TITLE
OSX hash or pound from UK keyboard not passed to client

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2637] opened 2014-10-13 05:29 UTC
**Imported issue:**
- Author: mattaw (Google user)
- Date: 2010-08-19 00:00:00
- Legacy ID: 2664
- Version: 1.4.1

> What list of steps will reproduce the problem?  
> Pressing ALT+3 on the OSX doesn't produce a '#' character.  
> 
> What version of operating system, and Synergy+ are you using?  
> Setup: OSX 10.6.4, synergy server, read only SVN head "/p/synergy-plus/source/detail?r=684":r684 , client Windows 7, synergy x86 beta 1.4.1  
> 
> What is the expected behaviour, and what happens instead?  
> No character is produced  
> 
> Is there a way of temporarily working around your problem?  
> Only to use the character map to create one or to copy an existing one  
> 
> Would you like to solve the problem yourself and submit a patch?  
> Not at the moment but a fix is proposed here but doesn't seem to have been committed?  

"http://groups.google.com/group/synergy-plus/browse_thread/thread/e1d9bec2c494693a?fwc=2&pli=1":http://groups.google.com/group/synergy-plus/browse_thread/thread/e1d9bec2c494693a?fwc=2&pli=1

**Comment by Corben78** [comment] 2015-04-06 08:50
Ubuntu as Synergy server (12.04. or 14.04.) and OS X as client (Mavericks or Yosemite), german keyboard layout.
Character '#' is not passed to the client, instead a '3' is entered. Haven't found any other option to get a '#' passed over, only via copy & paste.

**Comment by XinyuHou** [comment] 2017-04-21 12:56
Duplicate of #3127

**Closed by XinyuHou** 2017-04-21 12:56 UTC
Labels: bug
