### ISSUE TITLE
The smallest scroll size on OSX is 76 pixels

### ISSUE THREAD

**Issue by p12tic** [symless/synergy#5672] opened 2016-10-16 17:29 UTC
### Operating Systems ###

Client: Ubuntu Linux 16.04
Server: OSX 10.12 Sierra

### Synergy Version ###

1.8.4 stable

### Steps to reproduce bug ###

1. Scroll slowly on the server
2. Observe that the client ignores the scroll
3. Scroll faster until the client log starts to show  "WARNING: Wheel scroll delta (76) smaller than threshold (120)" messages
4. Observe that the scrolling is very jumpy.

### Other info ###

Will do a PR with a fix shortly

**Comment by XinyuHou** [comment] 2016-10-17 13:36
Duplicate of #5604

**Closed by XinyuHou** 2016-10-17 13:36 UTC
