### ISSUE TITLE
Typing [ and ] give 5 and 6 on Mac OS X German keyboard

### ISSUE THREAD

**Issue by Botzman** [symless/synergy#4157] opened 2014-11-03 09:24 UTC
Server is Windows7 with english keyboard. Client is MacOS 10.9.4 ( english ) having german keyboard (long one with numeric pad). Enable U.S. keyboard layout in both MacOS and in Windows. Start typing in MacOS. Instead of [ and ] you get 5 and 6. Instead { and } you get \* and (.

**Comment by XinyuHou** [comment] 2017-04-21 13:36
Duplicate of #4280

**Closed by XinyuHou** 2017-04-21 13:36 UTC
Labels: bug
