### ISSUE TITLE
Build fails using Xcode 8 and macOS SDK 10.12 

### ISSUE THREAD

**Issue by grigorovich** [symless/synergy#5626] opened 2016-09-29 08:55 UTC
### Operating Systems ###

Mac OS 10.12
Xcode 8.0 with SDK 10.12

Compile of source failed

### Synergy Branch Version ###

Branches Master (1.8.3), 1.8.4, 1.9.0

```
$./hm.sh conf --mac-sdk 10.11
Mapping command: conf -> configure
Error: Mac SDK not found at: /Developer/SDKs/MacOSX10.11.sdk

```
So i did switch to 10.12 SDK as well:
```
$./hm.sh conf --mac-sdk 10.12
Mapping command: conf -> configure
cmake version 3.6.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).
Entering dir: build/release
CMake command: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=0 ../..
-- OSX_TARGET_MAJOR=
-- OSX_TARGET_MINOR=
CMake Error at CMakeLists.txt:173 (message):
  Mac OS X target must be 10.x
-- Configuring incomplete, errors occurred!
See also "synergy/build/release/CMakeFiles/CMakeOutput.log".
Going back to: synergy
Error: CMake encountered error: 256
```

**Comment by nlyan** [comment] 2016-09-29 10:48
Duplicate of #5601, but yours looks better so I'm going to hijack it.

**Comment by ssreekanth** [comment] 2016-10-10 16:52
With `./hm.sh conf -g 2 -r --mac-sdk 10.12 --mac-identity test`, it configures fine, but build fails here -

```
CompileC build/src/lib/platform/synergy.build/Release/platform.build/Objects-normal/x86_64/OSXClipboard.o src/lib/platform/OSXClipboard.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/testuser/synergy
    export LANG=en_US.US-ASCII
...
...
/Users/testuser/synergy/src/lib/platform/OSXClipboard.cpp:128:41: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
                kPasteboardFlavorNoFlags);
                                        ^
1 error generated.
```

Any suggestion on how to resolve this?

**Closed** 2016-10-13 10:03 UTC
Labels: bug, sprint-must

**Comment by ssbarnea** [comment] 2016-10-25 17:02
Why not keeping this bug open as long we it fails to build with xcode-8 on Sierra?

I cloned the repository, read the README and tried `./hm.sh conf` and `./hm.sh build`, still getting errors so let's make it work without having to patch it or having to call it with different arguments.

**Comment by grigorovich** [comment] 2016-10-28 19:21
@nlyan 
# Operating Systems

Mac OS 10.12.1
Xcode 8.1 with SDK 10.12

```
$./hm.sh conf -g1 --mac-sdk 10.12 --mac-identity Sierra
$./hm.sh build

```
Compile of source was success. So it fixed.

# Synergy Branch Version
Branch: 1.8.5
Commit: Version to v1.8.5-rc2 // 28 october 2016 // c9bb421fb5deb056166e728c820ae547f5fa0c2f

**Comment by chapola** [comment] 2017-02-16 16:28
How to run this command and in which dir
I am getting this error
 sh: ./hm.sh: No such file or directory

**Comment by hoangdangninh** [comment] 2017-08-11 18:42
@chapola : git checkout <a-stable-branch-in-tags>
