### ISSUE TITLE
International US keyboard not working on client

### ISSUE THREAD

**Issue by brunosaboia** [symless/synergy#6147] opened 2017-09-11 18:15 UTC
### Operating Systems ###

Server: Ubuntu 17.04 Zesty
Client: Microsoft Windows 10 Home Insider Preview10.0.16241 N/A Build 16241

### Synergy Version ###

1.8.8-stable-25a8cb2 (it's the same version for both client/server)

### Overview ###
In my server, which runs Linux, I have two keyboard layout installed. That's because I am Brazilian, and sometimes I need to type special characters such as á, ç, ã, and so on. 

I have the exact same configuration on the Windows box, which is a laptop. I can use the special characters there using the hardware keyboard just fine. However, when I switch from Linux to Windows using Synergy, the keyboard does not accept some keys.

Laptop's built-in keyboard:
![img_20170911_144640](https://user-images.githubusercontent.com/1746033/30289392-66aaf238-9702-11e7-8d48-a2a13979aa76.jpg)

Shared keyboard, which is installed for Ubuntu:
![img_20170911_144646](https://user-images.githubusercontent.com/1746033/30289393-66c5142e-9702-11e7-9ced-c39cf55e39bb.jpg)

### Steps to reproduce bug ###
1) Connect a US keyboard to a Ubuntu;
2) Add International keyboard layout;
3) Go to Windows 10 box and try to input special characters
4) Be sad, because you can't input them

### Other info ###
- Usually, you can write an "ú" using international support by typing ', then u
- The only special character I can input in both is à and ê, and it's variants (è, ù, û, etc.).
- Using an [online keyboard tester](http://www.keyboardtester.com/), I can see that no keypress is detected when I hit the ' key on Windows.  
- I cannot input a ', nor a ~ on Windows using International. I need to go back to US to use it. I can however input a ` by the usual international way (pressing the key and then pressing space)
- I've tried both US international with dead keys and US alternative international. None worked.

**Comment by XinyuHou** [comment] 2017-09-13 13:57
Duplicate of #6005

**Closed by XinyuHou** 2017-09-13 13:57 UTC
