### ISSUE TITLE
Problems when I lock Server and client, the keyboard is stuck on the client...

### ISSUE THREAD

**Issue by elierh** [symless/synergy#5948] opened 2017-03-27 23:16 UTC
### Operating Systems ###

Server: Windows 7 Enterprise 6,1
Client: MacOS Sierra 10.12.3

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

When I lock both server and client, when I come back to my desk I try to unlock the Windows session from the server, but I can't, the keyboard is stuck on the client, for that reason I can't use both machines. The only way to "fix" the problem is to power down the server and then on again.

### Other info ###

* Is there a way to work around it? No, the only way to "fix" the problem is to power down the server and then on again.
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by XinyuHou** [comment] 2017-03-30 15:44
Duplicate of #5294

**Closed by XinyuHou** 2017-03-30 15:44 UTC
