### ISSUE TITLE
Cursor does not move across screen on Fedora 25 (GNOME)

### ISSUE THREAD

**Issue by Over-enthusiastic** [symless/synergy#5782] opened 2016-12-28 06:42 UTC
### Operating Systems ###

Server: Fedora 25 (GNOME)
Client: Fedora 23 (GNOME)

### Synergy Version ###

1.8.6-stable

### Steps to reproduce bug ###

start server on Fedora 25 and start client on Fedora 23 or vice versa. 
Try to move the cursor across the screen on both side.. it does not move. 

Does not seem to work on default Fedora 25 workstation on x86_64

### Other info ###

* I upgraded one system from fedora 23 to fedora 25 using fedup. Its has stopped working after that.
* Is there a way to work around it? Yes . I installed KDE. It works with KDE Plasma ( version 5.8.4 )
* Does this bug prevent you from using Synergy entirely? Yes

From what i understand synergy client and server both are not able to interact with GNOME on Fedora 25.

Please let me know if any more debug info i required.

**Comment by linxit-aw** [comment] 2016-12-29 13:54
Perfect, just what I suspected - switched to Gnome/XOrg session on Fedora 25 and it started working. Up to then I could see windows getting focus on the F25 box but couldn't see the cursor or use the keyboard.

**Comment by Over-enthusiastic** [comment] 2016-12-30 06:34
@yupi2 I think my gnome-shell is running in Xorg mode. 
```
[user@workstation~]$ loginctl show-session 1 -p Type
Type=x11
```
My system does not have a graphic card. Following post says that gnome-shell in fedora25 falls back to Xorg if there is no nvidia graphics card. 
http://unix.stackexchange.com/questions/327699/fedora-25-is-not-using-wayland-by-default

**Comment by XinyuHou** [comment] 2017-01-18 12:37
Duplicate of #5782

**Closed by XinyuHou** 2017-01-18 12:37 UTC

**Comment by DarrellDuane** [comment] 2017-02-13 00:22
Duplicate of https://github.com/symless/synergy/issues/4090

**Comment by faiazahmed** [comment] 2018-12-06 02:32
On Fedora 28 and Fedora 29 same problem. Changing to Gnome Classic solved the problem.
