### ISSUE TITLE
Client keyboard missing Swedish letters

### ISSUE THREAD

**Issue by NinthJake** [symless/synergy#5850] opened 2017-02-17 05:35 UTC
### Operating Systems ###

Server: Microsoft Windows 10 ver.1607 (OS Build 14393.693)
Client: Linux Ubuntu MATE 16.10

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

I have read the issues other people have about switching keyboard layouts. This is not that. My keyboard layout is correctly set to Swedish on both machines and the signs !"#%&/()=?`;:_-*^~ are all correct but the Swedish letters "Å,Ä,Ö" seem to be missing.

1. Get Swedish keyboard(?)
2. Change to Swedish keyboard layout
3. Try to type ÅÄÖ
4. ...
5. Profit?

### Other info ###

* When did the problem start to occur? When I...
It has never worked for me.

* Is there a way to work around it? No/Yes, you can...
I have not found any workaround.

**Comment by Celant** [comment] 2017-02-21 14:19
Can you let me know which physical keyboard layout you have?

**Comment by XinyuHou** [comment] 2017-03-01 11:53
Duplicate of #4280

**Closed by XinyuHou** 2017-03-01 11:53 UTC
