### ISSUE TITLE
Add config option to disable clipboard sharing

### ISSUE THREAD

**Issue by ceribik** [symless/synergy#5032] opened 2015-09-23 05:52 UTC
There is not a single day where I don't have some issue with the clipboard sharing functionality of synergy. Sometimes it just hangs the server, or at other times, it just "eats" the clipboard input which is lost forever (if you cut, vs copied that text).

Please add a config option to disable this.

**Comment by spronkey** [comment] 2015-09-25 02:19
+1

**Comment by database9-445** [comment] 2015-10-12 16:49
I would appreciate this as well. While I do like the clipboard feature I'd rather have Synergy running stable.

**Comment by GranoblasticMan** [comment] 2016-03-15 22:38
+1 I'd actually like to use ClipboardFusion for its more advanced options, but it causes issues with Synergy =( A simple "disable clipboard sharing" functionality on the server config would be greatly appreciated.

**Comment by 335** [comment] 2016-04-19 00:35
+1 Conflicts with other clipboard applications occur.

**Comment by XinyuHou** [comment] 2016-10-17 11:52
Duplicate of #123

**Closed by XinyuHou** 2016-10-17 11:52 UTC
Labels: enhancement
