### ISSUE TITLE
Why can't i copy data form server to client

### ISSUE THREAD

**Issue by demonguy** [symless/synergy#5586] opened 2016-09-08 10:17 UTC
I'm using synergy 1.8.2-stable-36cd521
But what i found is , clipboard data is always invalid from server to client, but it's OK to copy to server from client.

I can see "previous clipboard data has become invalid" in the server log. Why will everything become like this? Sometimes reboot server synergy might works but can't last for long.

Server: Windows 10
Client: Ubuntu 14.04, root

**Comment by nlyan** [comment] 2016-09-08 11:37
Duplicate of #5502. Thanks for reporting this issue.

**Closed by nlyan** 2016-09-08 11:37 UTC
