### ISSUE TITLE
different mouse axis acceleration

### ISSUE THREAD

**Issue by kekkokk** [symless/synergy#5996] opened 2017-04-14 07:50 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.3
Client: Windows 10 Creator's update 1703 build 15063.138

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

simply installed same version on each laptop (two macbook pro 15" 2011/2012). on one in the left i have natively installed windows 10. on the other (the server) I have sierra and an external monitor on the right connected to it.
I have an external mouse connected to the server (Logitech g500s with Logitech gaming software utility installed).
when I use the mouse on osx no problem, when i switch to the left, (synergy client) my upper Y axis and my left X axis accelerates 3 - 4 times faster than down and right. this is crazy.
if I use the touchpad it works flawlessly.

### Other info ###

tried to disconnect the external monitor and switching off Logitech gaming software but nothing changes.

**Comment by MhoDaraf** [comment] 2017-04-14 20:15
I have the same exact issue.

My Synergy server is running on a Sierra 10.12.4 machine and the client is on a Yosemite 10.10.5 MacBook Pro 2011.

**Comment by XinyuHou** [comment] 2017-04-21 11:40
Duplicate of #5607

**Closed by XinyuHou** 2017-04-21 11:40 UTC
