### ISSUE TITLE
Laggy cursor on Windows client

### ISSUE THREAD

**Issue by byingyang** [symless/synergy#4417] opened 2015-03-07 01:51 UTC
We fixed the WiFi lag on macOS in Synergy v1.9.0. Login to our forum using your Synergy account & [Download Synergy v1.9.0](https://symless.com/forums/topic/2587-synergy-v190-release-candidate/).
---
Using OS 10.10 for a server to Windows 8.1 client. I haven't tested with both connected via ethernet in a while so I'm not 100% sure it's because of wifi, but v1.7.x is laggy compared to 1.6.x. It becomes unusable if you enable the new SSL.

**Comment by alphabj** [comment] 2015-03-10 23:42
For what it's worth, my macbook pro is almost dead and the graphics is starting to flake out (it's a 2008 model, if you can believe that), so maybe it will be better when I get a new one.

**Comment by nbolton** [comment] 2015-03-18 08:49
Experienced this today with a fairly new MacBook Air (client), right next to the wifi router. I don't think its SSL related though, because I disabled SSL and its still laggy (intermittently). Not sure it's to do with network traffic, since synergyc uses barely any traffic. @the-wes @XinyuHou

**Comment by nbolton** [comment] 2015-03-18 08:50
@the-wes I feel this may be a duplicate?

**Comment by nbolton** [comment] 2015-03-18 08:58
@alphabj Hmm, cursor doesn't seem to be laggy on 1.6... does going back to 1.6 solve the issue for you?

**Comment by nbolton** [comment] 2015-03-18 09:00
@XinyuHou This may be specific to 1.7 and the SSL/plugin framework, or may be a duplicate of #4132, I'm not sure yet. Since I get the issue in 1.7 (without SSL) and not in 1.6, I guess it must be because of the new plugin framework?

**Comment by nbolton** [comment] 2015-03-18 09:00
@XinyuHou When SSL is disabled (from the GUI), does execution still go through the ns DLL?

**Comment by nbolton** [comment] 2015-03-18 09:02
@XinyuHou It'd be interesting to see if PR #4228 solves this...

**Comment by XinyuHou** [comment] 2015-03-18 14:14
@nbolton No, when SSL is disabled, the connection works as before.

**Comment by XinyuHou** [comment] 2015-03-18 14:18
@nbolton PR #4228 seems to fix socketJob list overwhelming issue. Not sure if it is relevant to 1.7 but worth a try.

**Comment by alphabj** [comment] 2015-03-18 14:27
Yeah going back to 1.6.2 seems to solve the problem. No more lag so far.

**Comment by nbolton** [comment] 2015-03-18 17:05
@XinyuHou I wonder what could it be about 1.7 that causes this? Its not SSL (still laggy without it).

**Comment by XinyuHou** [comment] 2015-03-18 17:14
Just created a branch for pull request #4228 . Can anyone test the nightly, galkinvv-fix2866-f4218ad? Here is the link to nightly

https://synergy-project.org/nightly

**Comment by nbolton** [comment] 2015-03-22 15:46
@XinyuHou That PR didn't solve my mac client lag :(

**Comment by nbolton** [comment] 2015-03-22 15:48
Re-worded the title to match OP's problem.

**Comment by alphabj** [comment] 2015-03-26 01:51
I just installed 1.6.3 and the issue seems to be happening again.

**Comment by paul-suarez** [comment] 2017-05-08 20:31
[Kevin on Forums](https://symless.com/forums/topic/2552-mac-client-laggy/)
5/9/17 02:22 

I have a MacOS 10.12.4 client and a Windows 7 server.  When i move the mouse to the Mac screen, it's unusable.  I've tried many configuration changes and it is not any better.  When i make the Windows the client and Mac the server, i have no issues. I have tried disabling SSL wit the same results.

**Comment by gopalaiahvinay** [comment] 2017-08-05 04:32
@XinyuHou So whats the solution for windows lag? 
I have already installed 1.9.0 on both server and client

**Comment by AnomalRoil** [comment] 2018-07-04 09:11
I've just installed Synergy 1.9.1 on my brand new laptop running Win 10 pro and on a gaming rig running Win 7 pro and when using Wifi with a 650Mbps connection (5Ghz, 802.11ac), and I'm experiencing the same kind of lag as described above.

I've taken a look and saw that the synergyc.exe client was not running with "realtime" priority, so I set it and it helped a tad, but still laggy.

Eventually, using a wired connection solved the problem. This is really strange, since I got a pretty descent wifi setup :unamused:

**Comment by twhitson** [comment] 2018-08-23 15:11
I have this issue using my work desktop (Windows 10 Pro 1803 17134.228) and my laptop (Windows 10 Home 1803 17134.228) both on Ethernet (CAT6) plugged into the same switch about 50ft away. It seems to only lag when I first move the cursor onto the client computer (laptop), then it's fine after that. I tried disabling SSL and the same issue occurs.

**Comment by G1itcher** [comment] 2019-02-01 21:51
Amazing that such a base feature of this software has been bugged like this for nearly 4 years. I've got the same issue. Seems to get worse and worse over time.

**Comment by nbolton** [comment] 2024-09-06 21:58
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Closed by nbolton** 2024-09-06 21:58 UTC
Labels: bug, triage, unanswered
