### ISSUE TITLE
synergy server must be restarted if client PC goes to "sleep" if ssl enabled. 

### ISSUE THREAD

**Issue by nmcwilli** [symless/synergy#5927] opened 2017-03-27 16:14 UTC
### Operating Systems ###

Server: microOS Sierra 10.12.3
Client: Windows 10 Version 1607 (OS Build 14393.0)

### Synergy Version ###

1.8.8-stable-c30301e (on both client and server)

### Steps to reproduce bug ###

After upgrading to PRO version of Synergy, I can't "wake up" my client OS anymore (when in sleep mode) until I go into Synergy on Server OS and do the following steps: 
1. Right click Synergy icon, hit Stop
2. Right click Synergy icon, Start server client again 
Then I'm able to wake the client OS after doing that. 

I never had this problem before when using Synergy Basic version, so perhaps related to SSL somehow? It's almost like once SSL connection severed between client and server, server can't wake client if in sleep mode until you stop server and restart it to create a new connection to client. 

### Other info ###

* When did the problem start to occur? Right after I upgraded to Synergy Pro. 
* Is there a way to work around it? Yes ... you can manually restart server.
* Does this bug prevent you from using Synergy entirely? No ... but its annoying!

**Comment by Dakine135** [comment] 2017-03-27 17:06
I also Confirm this bug, same steps to re-produce, same steps to fix, same frustration. Occasionally restarting with the gui won't work, and I have to stop and start the service in windows services (windows is hosting the server, macOS client)

**Comment by XinyuHou** [comment] 2017-03-30 12:13
Duplicate of #4857

**Closed by XinyuHou** 2017-03-30 12:13 UTC
