### ISSUE TITLE
Cursor jumps when crossing between screens on Linux server

### ISSUE THREAD

**Issue by edsantiago** [symless/synergy#4832] opened 2015-06-26 19:12 UTC
This is the same as issue 3029, which was closed without a fix.

Setup is a multihead X11 server with two screens, :0.0 and :0.1. Not Xinerama: each screen is separate. With synergys (1.4.2 - 1.6.3) running, low-speed transitions from one screen to the other cause the cursor to weirdly jump to unexpected places. High-speed transitions work as expected.

Example:

```
[other-computer]   [  0.0  ]   [ 0.1 ]
```

Moving the cursor from the left edge of 0.1 should cause a transition to the right edge of 0.0. This is how X11 handles it without synergy running. With synergys 1.4.2-1.6.3 running, the cursor jumps from 0.1-left to 0.0-left and then immediately to other-computer-right.

Workaround: using 1.4.2 sources, edit src/lib/platform/CXWindowsScreen.cpp , change CXWindowsScreen::detectXI2 to always return 0. Run this version on all your systems. This works fine. Unfortunately the same change to src/lib/platform/XWindowsScreen.cpp in 1.6.3 does not work: the cursor no longer moves to other-computer. It sticks on :0.0-left.

**Comment by XinyuHou** [comment] 2017-08-11 10:39
Duplicate of #6121

**Closed by XinyuHou** 2017-08-11 10:39 UTC
Labels: bug
