### ISSUE TITLE
Client can't detect United States (Apple) keyboard layout

### ISSUE THREAD

**Issue by johnweldon** [symless/synergy#5661] opened 2016-10-13 00:12 UTC
### Operating Systems ###

Client: Windows 7 Ultimate x64 (Version 6.1 Build 7601: Service Pack 1) (late 2011 macbook pro hardware)

Server: Windows 10 x64 (Version 1607 OS Build 14931.1000)

### Synergy Version ###

1.8.4 (Client/Server 1.8.4-stable-a6ff907)

### Steps to reproduce bug ###

1. Reboot client win 7 machine.
2. Keyboard and mouse work... log in.
3. After log in keyboard no longer works on client, but mouse still works.

### Other info ###

* **When did the problem start to occur?** Since I installed synergy on the client
* **Is there a way to work around it?** No
* **Does this bug prevent you from using Synergy entirely?** Pretty much.. all I can do is navigate and interact with the mouse, otherwise I have to use the client keyboard directly.

**Comment by johnweldon** [comment] 2016-10-13 22:27
I found a workaround which I think exposes the underlying issue; I believe that synergy doesn't support the `United States (Apple)` keyboard which Boot Camp uses once you're logged in.

## workaround

I turned on debugging on the client (Debug1), and saw this error message repeatedly:
`DEBUG1: can't get keyboard layouts`

I looked at the `Text Services and Input Languages` configuration panel:
`Control Panel` --> `Clock, Language, and Region` --> `Change keyboards or other input methods` (under Region and Language) --> `Keyboards and Languages` tab --> `Change keyboards` button --> `General` tab

I saw that the only keyboard installed was the `United States (Apple)` keyboard, which presumably synergy doesn't know about.

I added the `US` keyboard, and synergy began working again.  (Click the `Add` button, scroll down to `English (United States)` in my case, and check the `US` keyboard, and then click `OK`)

**Comment by XinyuHou** [comment] 2016-10-17 12:55
Duplicate of #5176

**Closed by XinyuHou** 2016-10-17 12:55 UTC
Labels: bug
