### ISSUE TITLE
Clicks not working while running certain games (EVE)

### ISSUE THREAD

**Issue by KiraAkashiya** [symless/synergy#5954] opened 2017-03-28 05:16 UTC
### Operating Systems ###

Server: Windows 10
Client: Mac OS 10.12.3

### Synergy Version ###

1.8.7

### Steps to reproduce bug ###

1. Launch EVE(Windowed mode) on server
2. Move mouse over to client
3. Unable to click on anything on the client

### Other info ###

* Is there a way to work around it? It fixes it self after server/client when into screensaver occasionally
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment] 2017-03-30 15:48
Duplicate of #5226

**Closed by XinyuHou** 2017-03-30 15:48 UTC
