### ISSUE TITLE
Extensive memory usage after copying big data multiple times

### ISSUE THREAD

**Issue by xhou-wavefin** [symless/synergy#5138] opened 2015-12-03 00:30 UTC
Problem: Synergy uses a huge amount of memory after copying big data and switching screens couple of times.

Solution: Find a solution to release some unused memory.

**Comment by james-fowler** [comment] 2015-12-11 16:08
I'm working on some clipboard issues, related to copy-paste from a remote screen into Eclipse/CDT.  Might be able to check on memory usage while I'm there.  Is this easily reproducible with a linux (Ubuntu 15.10) only synergy server/client setup?

**Comment by XinyuHou** [comment] 2015-12-11 16:59
@james-fowler 
It should be. But I don't know how to check the memory usage of a process on Linux.

To reproduce, you only need to copy some big data from one machine and paste it into another. Then copy another small one doesn't reduce the memory usage.

**Comment by james-fowler** [comment] 2015-12-11 18:58
By "release memory", are you talking about process memory (i.e., pages allocated from the OS) or C/C++ heap memory?   Even if you don't have any leaks,  process memory used by the C++ heap is challenging to release once it's been used.

**Comment by nyetwurk** [comment] 2015-12-11 19:01
If it is a simple alloc/free or new/delete problem, it should be easy to find with valgrind.

Like james-fowler says, if it is a heap issue, may not be possible to fix w/o redoing the way memory is allocated/freed for clipboard buffers

**Comment by james-fowler** [comment] 2015-12-11 20:27
I've added some diagnostic support for working with clipboards.  Currently it's only implemented for XWindows, and it's not as useful without the named pipe remote command mods I've been tinkering with, but when you put the two together you can say 

  ***jfowler@gcsea:~$*** **echo "dump_clipboards" > /tmp/SynRc**

which generates the following output from synergys:

```
[2015-12-11T15:13:40.424217849] NOTE: dumping clipboards : 7 active
[2015-12-11T15:13:40.424231047] NOTE:  1 (17XWindowsClipboard) :  time:16802440 id:0 selection:490 open:0 time:16802440 owner:0 timeOwned:14814708 timeLost:12880086 motif:0 checkCache:0 cached:1 cacheTime:14814708 replies:0 eventMasks:12 {{Text:"start_reading"},} 
[2015-12-11T15:13:40.424247605] NOTE:  2 (17XWindowsClipboard) :  time:16801941 id:1 selection:1 open:0 time:16801941 owner:1 timeOwned:16801941 timeLost:0 motif:0 checkCache:0 cached:1 cacheTime:14824082 replies:0 eventMasks:0 {{Text:"ned. When size is no..."},} 
[2015-12-11T15:13:40.424256920] NOTE:  3 (9Clipboard) :  open:0 time:0 owner:1 timeOwned:16802440 {{Text:"start_reading"},} 
[2015-12-11T15:13:40.424262821] NOTE:  4 (9Clipboard) :  open:0 time:16801941 owner:1 timeOwned:0 {{Text:"ned. When size is no..."},} 
[2015-12-11T15:13:40.424268639] NOTE:  5 (9Clipboard) :  open:0 time:0 owner:1 timeOwned:14838886 {{Text:"start_reading"},} 
[2015-12-11T15:13:40.424273891] NOTE:  6 (9Clipboard) :  open:0 time:0 owner:1 timeOwned:0 {{Text:"ned. When size is no..."},} 
```

Still somewhat primitive, but hopefully it will help track down some clipboard issues.

The code for this is at https://github.com/james-fowler/synergy/tree/FixClipboard

**Comment by XinyuHou** [comment] 2015-12-14 18:36
We use std string to store the clipboard data and there is no code to resize it when the clipboard is not necessary that big.

**Comment by james-fowler** [comment] 2015-12-14 19:21
You'd have to use a custom class with a custom allocator instead of std::string, which would be able to allocate (and then release) memory for large buffers using something like mmap() instead of the normal C++ heap.   This is certainly feasible, but it's substantially more complicated than using std::string, and might not be easy to do in a portable manner.  It's also easy to make things worse instead of better if you're not careful.

From the patterns I've observed under a Linux server / Linux client synergy setup, there aren't a lot of clipboard instances being created, and it should be reasonably practical to replace std::string with a buffer supporting custom allocation.  Haven't looked at the code for other platforms, nor do I currently have any of them setup with synergy (although I could get a Windows system hooked in easily enough).

Finally, if the platform's native windowing API does buffer allocation on your process heap when interacting with clipboard contents, that would probably still cause an issue no matter what the synergy code does.

**Comment by james-fowler** [comment] 2015-12-14 23:14
I may be missing something, but there appears to be at least one leak in the clipboard handling...  Looks like ***ClipboardChunk***s are getting created but never deleted.  They are passed as POD style data in an Event, so the 16 bytes or so of data (size_t + char \*) in the ***Chunk*** are probably getting ***free()***d, not deleted.  I'm not seeing any calls to ***Chunk::~Chunk()***, which implies the memory allocated and pointed to by ***m_chunk*** is not getting freed.    

There's definitely more going on than I'm aware of, but I'm pretty certain somethings wrong since I see chunk allocation messages but no chunk free messages with the following hack:

```c++
Chunk::Chunk(size_t size)
{
	m_chunk = new char[size];
	memset(m_chunk, 0, size);
	LOG((CLOG_INFO "Chunk @%p allocated %d bytes @%p", (void*)this, (int)size, (void*) m_chunk ));
}

Chunk::~Chunk()
{
	LOG((CLOG_INFO "Chunk @%p freeing bytes @%p", (void*)this, (void*) m_chunk ));

	delete[] m_chunk;
}
```

**Comment by james-fowler** [comment] 2015-12-14 23:54
I have a potential fix in http://github.com/james-fowler/synergy/commit/57b5c305062f2e48d08305a8c54aae660664369b - haven't tested it extensively yet but it appears to work and ClipboardChunk instances are getting properly destroyed.  It's a bit of a hack - added a second ***Event*** constructor which takes an ***EvenData*** pointer instead of a ***void*** pointer, and set's it as both m_data and m_dataObject,  combined with some extra logic in ***Event::deleteData*** to make sure it doesn't get deleted/freed twice.

Just FYI - the ***EventData*** class doesn't appear to be used in the X-Windows code, although I've been using them in my remote control plugin.  It is used quite a bit for Windows IPC stuff, for the IpcMessage - some of that code may not compile with the extra ***Event*** constructor until ambiguities are resolved ( which should be easy if you have a Windows dev system building synergy - I don't ).

**Comment by james-fowler** [comment] 2015-12-16 23:23
Has nobody ever run this with valgrind (as @nyetwurk  suggested) or some other memory leak tracking tool?   I just tried it out, and the results are not pretty.  There are quite a few leaks. Many are startup related and therefore, while aesthetically offensive, are not a serious issue because they only occur once.  However, there are a few that happen repeatedly - like every time the screen is switched with an active clipboard on the client. 

One problem is in *src/lib/client/Client.cpp* : **m_sendClipboardThread** gets set to **NULL** without first deleting **m_sendClipboardThread**.  That's a fairly easy fix.   Dealing with **ClipboardChunk** was a bit more involved, but both fixes are in my branch which I've merged with v1.7.6, check out the [most recent commits](https://github.com/synergy/synergy/compare/v1.7.6...james-fowler:master) for more detail. 

I'll see what else I can find now that I have it running under valgrind.

**Comment by james-fowler** [comment] 2015-12-17 01:26
Found a few more issues, everything is fixed in https://github.com/james-fowler/synergy
Limited testing looked promising, no repeating leaks, no repeating growth of process memory usage switching back and forth with big clipboards.

There is a new problem somewhere in my fork though, possibly related to merging in v1.7.6 - if I start the server (client already running), copy to clipboard on the server screen, then move to the client screen,  it crashes.  If I switch to the client screen first, copy something to the clipboard, then switch back, seems to work fine from then on.  I'll figure this out later, gotta go help the kids make Christmas cookies...

**Comment by james-fowler** [comment] 2015-12-17 17:17
Still tracking down the weird startup problem (seg fault in **ClientProxy1_6::handleClipboardSendingEvent**), but I'm not seeing any more non-startup leaks.  I might have gotten my branch into an odd state trying to merge v1.7.6,  so I figured out a simpler way to apply the changes on top of the current v1.7.6 branch:

    git fetch https://github.com/james-fowler/synergy.git james-fowler-master
    git cherry-pick 57b5c305062f2e48d08305a8c54aae660664369b
    git cherry-pick ae5754e63511a7736ef7bf03fc98cbf613b3b28e
    git cherry-pick a839240b001f6a1924d99063fe0e5743bac9ba20
    git cherry-pick 35a9a6c06e85bb2dc537eddf8c94910ae2803152
    git cherry-pick e51fab59acfe958c7cad91857763ce18e42c7e1c
    git cherry-pick -X theirs a8ca4ebea36773ade01e269384045167243df30d
    git cherry-pick a00a7077cd0e1e3e422a6a02f9a58285653aab1a
    sed -i 's/keepAlive();//' src/lib/client/ServerProxy.cpp

Tested this with a fresh v1.7.6 checkout and it appears to fix all the post-startup leaks valgrind was showing in both **synergys** and **synergyc** for XWindows.   The **-X theirs** / **sed** hack avoids a merge conflict.   You should be able build directly (assuming you could before...) after running the above commands.  So far I have not seen the server startup crash described earlier with the cherry-picked build.

Be aware that since some of the modifications are platform specific,  you'll need to make similar changes for the Windows/OSX platforms.  At a minimum, the platform-specifc clipboard classes will need to be changed, similar to XWindowsClipboard.h/XWindowsClipboard.cpp.  The changes are easy, I just don't have a system set up to test them yet.

**Comment by Cereal2nd** [comment] 2016-01-18 08:59
I also had the problem that synergy basically eats a lot of memory, with the version from james-fowler this is all solved.

Can we get this merged into the main stream?

**Comment by JPvRiel** [comment] 2017-09-10 11:57
Running 1.8.8-stable-25a8cb2 and seeing `synergys` process chew up almost 1GB of memory after just an hour use. Agree @james-fowler 's efforts need to get merged. It's anoying having 

I can confirm that placing an image in the copy paste buffer and moving the mouse between screens causes memory usage to increment.

![image](https://user-images.githubusercontent.com/9722317/30248829-8bfc4984-962f-11e7-9bb5-bc5a3b406010.png)

An obvious non-ideal workaround is to start and stop synergy...

**Comment by nbolton** [comment] 2024-09-06 22:04
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Closed by nbolton** 2024-09-06 22:04 UTC
Labels: enhancement, triage, unanswered
