### ISSUE TITLE
Client lose mouse click ability

### ISSUE THREAD

**Issue by bigswede74** [symless/synergy#5928] opened 2017-03-27 16:14 UTC
### Operating Systems ###

Server: Windows 10 Enterprise LTSB (Version 1607 (OS Build 14393.953))
Client: Windows 7 (Version 6.1 (Build 7601: Service Pack 1))

### Synergy Version ###

1.8.7-stable-9799e96

### Steps to reproduce bug ###

I loose mouse click ability on the client randomly. 

1. Click things on the client
2. Observe nothing happens
3. Move mouse to server
4. Click in desktop area on any server screen
5. Move mouse back to client screen
6. Mouse click now works

### Other info ###

* When did the problem start to occur? I see the issue a few times a day.
* Is there a way to work around it? Yes, listed above
* Does this bug prevent you from using Synergy entirely? No

**Comment by CaptainMESO** [comment] 2017-03-27 16:31
Exactly the same issue like described can be reproduced with newest version 1.8.8-stable-c30301e

**Comment by niklaswall** [comment] 2017-03-27 21:08
Same thing happens to me multiple times per day. I have not yet figured out what causes it.

I'm using W10 as server and Ubuntu as client.

**Comment by XinyuHou** [comment] 2017-03-30 15:39
Duplicate of #5226

**Closed by XinyuHou** 2017-03-30 15:39 UTC
