### ISSUE TITLE
Jittery mouse and keyboard on client, Massive latency when crossing the screen threshold. 

### ISSUE THREAD

**Issue by csbans** [symless/synergy#6028] opened 2017-05-04 08:30 UTC
Client OS: Ubuntu 16.04
Server OS: Windows 10 Home v1607

This bug is persistent in all scenarios on this setup. I have tried everything from messing with settings to completely clearing all synergy files and packages from both client and server. I do not know where to turn from here.  

There is an obscene amount of latency when I attempt to cross the boarder from my Windows 10 Machine to my Ubuntu Machine. For approximately 5-20 seconds after I cross the boarder to the client, both the mouse and keyboard are extremely responsive as they would normally be. But after that period, the client becomes practically unusable with many seconds passing before any keystrokes or mouse movements carries over. What do?

**Comment by XinyuHou** [comment] 2017-05-08 10:43
That sounds like a clipboard issue.
Please upgrade to 1.8.8 and disable clipboard in server settings.

Duplicate of #5531

**Closed by XinyuHou** 2017-05-08 10:43 UTC
