### ISSUE TITLE
Mouse clicks randomy stop working to transferred

### ISSUE THREAD

**Issue by makedir** [symless/synergy#5777] opened 2016-12-20 07:35 UTC
### Operating Systems ###

Server: Windows 10
Client: Windows 10

### Synergy Version ###

1.8.6-stable

### Steps to reproduce bug ###

1. random event
2. switch to client via hotkey
3. all mouse clicks not working
4. restart server service
5. working again

**Comment by prophoto** [comment] 2016-12-21 14:01
This happens to me often with W10 Server and macOS Sierra client. Mouse movements work fine but clicks stop working. I have found that I don't need to stop the service, but open the app which I have pinned to my taskbar (since it happens so often). Can we get a fix? I'm thinking it has something to do with process scheduling as I've noticed when my synergy server is under high load it will happen more often.

**Comment by mdiorio** [comment] 2016-12-28 20:31
Happens to me too - Win 10 server, OS X El Capitan client.

Clicks when entering the client don't work.  For me, just clicking anywhere back on the host, then back to the client and things work again for a while.

**Comment by XinyuHou** [comment] 2016-12-30 15:39
Duplicate of #5226

**Closed by XinyuHou** 2016-12-30 15:39 UTC

**Comment by makedir** [comment] 2017-01-26 04:09
Still not fixed with 1.8.7. This is just a joke.

**Comment by Cornfedhusker** [comment] 2017-01-28 20:09
Not a joke,  this is chronic. A year of waiting now for this to be fixed.   And we just close threads with the problem.  Sweep it under the rug.  Anyone know of a competing software? Im done waiting
