### ISSUE TITLE
Laggy mouse on Mac OS Sierra 10.12.2

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [symless/synergy#5804] opened 2017-01-18 15:25 UTC
### Operating Systems ###

Server: Windows 10 64bit
Client: Mac OS Sierra 10.12.2

### Synergy Version ###

1.8.6-stable-2ab21aa

### Steps to reproduce bug ###

Server is windows on HARDWIRED, Client is Mac on Wireless

Half the time I use mouse on mac, its very laggy/jumpy. keyboard sometimes freaks out.

Hardwired is NOT a solution/option. Wireless is fine (continuous speedtests are 238Mbps down, 11.67Mbps up) and internal continuous pings to router show no dropped packets (802.11ac, right next to router)

### Other info ###

Would like advise on how to make the client be more happy as the laggy mouse is quite irritating.

**Comment by Jeff-Shim** [comment] 2017-01-19 10:12
Does log show any kind of error like below? or any other error?
 ERROR: ssl error occurred (system call failure)
 ERROR: eof violates ssl protocol
 ERROR: failed to accept secure socket
 INFO: client connection may not be secure

**Comment by samling** [comment] 2017-01-20 23:23
I have this same issue on 1.8.7-stable-9799e96 with the same setup, Win 10 64bit server and MacOS Sierra 10.12.2 client. Server is hardwired, client is on a 5ghz wireless connection. I do see the errors that Jeff-Shim mentioned above when enabling encryption on the server. Since updating from 1.8.6 to 1.8.7 enabling encryption seems to spawn that error message endlessly on the server and the client is never able to connect. When running without encryption, the two can talk to each other, but I still get intermittent lag spikes from the mouse WITHOUT the error messages above (and no other error messages in the console).

**Comment by BrickerBrickerOneNine** [comment] 2017-01-23 17:12
The log has shown that, but other times it doesnt. Right now it doesnt, and the lagy is unbearable. Sometimes the lag is fine. Reallllly trying to avoid having to buy a USB-to-Ethernet adapter just to use this productively.

**Comment by Jeff-Shim** [comment] 2017-01-23 17:28
Does turning off SSL encryption remove that symptom? Just trying to find out a specific cause and compare with mine.

**Comment by samling** [comment] 2017-01-23 17:32
@Jeff-Shim No, at least not in my case. Turning off encryption actually enabled my client and server to talk to each other, with encryption on I was not able to establish a connection. However, the lagginess persists without SSL.

**Comment by Jeff-Shim** [comment] 2017-01-23 17:46
@samling Funny thing in my case is that it started working well with/without SSL just after I started to comment this issue 4 days ago. I've been using synergy since I need it on Ubuntu, but you can try [sharemouse](http://www.keyboard-and-mouse-sharing.com) which supports Windows and Mac before this issue gets more attention and corrected. This issue definitely needs deeper look.

**Comment by Jeff-Shim** [comment] 2017-01-23 17:50
#4132

**Comment by BrickerBrickerOneNine** [comment] 2017-01-23 19:05
I noticed that right after I made my comment earlier today, that It smoothed out. its been fairly smooth since. But randomly starts to be very bad. Theres no increase on internal traffic and packetloss internally is nonexistent as well as very little jitter (under 10ms)

**Comment by scottresnik** [comment] 2017-02-03 19:05
Similar issue here with a windows 10 x64 server, and macOS Sierra (10.12.2 and 3) client.  Both server and client are wired.  I've tried with the client on Wi-Fi as well.  It did not change things.

The following is in my server log:
```
[2017-02-03T13:02:56] INFO: OpenSSL 1.0.2 22 Jan 2015
[2017-02-03T13:02:56] INFO: accepted secure socket
[2017-02-03T13:02:56] INFO: AES256-GCM-SHA384       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(256) Mac=AEAD
[2017-02-03T13:02:56] NOTE: accepted client connection
[2017-02-03T13:02:56] NOTE: new client disconnected
```

I don't see anything in the client log.

**Comment by XinyuHou** [comment] 2017-02-28 17:41
Duplicate of #4132 

Please try the workaround mentioned here.
https://github.com/symless/synergy/issues/4132#issuecomment-248337317

**Closed by XinyuHou** 2017-02-28 17:41 UTC

**Comment by BrickerBrickerOneNine** [comment] 2017-02-28 18:39
that shutting down awdlan0 doesnt work. my friend is also experiencing this
over wifi from windows to windows. clearly there is a mouse lag issue.

**Comment by dongyado** [comment] 2017-08-05 02:21
Synergy_v1.9.0_rc3.dmg for mac os  and Synergy_1.9.0~rc3_amd64.deb for ubuntu worked for me, when I use 1.8.8 for mac os and ubuntu, there is a absolute lag on macbook,  now it is really smooth, thanks.
