### ISSUE TITLE
Investigate ways of improving CPU usage on Mac OS X

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#3224] opened 2014-10-13 06:44 UTC
**Imported issue:**
- Author: Nick Bolton
- Date: 2012-07-22 13:30:25
- Legacy ID: 3294

The `synergyc` process currently uses around 5-10%% in most cases, but in some cases uses 10%%-20%% of CPU. We should investigate ways of improving the CPU usage.

**Comment by XinyuHou** [comment] 2017-04-21 13:34
Duplicate of #5991

**Closed by XinyuHou** 2017-04-21 13:34 UTC
Labels: bug
