### ISSUE TITLE
Screen lock synchronization

### ISSUE THREAD

**Issue by wykydtronik** [symless/synergy#5256] opened 2016-03-26 19:59 UTC
With Mouse Without Borders, I was able to mouse over to my secondary computer and hit Win + L to lock both my secondary and primary PC's (both running Windows 10)

As a feature suggestion, would it be possible to allow all instances of Synergy to lock the screen if you where to use such a shortcut? I get up from my computer regularly and naturally I want everything locked before I walk away from my workstation.

### OSX 
If you enable password to be required on lock/screensaver/sleep it's
> Control + Shift + Power (or Eject)

### Windows
> Win Key + L

### uBuntu
> Ctrl + Alt + L

**Comment by nlyan** [comment] 2016-07-07 14:29
Duplicate of #3084

**Closed by nlyan** 2016-07-07 14:29 UTC
Labels: feature
