### ISSUE TITLE
Keymap issues when using non default keymap on OS X (as server)

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2869] opened 2014-10-13 06:05 UTC
**Imported issue:**
- Author: Erik Forsen
- Date: 2011-08-17 10:49:27
- Legacy ID: 2938

**Steps to reproduce:**  
1. Install dvorak layout from here: http://dump.doomtech.net/NorskDvorakMac.zip  
2. Set norwegian dvorak in input sources  
3. Run synergys on os x, synergyc on linux  

expected: ability to use norwegian characters on client (e.g. Æ)
actual: no norwegian characters on client  

OS X as server, Linux as client.  

When using Norwegian keymap on os x, I get expected keymap on linux, including norwegian characters ,,.   

When using norwegian dvorak keymap (custom installed keymap), I get the dvorak layout on linux, except the norwegian characters.   

xev on OS X reports the following on the norwegian characters:   

With norwegian keymap:  
: keycode: 47 (keysym 0xe6, ae)  
: keycode: 49 (keysym 0xf8, oslash)  
: keycode: 41 (keysym 0xe5, aring)  

With norwegian dvorak keymap:  
: keycode: 14 (keysym 0xe6, ae)  
: keycode: 58 (keysym 0xf8, oslash)  
: keycode: 20 (keysym 0xe5, aring)  

Xev running on linux (client):   

With norwegian layout:  

: keycode 48 (keysym 0xe6, ae)  
: keycode 47 (keysym 0x8f, oslash)  
: keycode 34 (keysym 0xe5, aring)  

With norwegian dvorak layout:  

Xev on the client doesn't receive any events on , ,  when using norwegian dvorak on the server  

**Versions (Synergy, OS):**  

Server: synergys-patched from this http://synergy-foss.org/pm/issues/57 #82 (without the patched version I didn't get any keyboard events at all on client). Running on OS X 10.7.1  

Client 1: 1.3.1 on Debian Lenny (latest available version that will run on lenny)  

**Workaround:**  

No

**Comment by XinyuHou** [comment] 2017-04-21 13:04
Duplicate of #4280

**Closed by XinyuHou** 2017-04-21 13:04 UTC
Labels: bug
