### ISSUE TITLE
Windows + L doesn't work on windows client with ubuntu host.

### ISSUE THREAD

**Issue by thezoid** [symless/synergy#5754] opened 2016-11-29 10:10 UTC
### Operating Systems ###

Server: Ubuntu Gnome 16.10
Client: Windows 10 v1607

### Synergy Version ###

1.8.5-stable-a18eba7

### Steps to reproduce bug ###

1. Move mouse to the client.
2. Press meta+L
3. the meta key is never sent, but the L key is sent, when it should activate the windows shortcut to lock screen.

Alternate:
1. Create a hotkey that uses the meta key combined with another key. 
2. Try it
3. Nothing happens, when the hotkey should execute.

### Other info ###

* When did the problem start to occur? Always
* Is there a way to work around it? I created an autohotkey script that runs on boot on my VM so when I press PAUSE, it will lock the screen.
* Does this bug prevent you from using Synergy entirely? No

This is pretty annoying. I don't know why this is happening, but I would really love to log out. Windows+E works, Windows+D works. synergyc and synergyd are running as SYSTEM. On ubuntu it is running as user, I don't think there's a way around that.

Alternately you could override this key combination and run this on the client when the mouse is in the client
rundll32.exe user32.dll,LockWorkStation
iirc the path for this varies depending on the system architecture

with that you can even have that long-requested feature of locking both at the same time. So when the server presses a set hotkey, like ctrl+alt+L on gnome, then you could tick an option in settings for this to run on client.

**Comment by XinyuHou** [comment] 2016-12-05 16:25
Duplicate of #4429

**Closed by XinyuHou** 2016-12-05 16:25 UTC
