### ISSUE TITLE
Mac OSX 10.12.2 build with qt 5.8.0_2

### ISSUE THREAD

**Issue by jmta** [symless/synergy#6004] opened 2017-04-20 09:43 UTC
### Operating Systems ###
Mac OSX 10.12.2

### Synergy Version ###

1.8.8

### Steps to reproduce bug ###

1. Follow the build instructions on the wiki
Issue 1
Wiki needs updating.
"brew install qt" installs qt version 5.8.0_2 meaning that the line of code needed to be added is in fact "/usr/local/Cellar/qt/5.8.0_2/Frameworks"

Issue 2 (Unresolved by myself) 
QT 5.8.0_2 has changed the layout, no longer is there a Contents folder in QtCore.framework as it was looking for before. There is now "Headers, QtCore, QtCore.prl, Resources, Versions". Within Resources there is an Info.plist. 
Attempted fixes
Change line 791 "frameworkRootDir + "/" + dir + "/Contents/Info.plist" to "frameworkRootDir + "/" + dir + "/Resources/Info.plist"
Output `Log:
Log: Deploying Qt frameworks found inside: ("/Volumes/Data/Downloads/synergy-1.8.8-stable/synergy/bin/Release/Synergy.app/Contents/MacOS/Synergy")
Log:  copied: "/usr/local/opt/qt/lib/QtWidgets.framework/Versions/5/QtWidgets"
Log:  to "Synergy.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets"
Log: copy: "/usr/local/opt/qt/lib/QtWidgets.framework/Resources" "Synergy.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources"
Log:  copied: "/usr/local/opt/qt/lib/QtWidgets.framework/Resources/Info.plist"
Log:  to "Synergy.app/Contents/Frameworks/QtWidgets.framework/Versions/5/Resources/Info.plist"
Log:  symlink "Synergy.app/Contents/Frameworks/QtWidgets.framework/QtWidgets"
Log:  points to "Versions/Current/QtWidgets"
Log:  symlink "Synergy.app/Contents/Frameworks/QtWidgets.framework/Resources"
Log:  points to "Versions/Current/Resources"
Log:  symlink "Synergy.app/Contents/Frameworks/QtWidgets.framework/Versions/Current"
Log:  points to "5"
Log:  copied: "/usr/local/opt/qt/lib/QtGui.framework/Versions/5/QtGui"
Log:  to "Synergy.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui"
Log: copy: "/usr/local/opt/qt/lib/QtGui.framework/Resources" "Synergy.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources"
Log:  copied: "/usr/local/opt/qt/lib/QtGui.framework/Resources/Info.plist"
Log:  to "Synergy.app/Contents/Frameworks/QtGui.framework/Versions/5/Resources/Info.plist"
Log:  symlink "Synergy.app/Contents/Frameworks/QtGui.framework/QtGui"
Log:  points to "Versions/Current/QtGui"
Log:  symlink "Synergy.app/Contents/Frameworks/QtGui.framework/Resources"
Log:  points to "Versions/Current/Resources"
Log:  symlink "Synergy.app/Contents/Frameworks/QtGui.framework/Versions/Current"
Log:  points to "5"
Log:  copied: "/usr/local/opt/qt/lib/QtCore.framework/Versions/5/QtCore"
Log:  to "Synergy.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore"
Log: copy: "/usr/local/opt/qt/lib/QtCore.framework/Resources" "Synergy.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources"
Log:  copied: "/usr/local/opt/qt/lib/QtCore.framework/Resources/Info.plist"
Log:  to "Synergy.app/Contents/Frameworks/QtCore.framework/Versions/5/Resources/Info.plist"
Log:  symlink "Synergy.app/Contents/Frameworks/QtCore.framework/QtCore"
Log:  points to "Versions/Current/QtCore"
Log:  symlink "Synergy.app/Contents/Frameworks/QtCore.framework/Resources"
Log:  points to "Versions/Current/Resources"
Log:  symlink "Synergy.app/Contents/Frameworks/QtCore.framework/Versions/Current"
Log:  points to "5"
Log:  copied: "/usr/local/opt/qt/lib/QtNetwork.framework/Versions/5/QtNetwork"
Log:  to "Synergy.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork"
Log: copy: "/usr/local/opt/qt/lib/QtNetwork.framework/Resources" "Synergy.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources"
Log:  copied: "/usr/local/opt/qt/lib/QtNetwork.framework/Resources/Info.plist"
Log:  to "Synergy.app/Contents/Frameworks/QtNetwork.framework/Versions/5/Resources/Info.plist"
Log:  symlink "Synergy.app/Contents/Frameworks/QtNetwork.framework/QtNetwork"
Log:  points to "Versions/Current/QtNetwork"
Log:  symlink "Synergy.app/Contents/Frameworks/QtNetwork.framework/Resources"
Log:  points to "Versions/Current/Resources"
Log:  symlink "Synergy.app/Contents/Frameworks/QtNetwork.framework/Versions/Current"
Log:  points to "5"
Log:
Log: Deploying plugins from "/usr/local/Cellar/qt/5.8.0_2/plugins"
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/platforms/libqcocoa.dylib"
Log:  to "Synergy.app/Contents/PlugIns/platforms/libqcocoa.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/platforms/libqcocoa.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport"
Log:  to "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport"
Log: copy: "/usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Resources" "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources"
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/lib/QtPrintSupport.framework/Resources/Info.plist"
Log:  to "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/Resources/Info.plist"
Log:  symlink "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/QtPrintSupport"
Log:  points to "Versions/Current/QtPrintSupport"
Log:  symlink "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/Resources"
Log:  points to "Versions/Current/Resources"
Log:  symlink "Synergy.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current"
Log:  points to "5"
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/printsupport/libcocoaprintersupport.dylib"
Log:  to "Synergy.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/bearer/libqcorewlanbearer.dylib"
Log:  to "Synergy.app/Contents/PlugIns/bearer/libqcorewlanbearer.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/bearer/libqcorewlanbearer.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/bearer/libqgenericbearer.dylib"
Log:  to "Synergy.app/Contents/PlugIns/bearer/libqgenericbearer.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/bearer/libqgenericbearer.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqgif.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqgif.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqgif.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqicns.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqicns.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqicns.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqico.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqico.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqico.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqjpeg.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqjpeg.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqjpeg.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqmacjp2.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqmacjp2.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqmacjp2.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqtga.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqtga.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqtga.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqtiff.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqtiff.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqtiff.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqwbmp.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqwbmp.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqwbmp.dylib")
Log:  copied: "/usr/local/Cellar/qt/5.8.0_2/plugins/imageformats/libqwebp.dylib"
Log:  to "Synergy.app/Contents/PlugIns/imageformats/libqwebp.dylib"
Log:
Log: Deploying Qt frameworks found inside: ("Synergy.app/Contents/PlugIns/imageformats/libqwebp.dylib")
Log: Created configuration file: "Synergy.app/Contents/Resources/qt.conf"
Log: This file sets the plugin search path to "Synergy.app/Contents/PlugIns"
Going back to: /Volumes/Data/Downloads/synergy-1.8.8-stable/synergy
bin/Release/Synergy.app
Entering dir: bin/Release/Synergy.app/Contents/Frameworks/QtCore.framework/Versions
Error: Destination path '5/Resources' already exists`

### Other info ###

An app is still created but when the app is opened the window opens but it blank, to be expected with a qt issue.

**Comment by jmta** [comment] 2017-04-20 10:03
Also just tried manually copying the Info.plist from Qt to the synergy app Resources folder in "Contents/Frameworks/QtCore.framework/Versions" as well as changing its name to Contents.  Also just tried changing line 779 to match 782, as I believe that will be the line running and qt version is > 4.

**Comment by jmta** [comment] 2017-04-20 10:04
#5719

**Comment by grigorovich** [comment] 2017-04-21 07:42
Same on MacOS 10.12.4 with qt 5.8.0_2. 
synergys synergyc works. But 'Synergy.app' failed

**Comment by jmta** [comment] 2017-04-21 07:46
'Same on MacOS 10.12.4 with qt 5.8.0_2.
synergys synergyc works. But 'Synergy.app' failed' 

If you run ./Synergy in the terminal, do you get a similar error?

**Comment by XinyuHou** [comment] 2017-04-21 12:08
Please try to compile v1.9 branch
Duplicate of #4572

**Closed by XinyuHou** 2017-04-21 12:08 UTC

**Comment by jayce-leathers** [comment] 2017-08-03 20:29
@XinyuHou 
Where are instructions on compiling the v1.9 branch? The hm.sh script is not on that branch so I'm assuming the directions in the wiki do not apply.
