### ISSUE TITLE
drag and drop files function has some problem

### ISSUE THREAD

**Issue by kndol** [symless/synergy#5717] opened 2016-10-31 14:52 UTC
### Operating Systems ###

Server: ms windows 10 1607(14393.351)
Client: macOS Sierra 10.2.1

### Synergy Version ###

1.8.5-stable-a18eba7 (nightly build)

### Steps to reproduce bug ###

1. Dragging files from Windows and drop to macOS problem:
When the name of directory on windows includes UTF-8(Korean) characters, the Synergy doesn't recognize the name, and fails to drag and drop files.

2. Dragging files from macOS and drop to Windows problem:
Drag files and move mouse to windows, files are copied to desktop of windows - mouse button is still pressed. I cannot copy files to drives or folders I want directly.

3. There is no overwrite message.
If the same names file already exist, the Synergy overwrites the file without any question nor information. I think this is dangerous.

### Other info ###

* Does this bug prevent you from using Synergy entirely? No

Put anything else you can think of here.

**Comment by piotrva** [comment] 2016-10-31 16:17
v1.8.5-rc1-b66043e, both Windows 7 x64, drag and drop not working - when "holding" file i am unable to switch screen.

**Comment by XinyuHou** [comment] 2016-12-05 12:21
Duplicate of #4376

**Closed by XinyuHou** 2016-12-05 12:21 UTC
