### ISSUE TITLE
Ctrl-(arrow) not being transmitted

### ISSUE THREAD

**Issue by Rimbo** [symless/synergy#5708] opened 2016-10-25 23:28 UTC
### Operating Systems

Server: MacOS 10.11.6
Client: macOS 10.12
### Synergy Version

1.8.4-stable-a6ff907
### Steps to reproduce bug

I've mapped ctrl-(left), ctrl-(right) and ctrl-(up) to be hotkeys. 
- If I type them on the client's keyboard, they work. 
- If I type them on the server's keyboard, they work. 
- But if I type them on the server's keyboard when the client is active, they do not work, and instead I see "[timestamp] INFO: found key in group 0" in the client's log. (The server log is silent.)
### Other info
- When did the problem start to occur? When I upgraded to macOS Sierra / latest Synergy
- Is there a way to work around it? Other than using the client's keyboard, not that I've discovered.
- Does this bug prevent you from using Synergy entirely? No.

Did you know that Dr. Wegeforth rode the first elephants brought to the San Diego Zoo from the docks? He had forgotten to arrange transportation from the dock, but being former circus elephants, they were willing to be ridden right down Broadway. Do you know how to get down from an elephant?

You don't. You get down from geese and ducks.

**Comment by rdamazio** [comment] 2016-10-27 04:43
+1, I also see this.
There are a few additional keys that don't get sent, such as F1-F12.

**Comment by rdamazio** [comment] 2016-10-27 04:45
Also, apparently this is a duplicate of issue 5592 .

**Comment by Rimbo** [comment] 2016-10-27 19:10
Yes, that looks like the exact same thing.

**Comment by future0906** [comment] 2016-10-28 08:20
1.8.4-stable +1.

It seen like keypress was sent, but not trigger any global hotkey function on OSx client.

**Comment by kndol** [comment] 2016-10-31 14:53
1.8.5-stable-a18eba7

the same problem.

**Comment by mssalvatore** [comment] 2016-11-11 16:12
1.8.5-stable-a18eba7 +1

Has anyone tried the 1.8.6 or 1.9.0 branches?

**Comment by future0906** [comment] 2016-11-23 08:04
For any one still care about this issue, please move to [issue#5592](https://github.com/symless/synergy/issues/5592).This is duplicate issue.
The nightly build fixed this issue.

**Comment by XinyuHou** [comment] 2016-11-25 17:04
Duplicate of #5592.

Please test this nightly
http://symless.com/nightly?filter=synergy-issue5592-ctrl-up-key-rc1-e8145aa-MacOSX-x86_64.dmg

**Closed by XinyuHou** 2016-11-25 17:04 UTC
