### ISSUE TITLE
Support pre-login support for Linux

### ISSUE THREAD

**Issue by lilHermit** [symless/synergy#5815] opened 2017-01-25 10:20 UTC
This currently isn't officially supported it would be good if you could supply scripts with the distribution. I have my own lightdm-wrapper scripts that work well and I'm happy to share.

**Comment by nlyan** [comment] 2017-01-25 15:22
That sounds cool, we'd love to see those scripts

**Comment by lilHermit** [comment] 2017-01-25 17:05
Follows is my Ubuntu config that I have used for years

```bash
#!/bin/bash

# This starts synergyc as root and then waits for the synergy client (which is started on login)
# once this is found it kills the root synergyc and itself
# the waiting is limited to 500 seconds so the script doesn't hang around forever 

SYNERGYC=$(which synergyc)

# don't continue if synergyc is already running
if [ "$(pgrep -fc ${SYNERGYC})" -gt 0 ]; then
    echo already running
    exit
fi

${SYNERGYC} --display :0 --profile-dir /home/scott/.synergy --no-tray --debug DEBUG --name dangermouse --enable-crypto --log /var/log/synergy.log 192.168.0.55:24800 &

sleep 2

# Grap the pid of the new process
PID=$(pgrep -f ${SYNERGYC})

echo "Waiting for synergy to be launched"
for i in {1..100}
do
  pgrep -x 'synergy$' && kill -9 "${PID}" && exit
  sleep 5
done
```
The above currently this exists in my bin dir as `synergyc.sh` and I have the following

```bash
#!/bin/bash

/home/lilhermit/bin/synergyc.sh &
```
in the same dir called `synergy-lightdm-wrapper.sh`

Then I have the following in `/etc/lightdm/lightdm.conf`
```bash
[SeatDefaults]
user-session=ubuntu
greeter-session=unity-greeter
greeter-setup-script=/home/scott/bin/synergy-lightdm-wrapper.sh
```

Everything then works with the following caveats (maybe you can fix them ;-) ) :

- You get no cursor in lightdm unless you have a physical mouse plugged
- The first key you press gets repeated so you have to delete the repeats.
- Then the next key you press doesn't register

**Comment by lilHermit** [comment] 2017-01-25 17:16
Obviously these scripts should live in system dir like `/usr/local/synergy/bin` rather than the users home dir

**Comment by XinyuHou** [comment] 2017-02-28 17:25
@lilHermit 
Thank you for sharing your solution.

We are planning to implement service on all platforms. One of the usages of having a service is to run Synergy on login page. So this ticket would be a duplicate of #4622

**Closed by XinyuHou** 2017-02-28 17:25 UTC
