### ISSUE TITLE
Three finger tap gesture broken on Mac client

### ISSUE THREAD

**Issue by hu6360567** [symless/synergy#4440] opened 2015-03-16 02:07 UTC
When I tried to have a three finger tap on a word in PDF. It doesn't work.
But three-finger drag is working fine.

**Comment by oxoxoxox** [comment] 2015-03-16 03:21
Ye Mine is too. RMBP Yosemite 10.10.2, Synergy 1.6.2, three-finger-tap is not working when Synergy start running. No print about three-finger-tap in synergy log. I guess Synergy just ignored the three-finger-tap message.

**Comment by nbolton** [comment] 2015-03-22 16:17
I'm guessing this happens on Mac client?

**Comment by hu6360567** [comment] 2015-03-23 02:27
@nbolton Yes, on Mac Client. I have never tried when Mac is server.

**Comment by nbolton** [comment] 2015-03-23 08:20
@hu6360567 Thanks!

**Comment by XinyuHou** [comment] 2017-04-21 15:58
Duplicate of #2905

**Closed by XinyuHou** 2017-04-21 15:58 UTC
Labels: bug
