### ISSUE TITLE
Clipboard stops functioning copying text from Win8.1 client to Ubuntu 16.10 server

### ISSUE THREAD

**Issue by halifornia** [symless/synergy#5937] opened 2017-03-27 18:29 UTC
### Operating Systems ###
Server: Ubuntu 16.10
Client: Windows 8.1 Enterprise

### Synergy Version ###
Wndows 8.1 - 1.8.8-stable-25a8cb2
Ubuntu 16.10 - 1.8.8-stable-25a8cb2

### Steps to reproduce bug ###
1. Boot up server (Ubuntu 16.10)
2. Boot up client (Windows 8.1 Enterprise)
3. Highlight a string of text on the client (such as a URL)
4. Move the cursor to the server, and attempt to paste the URL
Result: The cross-system clipboard is empty
Workaround: Halt and restart synergy on the client, re-copy the string, and paste on the server side
Frequency: 100% upon boot - after stopping and restarting the client, the clipboard works for anywhere from 15-45 minutes before client must be restarted again - unclear if leaving either system idle exacerbates issue

### Other info ###
* When did the problem start to occur?
     Occurred on my previous version of synergy (1.7.something) and is still present on the latest version - 100% reproducible
* Is there a way to work around it?
    Yes, I can stop and restart the client, but this is a lot of overhead to copy a single line of text.
* Does this bug prevent you from using Synergy entirely?
    No, but it does make it significantly less efficient

**Comment by XinyuHou** [comment] 2017-03-30 12:21
Duplicate of #4125

**Closed by XinyuHou** 2017-03-30 12:21 UTC
