### ISSUE TITLE
Server IP address is not updated until App is relaunched

### ISSUE THREAD

**Issue by rakesh529** [symless/synergy#5970] opened 2017-04-03 15:53 UTC
### Operating Systems ###

Server: MACBook Pro 10.12.1
Client:  Win 7, Dell Desktop

### Synergy Version ###

1.5.1

### Steps to reproduce bug ###

1. My environment consists of (OS X as server and Win as Client) and every morning when I come back to the office from home, My setup won't work.
Reason: Wi-fi IP address won't refresh on its own(on Mac machine, server)

Workaround:
1. Relaunch synergy App and find out new IP address
2. Provide new IP address on client side and everything works fine

Expected behavior:
1. Wifi address should refresh automatically when network is changed

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by xpac1985** [comment] 2017-04-04 17:53
Your Synergy version is, like, super old. Did you try updating to 1.8.8?

**Comment by XinyuHou** [comment] 2017-04-06 12:12
Duplicate of #4275

**Closed by XinyuHou** 2017-04-06 12:12 UTC
