### ISSUE TITLE
Cyrillic  keyboard layout on server sends '?' chars

### ISSUE THREAD

**Issue by nbolton** [symless/synergy#2914] opened 2014-10-13 06:10 UTC
**Imported issue:**
- Author: Sergei Ledovskij
- Date: 2011-09-29 16:15:01
- Legacy ID: 2983
- Version: 1.3.6

**Steps to reproduce:**  
1. Server runs 3 layouts  
2. US  
3. Finnish  
4. Russian phonetic (self-made)  
5. Client runs same layouts, with same switching hot-keys  
6. On server switching from US -> Finnish  
   3.1. Able to write in Finnish layout on server  
   3.2 Able to write in Finnish layout on client  
7. On server switching US -> Russian  
   4.1 Able to write in Russian layout on server  
   4.2 _Not_ able to write in Russian layout on client (spec. characters, and numbers work; Cyrillic letters are represented as "?")  

Expected: All layouts to switch  
Actual: 2/3 layouts switch properly  

**Versions (Synergy, OS):**  

Server: 1.3.6  
Client 1: 1.3.6  

**Comments:**  

have tried latest beta, older beta, latest stable, older stable. before the merge, and after.  

found similar topics in issue tracker (old and new), still not able to resolve.  
apologize if possibly going blind here, but not able to find a resolution through self-research or troubleshooting.

**Comment by the-wes** [comment] 2015-04-01 23:29
Reopening this one since https://github.com/synergy/synergy/issues/5 was closed in favor of more specific issue reports.

**Comment by k0dek0mmand0** [comment] 2017-03-27 21:52
A similar issue is found on Windows 10 ->Windows 10 setup (synergy `1.8.7-stable`) with US/Slovenian keyboard layout combo. The letters `š`, `đ`, `ž`, and `ć` are transmitted to the client correctly, while the letter `č` is transmitted as `c` when layout is switched to Slovenian.

**Comment by danislav** [comment] 2017-03-29 14:29
For me everything was working ok with the free version.
Since I upgraded to "Pro" version the Cyrillic is broken and I can't type... :( 
Please, can you check this out?

More info:
Server EN, client EN: ok, 
Server EN, client Cyrillic: types Latin. With the free version this was working.
Server Cyrillic, client Cyrillic: types ?????

**Comment by XinyuHou** [comment] 2017-04-21 13:05
Duplicate of #4280

**Closed by XinyuHou** 2017-04-21 13:05 UTC
Labels: bug

**Comment by jsaveljevs** [comment] 2021-07-21 14:02
How is this still a thing in 2021? 

#4280 is just locked with nothing happening for years. 
Is there anything I (as a reporter affected by this problem) can help you with? What's an estimated resolution plan for this issue?

**Comment by jsaveljevs** [comment] 2021-07-21 14:06
btw, my setup is

server: Windows 10 19042.1110, Synergy v1.14.0
client: macOS 11.4 (M1), Synergy v1.14.0
