### ISSUE TITLE
Consistent cursor lag on Windows 10 Pro (Client)

### ISSUE THREAD

**Issue by ZeroNanuk** [symless/synergy#6055] opened 2017-06-05 07:25 UTC
### Operating Systems ###

Server: Windows 10 Pro Version 1703 Build 15063.296
Client: Windows 10 Pro Version 1703 Build 15063.296

### Synergy Version ###
Tried 
synergy-v1.8.8-stable-25a8cb2-Windows-x64 
and 
Synergy-1.9.0_rc3-1.x86_64

### Steps to reproduce bug ###

Consistently Laggy.

### Other info ###

Started a week ago and I tried migrating to Synergy-1.9.0_rc3-1.x86_64. It is still consistently laggy when I move the mouse from the the server screen to the client. I am referring to cursor lag as well as keyboard delay when I'm typing. On average it takes up to 10-15 second for keyboard input to register. I've tried opening ports for the server IP address on the router as well as allowing Synergy.exe, Synergyc.exe, Synergyd.exe and Synergys.exe through on outgoing and incoming of the firewall on both computers. 

Ping to the server is < 1ms
Ping to the client is 12ms-38ms

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by XinyuHou** [comment] 2017-06-06 13:35
@ZeroNanuk 
Have you tried this build?
https://symless.com/forums/topic/2587-download-synergy-190-to-fix-the-wifi-macos-bug/

**Comment by ZeroNanuk** [comment] 2017-06-13 02:48
Hello Jerry,


Yes that is the build I am currently using.

________________________________

**Comment by XinyuHou** [comment] 2017-06-30 15:23
Duplicate of #4417

**Closed by XinyuHou** 2017-06-30 15:23 UTC
