### ISSUE TITLE
Client doen't stop but button changed from start to stop.

### ISSUE THREAD

**Issue by alantprice** [symless/synergy#5520] opened 2016-08-02 15:42 UTC
Ubuntu 16.04 Server,  Mac 10.11.6 client.

After setting up and testing as best I could 1.8.2.-rc1-12e0120 I stopped synergy on the client the window says, "Synergy is not running." and the button says start, but I am still able to use the mouse and keyboard on the client.

The clients log has stopped, the servers log continues .

[synergy_linux_deb_64_server.txt](https://github.com/symless/synergy/files/397411/synergy_linux_deb_64_server.txt)
[synergy_mac_client.txt](https://github.com/symless/synergy/files/397419/synergy_mac_client.txt)

**Comment by XinyuHou** [comment] 2016-08-02 16:12
Duplicate of #5408

**Closed by XinyuHou** 2016-08-02 16:12 UTC
