### ISSUE TITLE
Laggy Synergy to a point where it's unusable (Mac OS)

### ISSUE THREAD

**Issue by bryancaporicci** [symless/synergy#5575] opened 2016-08-30 13:51 UTC
I've been using Synergy for quite some time, but after updating this morning, I was experiencing a lot of lag between my iMac and my Macbook Pro. It's completely unusable. 

UPDATE: Turns out it had nothing to do with updating. I tried downgrading and still had the lag.

**Comment by nlyan** [comment] 2016-08-30 15:24
Hi,

We need a bit more information. Could you tell us what version you were using previously and what version you are using now? Also confirm whether you are using OS X 10.11 or a prior version, and whether there are any particular causes of the lag, or when it occurs

Thanks

**Comment by cyberea** [comment] 2016-09-05 14:23
Hello I am new to Synergy. I purchased a licence a few weeks ago and have been having these laggy problems. I am using a **Mac Pro (Late 2013)** and a **MacBook (Retina, 12-inch, Early 2016)** both with **MacOS 10.11.6**.

I have Synergy **1.8.2-stable-36cd521** on both machines. The MacBook is running as server and connected to network via wifi the Mac Pro as client connected to network via ethernet.

I thought it might be a connection issue, but I see nothing indicated in either the server or client Synergy log. I have tested the performance of the wifi connection separately also and do not see any issues.

**Comment by bryancaporicci** [comment] 2016-09-09 12:50
FYI Looks like I have a very similar set up to @cyberea - My iMac (the "server" in Synergy) is connected to the network via Ethernet, and the MacBook Pro is connected via WiFi.

**Comment by nlyan** [comment] 2016-09-12 09:43
At the moment we can't say this is an issue with Synergy itself, although we have had some other reports of lag in 1.8.x.

**Comment by XinyuHou** [comment] 2016-09-19 17:31
Duplicate of #4132

**Closed by XinyuHou** 2016-09-19 17:31 UTC
