### ISSUE TITLE
Client lost after PRO activation because SSL encription enabled

### ISSUE THREAD

**Issue by QuAzI** [symless/synergy#5867] opened 2017-03-02 16:16 UTC
### Operating Systems ###

Client: Debian 3.4.113-sun8i

### Synergy Version ###

1.8.8-stable-c5b83ce

### Steps to reproduce bug ###

I build deb package from sources and install. After activation to "PRO" version client lost because "SSL encription" enabled by default. In other machines include server (where Synergy used long time and installed from official site) SSL encription disabled.

**Comment by XinyuHou** [comment] 2017-03-08 12:12
Duplicate of #5898

**Closed by XinyuHou** 2017-03-08 12:12 UTC
