### ISSUE TITLE
Support multiple monitors with different DPI scaling

### ISSUE THREAD

**Issue by jeffboulanger** [symless/synergy#5146] opened 2015-12-09 19:06 UTC
Log for reference: http://pastebin.com/CNHNtWde

3 Monitor setup on server (right to left):
1920x1080 100% 
1920x1080 100%
2560x1440 175%

Client 1 monitor 1680x1050

**Comment by ebalsumgo** [comment] 2015-12-09 19:35
I am guessing my problem is the exact same as this. I have 3 monitor setup 2 with the same resolution and DPI and 1 with different. cc #5030

**Comment by jeffboulanger** [comment] 2016-03-21 16:25
Any ideas on when this will be included?

**Comment by georgestephanis** [comment] 2016-03-31 17:27
Also eager for this.  My Synergy Server (Surface Book) has a 2000x3000@200% display, and a 4K@150% display.  Mouse literally cannot get to the left half of my Surface Book screen when Synergy is connected.

**Comment by jeffboulanger** [comment] 2016-08-09 15:55
Guys this is becoming a norm, any word on when we can expect this feature, haven't been able to use Synergy since I posted created this issue :(.

**Comment by ahubbard** [comment] 2016-08-15 21:16
@jeffboulanger I use by setting one screen on top of each other.  nowhere near as good as side-by-side, but usable at least.

**Comment by jeffboulanger** [comment] 2016-08-15 21:18
@ahubbard To many monitors for that, but good work around for others, thanks!  I would still like to see this fixed.

**Comment by stefanflegg** [comment] 2016-08-18 06:35
I'd like to see this also. I'm struggling to use this between two Surface tablets with different external monitors (4K and QHD) with different scaling factors.

**Comment by XinyuHou** [comment] 2016-10-28 13:46
Can someone test this nightly please?
http://symless.com/nightly?filter=issue5186-different-dpi-rc1-8d193c7

**Comment by XinyuHou** [comment] 2016-10-28 13:47
Duplicate of #5186

**Closed by XinyuHou** 2016-10-28 13:47 UTC
Labels: enhancement
