### ISSUE TITLE
Trackpad scrolling too fast on Windows

### ISSUE THREAD

**Issue by OmgImAlexis** [symless/synergy#5781] opened 2016-12-26 12:41 UTC
### Operating Systems ###

Server: MacOS Siera
Client: Windows 10 Pro

### Synergy Version ###

1.8.6-stable-2ab21aa

### Steps to reproduce bug ###

1. Move cursor to Windows
2. Scroll down a page

### Other info ###

* When did the problem start to occur? As far as I can remember this has always been an issue, I stopped using Synergy about a year ago because of this.
* Is there a way to work around it? Not that I know of.
* Does this bug prevent you from using Synergy entirely? Yes and no.

I believe this has todo with how OSX handles trackpad scrolling and how they've implemented "smooth scrolling". On Windows the scrolling accelerates as I move my fingers up and down the trackpad where as on OSX it just moves the page smoothly.

**Comment by OmgImAlexis** [comment] 2016-12-26 13:40
Seems this is related to https://github.com/symless/synergy/issues/2631

**Comment by XinyuHou** [comment] 2016-12-30 15:35
Please try this nightly

http://symless.com/nightly?filter=synergy-issue5604-choppy-scrolling-rc2-f03a03a

**Comment by OmgImAlexis** [comment] 2016-12-31 02:15
That significantly helps. It does now feel like while scrolling I'm going down the page a single line/line section at a time if that makes sense. This is at least usable now.

**Comment by OmgImAlexis** [comment] 2016-12-31 02:18
Okay I think I know the issue. On OSX the scrolling "flows" to a stop where as on Windows it seems to just HALT where the end line is. I'm not sure if this is a Windows thing or something Synergy can fix.

**Comment by XinyuHou** [comment] 2017-02-28 14:45
@OmgImAlexis 
> OSX the scrolling "flows" to a stop where as on Windows it seems to just HALT where the end line is.
I'm sorry I can't picture this. But it sounds like a OS specific thing. If you are not sure, please compare with your local input device and let us know.

I will close this ticket as it's a duplicate of #5604.

**Closed by XinyuHou** 2017-02-28 14:45 UTC
