### ISSUE TITLE
Compiled from source, "Use SSL encryption" is greyed out

### ISSUE THREAD

**Issue by HunterGraubard** [symless/synergy#6098] opened 2017-07-08 23:19 UTC
### Operating Systems ###

Server: Windows 10 Pro Version 1703 Build 15063.447

### Synergy Version ###

1.8.8-stable-c30301e

### Steps to reproduce bug ###

1. Compile Synergy.
2. Install Synergy.
3. Run Synergy.
4. Go to Edit -> Settings.
5. "Use SSL Encryption" is greyed out.

What am I supposed to do to get this working? Isn't this supposed to be completely free software, with only the pre-compiled binaries paid for? The software still seems to ask for a serial key for activation...

**Comment by andrewkho** [comment] 2017-07-10 08:49
On OSX I observe this issue both with master and v1.9 branch. However on Debian Stretch, master branch, encryption is working. 

When compiling synergy on OSX I can see it searching and linking for the openssl libraries, however no matter what happens it does not seem to activate it.

**Comment by andrewkho** [comment] 2017-07-10 15:42
I don't know if this is good form, but a viable workaround is to create your own ssl tunnel (using stunnel) and connect through the tunnel.

**Comment by cardonator** [comment] 2017-07-11 21:21
You need to make code changes to disable the license check for encryption.

https://github.com/symless/synergy/pull/5944

**Comment by XinyuHou** [comment] 2017-07-14 11:50
Duplicate of #5810

**Closed by XinyuHou** 2017-07-14 11:50 UTC
