### ISSUE TITLE
Using mouse/keyboard on client doesn't prevent the screensaver on server to start

### ISSUE THREAD

**Issue by NoICE** [symless/synergy#5830] opened 2017-02-04 00:51 UTC
### Operating Systems ###

Server: macOS Sierra 10.12.3 (16D32)
Client: Windows 10 1607

### Synergy Version ###

1.8.7 on both server and client.

### Steps to reproduce bug ###

1. Move mouse to Windows (client) computer and start chatting with your buddies on Steam, using your beautiful mac keyboard.
2. Happily type and type and type on the client.
3. Server (macOS) starts screensaver. What?
4. See your input interrputed, as you are watching the mac taking over your keyboard and you are now typing your love letters to the login screen's password input.

### Other info ###

* When did the problem start to occur? When I... *always*.
* Is there a way to work around it? No/Yes, you can... disable screensaver. 
* Does this bug prevent you from using Synergy entirely? Yes/No No, but it's very annoying.

Please follow the link below to send us logs from both your server and client sides if it's appropriate. https://github.com/symless/synergy/wiki/Sending-logs

Put anything else you can think of here.

**Comment by NoICE** [comment] 2017-02-14 18:46
This is VERY annoying. Can you please take a look at it?

**Comment by XinyuHou** [comment] 2017-02-28 18:09
Duplicate of #5839

**Closed by XinyuHou** 2017-02-28 18:09 UTC

**Comment by NoICE** [comment] 2017-02-28 18:13
This ticket is technically older, so #5839 is a (less detailed) duplicate of this one, but that doesn't matter, as long as there is at least one ticket hanging aroud ;)
