### ISSUE TITLE
"Alt Gr" key not working between Linux and Windows

### ISSUE THREAD

**Issue by LionelTricon** [symless/synergy#5723] opened 2016-11-02 12:14 UTC
### Operating Systems ###

OpenSuse Linux 42.1 on master side
Windows 7 on slave side

### Synergy Version ###

synergy-1.8.5-1 under Linux (recompiled from Git)
1.8.5-stable-a18eba7

### Steps to reproduce bug ###

When i want to access @ \ | characters etc ... using "Alt Gr" on the Linux side with the keyboard, it's not working at all. Nothing seems transmitted from Synergy Linux to Synergy Windows.

### Other info ###
A little boring since i have to use the Windows keyboard to type these special characters :) Which is not very practical.

**Comment by LionelTricon** [comment] 2016-11-03 08:20
Notice that i use a french keyboard (AZERTY).

**Comment by LionelTricon** [comment] 2016-11-03 09:47
`[2016-11-03T10:37:45] DEBUG1: event: KeyPress code=108, state=0x0010
[2016-11-03T10:37:45] DEBUG1: onKeyDown id=61310 mask=0x2000 button=0x006c
[2016-11-03T10:37:45] DEBUG1: send key down to "Lionel-PC" id=61310, mask=0x2000, button=0x006c
[2016-11-03T10:37:46] DEBUG1: new mask: 0x2020
[2016-11-03T10:37:46] DEBUG1: event: KeyPress code=19, state=0x0090
[2016-11-03T10:37:46] DEBUG1: onKeyDown id=64 mask=0x2020 button=0x0013
[2016-11-03T10:37:46] DEBUG1: send key down to "Lionel-PC" id=64, mask=0x2020, button=0x0013
[2016-11-03T10:37:46] DEBUG1: new mask: 0x2020
[2016-11-03T10:37:46] DEBUG1: event: KeyRelease code=108, state=0x0090
[2016-11-03T10:37:46] DEBUG1: new mask: 0x2000
[2016-11-03T10:37:46] DEBUG1: event: KeyRelease code=19, state=0x0010
[2016-11-03T10:37:46] DEBUG1: onKeyUp id=61310 mask=0x2020 button=0x006c
[2016-11-03T10:37:46] DEBUG1: send key up to "Lionel-PC" id=61310, mask=0x2020, button=0x006c
[2016-11-03T10:37:46] DEBUG1: onKeyUp id=224 mask=0x2000 button=0x0013
[2016-11-03T10:37:46] DEBUG1: send key up to "Lionel-PC" id=224, mask=0x2000, button=0x0013
`

Code 108 = Alt Gr
Code 19 : 0 à @ (french keyboard)

What i expect:
Code 50 (Shift) + Code 19 = 0 (working)
Code 19 = à (working)
Code 108 (Alt- Gr) + Code 19 = @ (not working, nothing at all)

**Comment by Upgreydd** [comment] 2016-11-04 08:37
Confirmed.
Arch Linux server + Windows 7 Client
added in screens: client: line "alt = altgr"
Now to write special chars like "ąśćńłóżź" i need to push left ctrl + right alt. That should work without ctrl.
Without added line it doesn't work at all

**Comment by tperalta82** [comment] 2016-11-20 02:10
Alfter reading through the code, and trying some settings, it seems that ubuntu messes up a little with xmodmap

after messing a bit with settings and reading through code, and using the debug option

instead of adding alt = altgr to the config file, I found that instead adding 

altgr = shift works on my case (with portuguese layout)

Here is my full config file both with mouse wwwback/front and altgr working

section: screens
	Windows:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
        altgr = shift
	Optimus:
		halfDuplexCapsLock = false
		halfDuplexNumLock = false
		halfDuplexScrollLock = false
		xtestIsXineramaUnaware = false
		switchCorners = none 
		switchCornerSize = 0
end

section: links
	Optimus:
		right = Windows
	Windows:
		left = Optimus
end

section: options
	relativeMouseMoves = true
	screenSaverSync = true
	win32KeepForeground = false
	switchCorners = none 
	switchCornerSize = 0
    mousebutton(6) = keystroke(WWWBack)
    mousebutton(7) = keystroke(WWWForward)
	keystroke(Control+Shift+Right) = switchToScreen(Windows)
	keystroke(Control+Shift+Left) = switchToScreen(Optimus)
	keystroke(Shift+Control+F1) = lockCursorToScreen(toggle)
end

**Comment by pproba** [comment] 2016-11-22 14:36
I'm also seeing this issue on RHEL7.2 (server) and Windows 7 Enterprise (client) after updating to 1.8.5-stable-a18eba7 x64 (server) and 1.8.5-stable-a18eba7 x64 (client).

With the previous versions, the workaround "altgr = alt" worked without any issues. With the update, the AltGr key stopped working. Removing the workaround or changing it to "alt = altgr" didn't help either.

I've had to downgrade my client back to 1.7.5 in order to fix the issue.

**Comment by tperalta82** [comment] 2016-11-22 14:39
@pproba  Out of curiosity, can you try altgr = shift ?

**Comment by veretcle** [comment] 2016-12-01 15:02
Same problem than @Upgreydd here with the same configuration.

altgr = shift just makes some keys works but not all (€ work œ not).

**Comment by XinyuHou** [comment] 2016-12-05 16:59
Duplicate of #4411

**Closed by XinyuHou** 2016-12-05 16:59 UTC
