### ISSUE TITLE
 ERROR: ipc connection error, code=7

### ISSUE THREAD

**Issue by idealife** [symless/synergy#6091] opened 2017-06-28 03:23 UTC
### Operating Systems ###
Server: Window8
Client: MacOS 10.9.5

### Synergy Version ###
1.8.8-stable-c30301e

### Steps to reproduce bug ###
After I cleared the Windows System by some tools, Synergy server's console printed the error: ERROR: ipc connection error, code=7. 
The Client cann't connect the server.

### Other info ###
[2017-06-28T11:19:44] ERROR: failed to launch, error: process immediately stopped
[2017-06-28T11:19:44] INFO: backing off, wait=10s, failures=43
[2017-06-28T11:19:54] INFO: starting new process
[2017-06-28T11:19:54] INFO: activeDesktop:Default

[2017-06-28T11:19:54] INFO: starting new process
[2017-06-28T11:19:54] INFO: drag and drop enabled

synergys.exe: no configuration available

**How can I  fix this problem?
 I known there is some error config in my windows system。**

**Comment by nlyan** [comment] 2017-06-30 14:07
Duplicate of #3380

**Closed by nlyan** 2017-06-30 14:07 UTC
