### ISSUE TITLE
Synergy Mutual Authentication issue

### ISSUE THREAD

**Issue by CMCDragonkai** [symless/synergy#5895] opened 2017-03-07 06:05 UTC
Just bought the pro version of synergy.

If the server has crypto enabled (I did this on Windows with the settings checkbox enable SSL), does this mean the clients must also have crypto enabled? My synergyc client running on Linux (compiled from a package manager) currently shows "crypto disabled because of ns plugin not available" when I use `--crypto-enable`. If I enable it, the client times out on connection.

I have to disable SSL on the server, and then allow the client to connect.

From the documentation on Archlinux, it appears there's a way to perform mutual authentication? Can the client authenticate against the server, and server authenticate against the client? One way to do this is through client certificates and server certificates. There should be a setting where the server can state what client certificates to accept, and for the client which server certificates to accept.

For now I'm afraid that any client can connect to my server, as long as they know my desired synergy screen name and the synergy port.

**Comment by yupi2** [comment] 2017-03-07 07:35
Nix uses an [old Synergy version (1.7.6)](https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/applications/misc/synergy/default.nix) so that's why you're getting the disabled crypto plugin message.

The ability for any client to connect to the server is definitely not a good thing but the worst that will happen currently is the leaking of clipboard data or causing the server to crash (it's buggy code).

**Comment by XinyuHou** [comment] 2017-03-08 13:58
@CMCDragonkai 
Please compile the latest stable release on Linux to use SSL. Please also use GUI the enable SSL.

Duplicate of #5898

**Closed by XinyuHou** 2017-03-08 13:58 UTC
