### ISSUE TITLE
Dialog to suggest disabling SSL on non-SSL client

### ISSUE THREAD

**Issue by speaker** [symless/synergy#4541] opened 2015-04-16 18:01 UTC
1.7 clients come with SSL pre-enabled (check-box checked)
If a pre-1.7 server is running with encryption enabled, both the server and client need to be manually changed in order for the connection to work. The only option is then no encryption.

It would be helpful if starting at 1.7, the client were able to know it's talking to a pre-1.7 server and present a window asking to disable SSL (temporarily or "dont ask again") and attempt to connect.

In the future a hand-shake that both the server and client can understand would be helpful to line up capabilities.

**Comment by XinyuHou** [comment] 2017-03-08 12:12
Duplicate of #5898

**Closed by XinyuHou** 2017-03-08 12:12 UTC
Labels: enhancement
