### ISSUE TITLE
Modifier keys (CTRL) doesn't work on Mac

### ISSUE THREAD

**Issue by lparsons** [symless/synergy#5759] opened 2016-12-01 20:09 UTC
### Operating Systems ###

Server: Mac OS X 10.11.6
Client: macOS 10.12.1 

### Synergy Version ###

1.8.5-stable-a18eba7

### Steps to reproduce bug ###

1. on client, type CTRL -> or CTRL <-
2. Synergy console on client shows: `INFO: found key in group 0
[2016-12-01T15:08:31] INFO: found key in group 0`

### Other info ###

* The problem started when I upgraded the client machine from OS X 10.11 to macOS 10.12
* Is there a way to work around it? No
* Does this bug prevent you from using Synergy entirely? No

**Comment by XinyuHou** [comment] 2016-12-05 16:44
Duplicate of #5592

**Closed by XinyuHou** 2016-12-05 16:44 UTC
