### ISSUE TITLE
Clipboard share not working from server to client

### ISSUE THREAD

**Issue by makedir** [symless/synergy#5776] opened 2016-12-19 09:26 UTC
### Operating Systems ###

Server: Windows 10
Client: Windows 10

### Synergy Version ###

1.8.6-stable (no ssl)

### Steps to reproduce bug ###

1. copy txt/link on server pc
2. move to client via hotkey
3. no stored clipboard from the server in the client clipboard

### Other info ###

Works though the other way around:

1. move to client via hotkey
2. copy txt/link on client pc
3. move to server via hotkey
4. clipboard from client is stored correctly inside server clipboard

**Comment by XinyuHou** [comment] 2016-12-30 14:57
Duplicate of #5729

**Closed by XinyuHou** 2016-12-30 14:57 UTC
