### ISSUE TITLE
Synergy forgets that I already upgraded to pro

### ISSUE THREAD

**Issue by dwright** [symless/synergy#5934] opened 2017-03-27 17:23 UTC
### Operating Systems ###

Server: Ubuntu 16.04.1 LTS
Client: Mac OSX 10.12

### Synergy Version ###

1.8.8-stable

### Steps to reproduce bug ###

1.   Purchase regular synergy, key regular key.
2.   Install synergy.    Use regular key.
3.   Upgrade synergy.     Synergy remembers regular key.
4.   Upgrade to synergy pro.    Replace old key with new one.
5.   Synergy thanks you for upgrading.
6.   Upgrade to next version of synergy.
7.   Key inside synergy has reverted back to original regular key.     You must go to website and download current pro key and "upgrade" again on every single server / client.

### Other info ###

* When did the problem start to occur?
    Has always happened since I've upgraded to pro.    I go through this with each version upgrade.

* Is there a way to work around it?
   You have to log into the synergy website, copy the key, and paste it into every one of your servers / clients again.      Which, you have to do manually on each machine because SSL is broken everywhere until you do.

* Does this bug prevent you from using Synergy entirely?
    No.   In as much as being out of gasoline does not prevent you from using a car entirely.   It just makes it super inconvenient.

**Comment by XinyuHou** [comment] 2017-03-30 12:16
Duplicate of #5733

**Closed by XinyuHou** 2017-03-30 12:16 UTC
