### ISSUE TITLE
File Transfer Status Indicator

### ISSUE THREAD

**Issue by stinker1978** [symless/synergy#5940] opened 2017-03-27 18:59 UTC
### Operating Systems ###

Server: macOS 10.12.3
Client: Windows 10 1607 Build 14393.953

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

Feature Request - For file transfers between machines, can you add a status indicator showing that the copy is happening?  If there is one there, then it's not showing between my machines.

**Comment by XinyuHou** [comment] 2017-03-30 12:22
Duplicate of #4745

**Closed by XinyuHou** 2017-03-30 12:22 UTC
