### ISSUE TITLE
Automatic mapping of additional mouse buttons between different systems

### ISSUE THREAD

**Issue by TurkeyMan** [symless/synergy#4202] opened 2014-11-08 02:04 UTC
I notice that mouse buttons 4 and 5 (usually 'back' and 'forward' in windows and linux) don't seem to work by default.
There is a workaround to map them, but I haven't managed to do it properly (only got 'back' working). Perhaps there should be an option in the config, or just do this by default?

**Comment by XinyuHou** [comment] 2017-04-21 13:39
Duplicate of #4441

**Closed by XinyuHou** 2017-04-21 13:39 UTC
Labels: bug

**Comment by vinozganic** [comment] 2024-03-10 17:48
Has any of you got it working for combination: 
Server: MacOS, Client: Windows

I need my additional page back and page forward keys to work :(
None of the combinations for options section in config worked for me...
