### ISSUE TITLE
Logitech mouse button settings broken

### ISSUE THREAD

**Issue by Syngenuity** [symless/synergy#4211] opened 2014-11-10 13:39 UTC
Tested: upgraded from 1.6.0 (shift key not working) to 1.6.1 and gained the shift key usage on the client again (leaving all system32 and syswow64 files intact, from last update).

At that point, the shift key functionality was returned; however, I lost all my Performance Mouse MX settings which worked perfectly on the host & client computers in the last version.

I verified this, by uninstalling 1.6.1 and re-installing 1.6.0 on the host (leaving the client @ 1.6.1) and all Logitech settings were returned... working on both the client and server computers.

Please see settings in the screenshot, attached.

Please review and respond.

Thanks,

Rob
![image](https://cloud.githubusercontent.com/assets/7465105/4976569/99429e2e-68b3-11e4-9265-0909e78c4ad1.png)

**Comment by XinyuHou** [comment] 2017-04-21 13:57
Duplicate of #3809

**Closed by XinyuHou** 2017-04-21 13:57 UTC
Labels: bug
