### ISSUE TITLE
Compiling error Sierra 10.12

### ISSUE THREAD

**Issue by nbeazy** [symless/synergy#5676] opened 2016-10-17 15:39 UTC
### Operating Systems ###

Sierra 10.12

### Synergy Version ###

1.8.4

### Steps to reproduce bug ###

1. brew install cmake and qt5
2. Fixed "./ext/toolchain/commands1.py" qt5 folders to point to local versions of 5.7.0 and compile "./hm.sh conf -g2 --mac-sdk 10.10 --mac-identity test"
3. Returns error, could not find qmake. Cannot continue without qmake.

### Other info ###

Tried compiling in xcode as well and xcode fails for null value

**Comment by XinyuHou** [comment] 2016-10-19 10:09
@nbeazy 
Please sit tight. I are just working on this issue in our next release.

Duplicate of #5626

**Closed by XinyuHou** 2016-10-19 10:09 UTC

**Comment by nbeazy** [comment] 2016-11-08 17:00
I still get a could not find qmake error when runnning "./hm.sh conf -g1 --mac-sdk 10.12 --mac-identity Sierra".  Any potential solutions to this?

**Comment by jasonklotzer** [comment] 2017-01-04 06:44
After installing qt (`brew install qt)`, you should also setup your PATH to include the QT bin directory. 

One way to do this is the following in your .bash_profile:
 `export PATH=/usr/local/Cellar/qt5/5.x.x_x/bin:$PATH`

**Comment by revolter** [comment] 2017-03-18 12:49
You also need to change it on every Qt update :|
