### ISSUE TITLE
Mouse in Photoshop CS5 does not work when Synergy Server is running on the same PC.

### ISSUE THREAD

**Issue by SteveRMann** [symless/synergy#5500] opened 2016-07-24 22:11 UTC
This seems to be a widespread issue, so I am a bit surprised to see it not reported here. (Search for Photoshop = no hits).

Using Photoshop CS5 for years on Win7 and now Win10.
Installed Synergy on my "main" PC that also has Photoshop CS5 installed.
Now, mouse commands in Photoshop, particularly draw a marquee or shape, or right-click on a layer do not work.
In Task Manager, stopped Synergy.
Photoshop works fine.

Not an acceptable workaround.

**Comment by ccoenen** [comment] 2016-07-25 20:14
I sometimes have problems with adobe illustrator, where I can't use the <kbd>spacebar</kbd> shortcut to pan the canvas. Stopping/Starting the server usually solves this. I agree, this is not a good situation.

**Comment by staaronis3** [comment] 2016-07-26 03:31
Try to update to [1.8.2 RC1](http://symless.com/nightly?filter=synergy-v1.8.2-rc1-12e0120) and it will fix the problems.

**Comment by XinyuHou** [comment] 2016-08-02 16:09
Duplicate of #3044

**Closed by XinyuHou** 2016-08-02 16:09 UTC

**Comment by darkdragon-001** [comment] 2016-08-05 11:15
I had the same problem with Photoshop CS6 and Win7/Win10. It seems to be fixed by [1.8.2 RC1](http://symless.com/nightly?filter=synergy-v1.8.2-rc1-12e0120)!
