### ISSUE TITLE
Cursor goes to wrong monitor on return from client to server (Mac server, Linux client)

### ISSUE THREAD

**Issue by jmznxn77** [symless/synergy#5935] opened 2017-03-27 17:40 UTC
### Operating Systems ###

Server: microOS Sierra
Client: Ubuntu 16.0.4

### Synergy Version ###

1.8.8-stable-25a8cb2

### Steps to reproduce bug ###

The bug occurs when using a mac server in a multimonitor setup.
Specifically for me, I have a macbook pro with its built-in monitor to the left, a monitor in front of me connected to the mac, and a monitor attached to the linux client on the right.
Display arrangement for the mac is configured normally in the system preferences.
Synergy configuration shows only one square for mac server, and linux client is positioned to the right of that.

1. Use mouse on linux client
2. Move mouse back to mac server

Sometimes the cursor jumps from the linux monitor to the Macbooks built-in display (left screen) instead of to the external monitor (center screen/screen adjacent to client)

Screenshot of configurations:
<img width="1460" alt="screen shot 2017-03-27 at 1 38 23 pm" src="https://cloud.githubusercontent.com/assets/14592193/24369673/c3cc9974-12f2-11e7-9af5-277b8c91a652.png">
.

**Comment by XinyuHou** [comment] 2017-03-30 12:20
Duplicate of #5489

**Closed by XinyuHou** 2017-03-30 12:20 UTC
