### ISSUE TITLE
UGH! Mouse won't click on secondary computer randomly. 

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [symless/synergy#5821] opened 2017-01-26 16:03 UTC
### Operating Systems ###

Server: Windows 10
Client: Mac OS Sierra

### Synergy Version ###

1.8.7-Stable 9799e96

### Steps to reproduce bug ###

1. Move mouse to secondary (client) computer (mac)
2. try and CLICK anything (cursor shows but nothing will click)
3. Keyboard magically works

No errors beyond "WARNING: cursor may not be visible

### Other info ###

* When did the problem start to occur? It happens randomly. 
* Is there a way to work around it? No, I have to shut off and reboot and its annoying
* Does this bug prevent you from using Synergy entirely? Yes

**Comment by Xeteon** [comment] 2017-01-27 00:11
Can confirm this bug
I have to restart the service each time this occurs

**Comment by legonigel** [comment] 2017-01-28 20:33
I believe this is a duplicate of #5716.

**Comment by BrickerBrickerOneNine** [comment] 2017-01-29 01:32
No. It's not

**Comment by Traste** [comment] 2017-02-13 07:42
+1
Using Synergy between two windows machines;
1 Windows 7 Enterprise 64bit
1 Windows 10 Pro 64 bit
Connection is over VPN between two machines on the same home network (using port 443), no SSL as that is not working at all.
The issue occurs intermittently, i have seen no pattern as of yet.

**Comment by erikliland** [comment] 2017-02-16 08:56
I am experiencing the same problem with a Windows 10 server, and a Mac Book client.
I'm not using SSL, and the problem goes away if I restart / reconnect.

**Comment by paolosaurus** [comment] 2017-02-21 19:39
I am seeing the same thing.  On Windows 8 server with MacBook client running latest OS. 

Seemingly at random the mouse buttons on the client (the MacBook) will stop working.  Moving the cursor back to the server's screen and clicking around will sometimes fix it but generally I have to restart the server.

This is the main issue I am having with Synergy and it is affecting my productivity :(

Config file attached.

[synergy.txt](https://github.com/symless/synergy/files/791289/synergy.txt)

**Comment by legonigel** [comment] 2017-02-22 15:13
If someone can reproduce this issue and provide [logs](https://github.com/symless/synergy/wiki/Sending-logs) it would help the developers to be able to fix the issue.

**Comment by erikliland** [comment] 2017-02-23 08:16
Here is some log files and description of what happened:

Client, MacBook Pro (MacOS 10.12.3) freshly restarted, Synergy running and waiting for server. 
Server, Widows 10 freshly restarted, synergy running from automatic startup. 
Mouse can be moved between desktops without any problem, but mouse clicks are not registered.
Server log: http://pastebin.com/VME3cmvT
Client log: http://pastebin.com/9UgN5gFR

If stopping and starting Synergy on the server, or pressing apply on the server, the clicking is working properly again. The problem is re-producable without doing anything on the Mac, and the problem is solvable without doing anything on the Mac.

**Comment by denormalizer** [comment] 2017-02-28 23:44
Just want to report my configuration in case there is a pattern

    Server: Windows 10
    Client 1: Ubuntu 16.04
    Client 2: Mac OSX 10.11

I'll keep an eye out for the logs when it next happens.

**Comment by XinyuHou** [comment] 2017-03-01 16:07
duplicate of #5716.

**Closed by XinyuHou** 2017-03-01 16:07 UTC

**Comment by paolosaurus** [comment] 2017-03-01 18:24
I do not think this is a duplicate of #5716.

**Comment by legonigel** [comment] 2017-03-01 18:35
@paolosaurus how is this not a duplicate of #5716 ? Both issues show the mouse not clicking on a Mac OS client with a Windows server that can be fixed by restating the service. 

If you do believe this is a different issue please provide logs of both the client and the server with log level debug2 and compare them to the logs in #5716

**Comment by paolosaurus** [comment] 2017-03-01 20:37
Just because the steps to reproduce the bug are different.  For #5821, I am not booting servers or hearing error sounds.  What I am seeing is the mouse click on the Mac OS client working fine and then after some time it suddenly stops working, seemingly at random.

**Comment by BrickerBrickerOneNine** [comment] 2017-03-02 15:35
exactly what Paolosaurus said, so instead of closing tickets and marking
them as "duplicate" lets fix the issue for your paid products and validate
the issues are indeed the very exact same.

**Comment by denormalizer** [comment] 2017-03-07 04:52
I have found another workaround to this non mouse click issue.

* Go back to Synergy server window
* Click anywhere on window. eg. Log
* Go back to client
* Mouse click now works on client

Can anyone else confirm this also works for them?

**Comment by paolosaurus** [comment] 2017-03-07 05:07
Yes I found this work around also. I can also click in other windows on the server (not just the synergy server window) and if often fixes the click  problem on the client.

**Comment by denormalizer** [comment] 2017-03-30 23:17
I noticed the following log lines in the client prior to this issue arising, not sure if relevant:

> [2017-03-31T10:09:49] INFO: found key in group 0
> [2017-03-31T10:11:32] INFO: found key in group 0
> [2017-03-31T10:11:48] INFO: found key in group 0
