### ISSUE TITLE
Edge detection issues on multi-monitor client with different resolutions/DPI

### ISSUE THREAD

**Issue by Sertelegger** [symless/synergy#5201] opened 2016-01-29 00:37 UTC
This seems similar to https://github.com/symless/synergy/issues/5030, but unfortunately the issue still isn't fixed for me.

My scenario is like this:
Server: Windows 10 on a Surface Pro 2 @ 1920x1080 with 150% DPI
Host: Windows 10 on a system with two displays: Display 1 = 3840x2160 with 150% DPI, Display 2 = 2560x1600 with 100% DPI
The displays are laid out so that when I leave the server on the right edge I got to Display 1 then Display 2.

Experienced:
1. I leave the Server system, edge works fine (*)
2. I move the mouse to the right edge of Display 1 on the client system and enter Display 2.
3. I keep moving the mouse to the right. When I'm at about 30% of Display 2 the mouse suddenly jumps back to Display 1 to about the 85% mark.
4. I keep moving the mouse to the right and enter Display 2 again. Now it works fine and I can get all the way to the edge of Display 2.
5. When I move left again I get the same in reverse. I enter Display 1 and when I'm at about 85% the mouse jumps back to Display 2 around the 30% mark and I have to keep moving the mouse the really get back onto Display 1 again.

This repros for me 100% of the time in this configuration. Since you can eventually get to where I want to move the mouse if you just keep moving in that direction there is a workaround, but it's annoying as hell.

(*) As a side note, and this should probably be filed as a separate issue, if I plug my 4K display into the Surface 2 leave only one display on the client system, then unless I restart the Synergy service things don't work at all after switching to the client system. The mouse pointer will just sit in a corner and I can't switch back to the server system anymore with the mouse.

**Comment by fuzzzerd** [comment] 2016-02-02 16:31
I experience almost exactly the same issue, with the mouse moving from one display back to the previous one. My setup is slightly different:

Server: Windows 10, Single Display
Client: Windows 10, Surface Pro 2, Dual Display: 1920x1080@150% dpi (built-in) and 1920x1080@100%

I experience issues moving from Server <=> Client (either direction) as well as going from Surface Display to Second Monitor. I experience almost exactly #3 above.

Setting all displays to the same DPI seems to eliminate this issue; it appears from my testing that the issue is mixing DPI settings.

**Comment by S1ack** [comment] 2016-02-09 18:39
Same issue,
Client Windows 10 Lenovo Yoga 2 pro with dock and monitor (native is 3200x1800, dock is 1920 x 1080) I have had to play with DPI setting to get some programs functional.

Server Windows 7 Dell aslo docked with 2 monitors 1920x1080 and native at 1920x1080

**Comment by Doridian** [comment] 2016-02-11 13:26
My setup is as follows (right to left): 1080p display W10 (100%), 4k display W10 (125%), Macbook Pro Retina.

Switching from the 4k display to the MBP does not work as the right edge of that display is not recognized at all.
If I enable compatibility mode as suggested in the other issue, I suddenly get the right edge of the 4k screen recognized in the middle of said screen and then my mouse cursor gets stuck in the bottom-right corner of the MBP's display.

**Comment by aschaerorange** [comment] 2016-05-09 12:29
Hi, I experiment another issue, but related to edge detection (and screen disposition) as stated in this issue's title.

my config is as follow :

linux client (left, 1280x1024) <----> windows server screen 1 (1280x1024) (main, with start button)
                                                               ^
                                                               |
                                                               v
                                                        windows server screen 2 (bellow 1st one, 1368x768)

- I can NOT switch to client, from left border of windows server screen 1 (bug here)
- I can switch to client left, from windows server screen 2 (working as expected)
- when I come back from client to server, I can land on server screen 1 or 2 (working as expected)

**Comment by daveseah** [comment] 2016-08-29 13:13
I just added a 1080P monitor to my Windows 10 box and am discovering this jumping issue. I have a Macbook Pro 15 on the left, and a Windows 10 box on the right. Both systems have two monitors. 

Mac Laptop ++ 1920x1080 -- PC 2560x1440 ++ 1920x1080I

I uploaded a video [showing the jumping](https://youtu.be/fjJcVIzWTmg) to YouTube. It sounds a lot like Sertelegger's issue from January.

**Comment by XinyuHou** [comment] 2016-10-28 13:48
Can someone test this nightly please?
http://symless.com/nightly?filter=issue5186-different-dpi-rc1-8d193c7

**Comment by XinyuHou** [comment] 2016-10-28 13:48
Duplicate of #5186

**Comment by PhRX** [comment] 2016-12-22 07:52
Still broken in 1.8.6. Setup : laptop runs Win10, with High-DPI screen (3840x2160) [S1], with second monitor (1920x1080) [S2] to the right. Second is set as Main. Laptop runs synergy 1.8.6 as client.
Desktop runs linux, also 2 monitors (1600x1200 left, main [S3]; 1920 x 1080 right [S4]). Runs synergy 1.8.6 as server. Laptop screen is set to left of desktop screen.
so, it looks like : S1 - S2 - S3 - S4

I get the "looping" effect : start cursor on S3, move to S2 then S1. About 30% in S1 the cursor jumps again to the right of S2, continue moving to left then traverses S2 and S1 "normally". Jump/loop also occurs in exact reverse when moving cursor to the right again.
Still broken in 1.8.6. Setup : laptop runs Win10, with High-DPI screen (3840x2160) [S1], with second monitor (1920x1080) [S2] to the right. Second is set as Main. Laptop runs synergy 1.8.6 as client.
Desktop runs linux, also 2 monitors (1600x1200 left, main [S3]; 1920 x 1080 right [S4]). Runs synergy 1.8.6 as server. Laptop screen is set to left of desktop screen.
so, it looks like : S1 - S2 - S3 - S4

I get the "looping" effect : start cursor on S3, move to S2 then S1. About 30% in S1 the cursor jumps again to the right of S2, continue moving to left then traverses S2 and S1 "normally". Jump/loop also occurs in exact reverse when moving cursor to the right again.

**Comment by llavalle** [comment] 2017-04-03 19:58
@XinyuHou  Looks like your nightly link is broken for me.  Running 1.8.8-stable (March 16th build) and still having the problem.

**Comment by grant100** [comment] 2018-06-06 19:13
Synergy 2 is a trash fire, and this is still broken.

**Comment by nbolton** [comment] 2024-09-06 22:03
This issue has been inactive for a while so I'll close it for now. 
Please let me know if this is still an issue so that I can reopen it.

**Closed by nbolton** 2024-09-06 22:03 UTC
Labels: bug, triage, unanswered
