### ISSUE TITLE
Hotkeys / app on computer sleep

### ISSUE THREAD

**Issue by Duwayne6** [symless/synergy#5498] opened 2016-07-23 19:11 UTC
everytime i reboot or my computer goes to sleep, all of my applications with global hotkeys no longer work, and i have to open synergy, hit "start" then "apply" and they work again.

this causes alot of weird issues with some of my apps that have hotkeys, ie voice applications, gpu monitoring app, mouse software. ect.

**Comment by XinyuHou** [comment] 2016-08-02 10:01
Duplicate of #5358

**Closed by XinyuHou** 2016-08-02 10:01 UTC
