### ISSUE TITLE
ERROR: failed to get desktop path, no drop target available, error=2

### ISSUE THREAD

**Issue by dleghthikos** [symless/synergy#5971] opened 2017-04-03 18:55 UTC
### Operating Systems ###

windows 10 version 1703 (os build 15063.11)

### Synergy Version ###

1.8.8-stable-ec56ac4

### Steps to reproduce bug ###

1. have synergy set to elevate privilidges 'always'
2. the error will be logged every time synergy is started

### Other info ###

ERROR: failed to get desktop path, no drop target available, error=2

drag-and-drop file transfer does not work

the problem started upon update of windows to aforementioned insider preview build (it was on the 'release preview' ring)

**Comment by XinyuHou** [comment] 2017-04-06 11:54
Duplicate of #4987

**Closed by XinyuHou** 2017-04-06 11:54 UTC

**Comment by cenzwong** [comment] 2021-02-08 11:12
For me, i suffer from this problem too. But it turns out that it is because my keyboard has turn on scroll lock accidently and makes it not work. and have "ERROR: failed to get desktop path, no drop target available, error=2" this error. Turning off scroll lock on your keyboard and it will become normal again.

HOPE this help!

**Comment by neosinan** [comment] 2022-08-14 12:51
> For me, i suffer from this problem too. But it turns out that it is because my keyboard has turn on scroll lock accidently and makes it not work. and have "ERROR: failed to get desktop path, no drop target available, error=2" this error. Turning off scroll lock on your keyboard and it will become normal again.
> 
> HOPE this help!

Thank you, You solved my problem.
